### ISSUE TITLE
Calling the confirmPayment method without a params object causes exception

### ISSUE THREAD

**Issue by tbuczkowski** [flutter-stripe/flutter_stripe#1246] opened 2023-05-19 11:38 UTC
**Describe the bug**
I have a `paymentIntentClientSecret` that is created on the back-end with a payment method already attached. From my understanding, I should be able to call the `confirmPayment` method without providing the `params` object in a scenario like mine. Here's the method call in my code:
```
await _stripe.confirmPayment(paymentIntentClientSecret: clientSecret);
```
which results in the following errors:
IOS:
```
flutter: PlatformException(Invalid Params, , , null)
flutter: 
#0      JSONMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:171:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:310:18)
<asynchronous suspension>
#2      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:510:43)
<asynchronous suspension>
#3      MethodChannelStripe.confirmPayment (package:stripe_platform_interface/src/method_channel_stripe.dart:95:20)
<asynchronous suspension>
#4      Stripe.confirmPayment (package:flutter_stripe/src/stripe.dart:410:29)
<asynchronous suspension>
```
Android:
```
I/flutter ( 9138): PlatformException(error, org.json.JSONObject$1 cannot be cast to org.json.JSONObject, null, java.lang.ClassCastException: org.json.JSONObject$1 cannot be cast to org.json.JSONObject
I/flutter ( 9138): 	at com.flutter.stripe.StripeAndroidPlugin.onMethodCall(StripeAndroidPlugin.kt:287)
I/flutter ( 9138): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
I/flutter ( 9138): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
I/flutter ( 9138): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
I/flutter ( 9138): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
I/flutter ( 9138): 	at android.os.Handler.handleCallback(Handler.java:938)
I/flutter ( 9138): 	at android.os.Handler.dispatchMessage(Handler.java:99)
I/flutter ( 9138): 	at android.os.Looper.loopOnce(Looper.java:201)
I/flutter ( 9138): 	at android.os.Looper.loop(Looper.java:288)
I/flutter ( 9138): 	at android.app.ActivityThread.main(ActivityThread.java:7839)
I/flutter ( 9138): 	at java.lang.reflect.Method.invoke(Native Me
I/flutter ( 9138): #0      JSONMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:181:7)
I/flutter ( 9138): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:310:18)
I/flutter ( 9138): <asynchronous suspension>
I/flutter ( 9138): #2      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:510:43)
I/flutter ( 9138): <asynchronous suspension>
I/flutter ( 9138): #3      MethodChannelStripe.confirmPayment (package:stripe_platform_interface/src/method_channel_stripe.dart:95:20)
I/flutter ( 9138): <asynchronous suspension>
I/flutter ( 9138): #4      Stripe.confirmPayment (package:flutter_stripe/src/stripe.dart:410:29)
I/flutter ( 9138): <asynchronous suspension>
```

Looking at the flutter_stripe native code, I think I've been able to find the exact code causing the issue. Keep in mind though that my knowledge of swift/kotlin is limited so I might be wrong about this.
`StripePlugin.swift`:
```swift
func confirmPayment(_ call: FlutterMethodCall, result: @escaping FlutterResult) {
    guard let arguments = call.arguments as? FlutterMap,
    let paymentIntentClientSecret = arguments["paymentIntentClientSecret"] as? String,
    let params = arguments["params"] as? NSDictionary, // the params object should be optional, but if it's nil, the invalidParams error is thrown
    let options = arguments["options"] as? NSDictionary else {
        result(FlutterError.invalidParams)
        return
    }
    confirmPayment(
        paymentIntentClientSecret: paymentIntentClientSecret,
        params: params,
        options: options,
        resolver: resolver(for: result),
        rejecter: rejecter(for: result)
    )
}
```
`StripeAndroidPlugin.kt`:
```kotlin
"confirmPayment" -> stripeSdk.confirmPayment(
    paymentIntentClientSecret = call.requiredArgument("paymentIntentClientSecret"),
    params = call.requiredArgument("params"), // should be optional instead of required
    options = call.requiredArgument("options"),
    promise = Promise(result)
)
```

I would much appreciate a quick fix to this or an alternate solution, as this issue is a blocker for the project I'm working on.

**To Reproduce**
1. Outside of the flutter app create a payment intent with a payment method attached,
2. Call `await _stripe.confirmPayment(paymentIntentClientSecret: clientSecret);`,
3. You will get an exception.

**Expected behavior**
The payment should be confirmed.

**Smartphone / tablet**
 - Device: Android emulator, iOS simulator
 - OS: Android 12, iOS 16.1
 - Package version: 9.2.0
 - Flutter version: 3.10

**Comment by jonasbark** [comment] 2023-05-22 14:11
Thanks - fix is incoming

**Comment by tbuczkowski** [comment] 2023-06-05 07:38
Hi, any updates on a fix for this issue? I'm still getting the same errors on 9.2.1.

**Comment by remonh87** [comment] 2023-06-05 07:51
can you double check you also have 9.2.1. for stripe_ios and stripe_android?

**Comment by tbuczkowski** [comment] 2023-06-05 10:33
Yes, `stripe_ios`, `stripe_android` are 9.2.1 on my machine. I ran `flutter clean` and `flutter pub cache repair` to make sure the correct versions are being used.

**Comment by tbuczkowski** [comment] 2023-06-09 05:42
Any updates on this issue?

**Comment by tbuczkowski** [comment] 2023-06-13 09:28
@remonh87 I looked at the fix you commited and I believe it is wrong. It fixes the parameters parsing crash, but breaks the case, where I'm trying to confirm a payment that comes with a payment method attached from the back-end. Because you provide an empty object when params are null, the lower level SDK thinks the payment method should be created locally and throws the following error:
```
LocalizedErrorMessage(code: FailureCode.Failed, localizedMessage: You must provide paymentMethodType, message: You must provide paymentMethodType, stripeErrorCode: null, declineCode: null, type: null)
```
I believe instead of handling null in Dart, the fix should consist of fixing the parsing in the native code.

**Comment by remonh87** [comment] 2023-06-13 09:47
hmm good catch. @jonasbark  can you have a look at it again? I can reproduce the crash. It is super funky what is happening because in your inline function you do create an empty `JsonObject`  when it is null. However  when I execute in this scenario the line `Log.e("foo", "${argument<Any?>(key)} ${argument<Any?>(key)==null}"`  it prints `null, false`. This is a case that Kotlin fake null safety but isn't sound null safe.

**Comment by tbuczkowski** [comment] 2023-06-19 06:34
Again, the issue wasn't fixed, but the thread was closed.

**Comment by tbuczkowski** [comment] 2023-06-23 10:58
I have posted a PR with a possible fix - could someone take a look at it?

**Closed** 2023-06-29 18:57 UTC
Labels: needs triage
