### ISSUE TITLE
iOS 12 - Apple pay payment - Stripe.instance.presentPaymentSheet() method not completing

### ISSUE THREAD

**Issue by seanyyyyyy** [flutter-stripe/flutter_stripe#502] opened 2021-12-29 01:10 UTC
**Description**
On iOS 12 after making a successful payment with Apple Pay through the Payment Sheet, await Stripe.instance.presentPaymentSheet() function does not complete

**To Reproduce**
1. initialised payment sheet with proper info, then called await Stripe.instance.presentPaymentSheet()
2. payment sheet appears, press Apple Pay button
3. apple pay sheet appears, select card, confirm payment, success, apple pay sheet closes (successful payment appears in Stripe portal)
4. in app, await Stripe.instance.presentPaymentSheet() does not complete, no subsequent lines called, no errors in logs

**Expected behavior**
presentPaymentSheet() should complete, this flow works on iOS 13, 14 & 15 (Simulator)

**Smartphone / tablet**
 - Device: iPhone 6 (error also seems to occur on Simulator iOS 12.4)
 - OS: iOS 12.5.5
 - Package version: 2.1.0
 - Flutter version 2.8.1

**Comment by remonh87** [comment] 2021-12-30 10:27
This can be a bug in the Stripe native sdk need some investigation there. If this is the case, I do not expect high priority on this issue from the Stripe side since iOS12 is quite ancient.

**Comment by remonh87** [comment] 2022-01-06 09:16
could reproduce the issue I created a ticket for Stripe:  https://github.com/stripe/stripe-react-native/issues/765

**Comment by remonh87** [comment] 2022-03-27 13:58
On react native it works but it looks like there is some flutter issue with iOS12. For now I close it since this OS is really ancient.

**Closed** 2022-03-27 14:00 UTC
Labels: bug, blocked
