### ISSUE TITLE
Compatibility Issue: Concurrency Errors on iOS 15.0 with flutter_stripe Library

### ISSUE THREAD

**Issue by hwasiq** [flutter-stripe/flutter_stripe#1355] opened 2023-08-03 14:40 UTC
### Issue Summary
I'm encountering compatibility errors related to concurrency features when using the flutter_stripe library on iOS 15.0. These features are only available in iOS 15.0 and newer, leading to build failures.

### Actual Behavior
The build fails with the following error messages:
"Swift Compiler Error: Concurrency is only available in iOS 15.0.0 or newer"
"Swift Compiler Error: 'resume(with:)' is only available in iOS 15.0 or newer"
"Swift Compiler Error: 'resume(with:)' is only available in iOS 15.0 or newer"
"Swift Compiler Error: 'withCheckedThrowingContinuation(function:_:)' is only available in iOS 15.0 or newer"
"Uncategorized (Xcode): Command CompileSwiftSources failed with a nonzero exit code"
ios/Pods/StripePayments/StripePayments/StripePayments/Source/API%20Bindings/STPAPIClient+Payments.swift:721:25

- Flutter version: 3.7.6
- flutter_stripe 9.3.0
- iOS deployment target: 15.0
- Xcode version: 13.1

**Comment by remonh87** [comment] 2023-08-03 18:20
Can you upgrade to Xcode 13.2?  I think concurrency is not supported in your Xcode version

**Comment by JosephKalash** [comment] 2023-08-05 19:20
i think my issue is similar to this Flutter project build is fail when add flutter_stripe package
this is the output of flutter run command:
`Uncategorized (Xcode): Command CompileSwift failed with a nonzero exit code


Swift Compiler Error (Xcode): 'data(for:delegate:)' is only available in iOS 15.0 or newer
/Users/joseph/development/flutter/flutter_application_2/ios/Pods/StripePaymentsUI/StripePaymentsUI/StripePaymentsUI/Source/UI
%20Components/PaymentMethodMessagingView.swift:296:55


Swift Compiler Error (Xcode): Cannot infer return type for closure with multiple statements; add explicit type to
disambiguate
/Users/joseph/development/flutter/flutter_application_2/ios/Pods/StripeFinancialConnections/StripeFinancialConnections/Stripe
FinancialConnections/Source/Native/NetworkingLinkSignupPane/NetworkingLinkSignupViewController.swift:290:61


Could not build the application for the simulator.
Error launching application on iPhone 13 Pro.`

Flutter: 3.10.6
stripe: 9.3.0
xcode: 3.14
ios deployment target: 15.0

**Comment by hwasiq** [comment] 2023-08-05 19:40
No suitable solution has been found yet, even after updating Xcode.

**Comment by JosephKalash** [comment] 2023-08-05 19:54
@hwasiq it's sad to hear that. is there an older version of the package which will be compatible with my env and not cause these build issues

**Comment by hwasiq** [comment] 2023-08-05 20:08
I tried using flutter_stripe: ^9.2.2 as well, and I'm facing the same issue here too. The platform for this is also appearing as unknown on pub.

**Comment by JosephKalash** [comment] 2023-08-05 20:18
I will try older version with IOS target 14.0. it should be work in certain version.

**Comment by hwasiq** [comment] 2023-08-05 20:23
Could you please tell me which version of flutter_stripe you have used to resolve an issue?

**Comment by JosephKalash** [comment] 2023-08-05 20:44
no I didn't solve the issue yet. i meant i will try other versions and one of them should be work, because it's not possible to keep crash the build

**Comment by JosephKalash** [comment] 2023-08-06 13:39
@hwasiq the error in my case is represents in two files the first one is in file NetworkingLinkSignupViewController.swift line 291
`                            if !didPrefillPhoneNumber {
                                let didPrefillEmailAddress = {
                                   `
                                
and you can solve it by add Bool type to didPrefillEmailAddress var to explicitly define the type:
`  if !didPrefillPhoneNumber {
                                let didPrefillEmailAddress: Bool = {`
                                
the second is in PaymentMethodMessagingView.swift line 296
`static func loadImage(url: URL, apiClient: STPAPIClient) async throws -> UIImage? {
         let request = apiClient.configuredRequest(for: url)
         let (data, _) = try await apiClient.urlSession.data(for: request)
         return UIImage(data: data, scale: 3)?.withRenderingMode(.alwaysOriginal)
    }`
    
   the error says Swift Compiler Error (Xcode): 'data(for:delegate:)' is only available in iOS 15.0 or newer
   I think the issue is the code not compatible with IOS or swift version. I'm not expert with swift and IOS development so i couldn't figure it out but i will try solve the problem.
  right now i commented the content of this function

**Comment by remonh87** [comment] 2023-08-07 06:35
I am able to compile it. Also make sure to have have the latest flutter hotfix for 3.7, I think it is `3.7.12` . I know the Flutter team back ported  some Xcode command tools fixes

**Comment by 743306400** [comment] 2023-08-10 07:49
Is there a solution to this problem? I also encountered it

**Comment by JosephKalash** [comment] 2023-08-20 07:38
Unfortunately No they didn't fix it yet

**Comment by remonh87** [comment] 2023-08-27 14:18
please provide a reproduction example so we can further triage it because else I am inclined to close it. Can you try to compile the example app on iOS15?

**Closed** 2023-09-25 19:36 UTC
Labels: Awaiting response, needs triage
