### ISSUE TITLE
Android - Something wrong with CardFormField style

### ISSUE THREAD

**Issue by HeckYeah-01** [flutter-stripe/flutter_stripe#746] opened 2022-05-25 16:09 UTC
The issue is : 
When I used the CardFormField with Android I noticed the Unselected Text is not consistent across the fields, The Selected Text color is not the same as iOS, also the CVC field image that has used for the Discover card,  Zip Code text is white color, see the picture below 

<img width="219" alt="Screen Shot 2022-05-25 at 11 56 11 AM" src="https://user-images.githubusercontent.com/21050076/170307182-a350bdb9-c173-4cc5-94ea-3ca0822a7fa5.png">

<img width="223" alt="Screen Shot 2022-05-25 at 12 05 14 PM" src="https://user-images.githubusercontent.com/21050076/170307334-5be36caa-f2ae-4c82-bec2-5b165ff86f26.png">

```
CardFormField(
                    style: CardFormStyle(
                      borderColor: Colors.black,
                      borderRadius: 20,
                      backgroundColor: Colors.grey.shade200,
             ),
      ),
```

 - Device: Android Pixel 4 - Emulator 
 - OS:  Android 13
 - Package version: 3.0.0
 - Flutter version 3.0.1

**Comment by remonh87** [comment] 2022-05-26 07:52
duplicate of #731

**Closed by remonh87** 2022-05-26 07:52 UTC
Labels: needs triage

**Comment by priyankabambharoliya-official** [comment] 2022-06-03 07:09
I have same issue
