### ISSUE TITLE
CardField not showing and throwing exception on flutter_stripe 2.1.0, flutter 2.8.1

### ISSUE THREAD

**Issue by aris-1** [flutter-stripe/flutter_stripe#534] opened 2022-01-13 05:03 UTC
Same as https://github.com/flutter-stripe/flutter_stripe/issues/393, but since that is closed and not getting any reply, I opened a new one.

Applied all  the requirements at https://github.com/flutter-stripe/flutter_stripe#android, but still not working.
Tried calling applySettings as suggested by jonasbark on above mentioned issue, but that also gives an error.

Using:
flutter_stripe: ^2.1.0
Flutter  2.8.1
ext.kotlin_version = '1.5.0'

### Code:

```
import 'package:flutter_stripe/flutter_stripe.dart';
Stripe.publishableKey = "xxxxxx";
final stripeCardController = CardEditController();

Container(child: CardField(
controller: stripeCardController,
onCardChanged: (card) {
print("onCardChanged1 $card");
},
));
```

### Checked requirements:

- Android 5.0 (API level 21) and above
   minSdkVersion 21

- Kotlin version 1.5.0 and above: 
ext.kotlin_version = '1.5.0'

- Using a descendant of Theme.AppCompat for your activity
in values/styles.xml
```
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <style name="LaunchTheme" parent="@android:style/Theme.Black.NoTitleBar">
        <!-- Show a splash screen on the activity. Automatically removed when
             Flutter draws its first frame -->
        <item name="android:windowBackground">@drawable/launch_background</item>
    </style>
    <style name="NormalTheme" parent="Theme.AppCompat.Light.NoActionBar">
        <item name="android:windowBackground">?android:colorBackground</item>
    </style>
</resources>
```

- Using an up-to-date Android gradle build tools version:

 ```
   dependencies {
        classpath 'com.android.tools.build:gradle:4.1.2'  
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"  
     distributionUrl=https\://services.gradle.org/distributions/gradle-6.7-all.zip
```

- Using FlutterFragmentActivity instead of FlutterActivity in MainActivity.kt:

```
  import io.flutter.embedding.android.FlutterActivity
  import io.flutter.embedding.android.FlutterFragmentActivity 
class MainActivity: FlutterFragmentActivity() { 
}
```

### Error report:
E/MethodChannel#flutter/platform_views(14280): Failed to handle method call
E/MethodChannel#flutter/platform_views(14280): kotlin.UninitializedPropertyAccessException: lateinit property stripeSdk has not been initialized
E/MethodChannel#flutter/platform_views(14280): 	at com.flutter.stripe.StripeAndroidPlugin.getStripeSdk(StripeAndroidPlugin.kt:28)
E/MethodChannel#flutter/platform_views(14280): 	at com.flutter.stripe.StripeAndroidPlugin$onAttachedToEngine$1.invoke(StripeAndroidPlugin.kt:51)
E/MethodChannel#flutter/platform_views(14280): 	at com.flutter.stripe.StripeAndroidPlugin$onAttachedToEngine$1.invoke(StripeAndroidPlugin.kt:51)

**Comment by jamesblasco** [comment] 2022-01-15 10:34
Could you check if the issue is solved if you add
```await Stripe.instance.applySettings();````
like the example app 

https://github.com/flutter-stripe/flutter_stripe/blob/e6e9a744438b3b9b461bee584c5b47472800a163/example/lib/main.dart#L13

**Comment by aris-1** [comment] 2022-01-17 05:46
jamesblasco, when I add 
`await Stripe.instance.applySettings();`
it gives the following:
### Error report:
I/flutter ( 6730): [2022-01-17 07:41:10.716447 | Catcher | INFO] PlatformException(flutter_stripe initialization failed, The plugin failed to initialize. Are you using FlutterFragmentActivity? Please check the README: https://github.com/flutter-stripe/flutter_stripe#android, null, null)
I/flutter ( 6730): [2022-01-17 07:41:10.716751 | Catcher | INFO] 
I/flutter ( 6730): [2022-01-17 07:41:10.718727 | Catcher | INFO] ------- STACK TRACE -------
I/flutter ( 6730): [2022-01-17 07:41:10.730588 | Catcher | INFO] #0      JSONMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:155:7)
I/flutter ( 6730): [2022-01-17 07:41:10.731187 | Catcher | INFO] #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:167:18)
I/flutter ( 6730): [2022-01-17 07:41:10.731446 | Catcher | INFO] <asynchronous suspension>
I/flutter ( 6730): [2022-01-17 07:41:10.731692 | Catcher | INFO] #2      MethodChannelStripe.initialise (package:stripe_platform_interface/src/method_channel_stripe.dart:43:5)
I/flutter ( 6730): [2022-01-17 07:41:10.731917 | Catcher | INFO] <asynchronous suspension>
I/flutter ( 6730): [2022-01-17 07:41:10.732135 | Catcher | INFO] #3      Stripe._initialise (package:flutter_stripe/src/stripe.dart:417:5)
I/flutter ( 6730): [2022-01-17 07:41:10.732395 | Catcher | INFO] <asynchronous suspension>
I/flutter ( 6730): [2022-01-17 07:41:10.732596 | Catcher | INFO] #4      go.<anonymous closure> (package:xxxx/main.dart:178:7)
I/flutter ( 6730): [2022-01-17 07:41:10.732845 | Catcher | INFO] <asynchronous suspension>

**Comment by jonasbark** [comment] 2022-01-17 07:35
@aris-1 please update flutter_stripe to the latest version (2.1.1) - you should get more details then

**Comment by aris-1** [comment] 2022-01-17 08:05
@jonasbark it's like it is ignoring the MainActivity.kt, where I have put the FlutterFragmentActivity:

MainActivity.kt:
  ```
import io.flutter.embedding.android.FlutterActivity
  import io.flutter.embedding.android.FlutterFragmentActivity 
class MainActivity: FlutterFragmentActivity() { 
}

```
Not sure if this is a problem, in AndroidManifest.xml I have:
```
<application
        android:name="io.flutter.app.FlutterApplication"
```


### Error report:

I/flutter (19890): [2022-01-17 09:43:32.766540 | Catcher | INFO] PlatformException(flutter_stripe initialization failed, The plugin failed to initialize:
I/flutter (19890): Your Main Activity class io.flutter.embedding.android.FlutterActivity is not a subclass FlutterFragmentActivity.
I/flutter (19890): Please check the README: https://github.com/flutter-stripe/flutter_stripe#android, null, null)
I/flutter (19890): [2022-01-17 09:43:32.767036 | Catcher | INFO] 
I/flutter (19890): [2022-01-17 09:43:32.770115 | Catcher | INFO] ------- STACK TRACE -------
I/flutter (19890): [2022-01-17 09:43:32.775207 | Catcher | INFO] #0      JSONMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:155:7)
I/flutter (19890): [2022-01-17 09:43:32.775975 | Catcher | INFO] #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:167:18)
I/flutter (19890): [2022-01-17 09:43:32.776500 | Catcher | INFO] <asynchronous suspension>
I/flutter (19890): [2022-01-17 09:43:32.777118 | Catcher | INFO] #2      MethodChannelStripe.initialise (package:stripe_platform_interface/src/method_channel_stripe.dart:43:5)
I/flutter (19890): [2022-01-17 09:43:32.777504 | Catcher | INFO] <asynchronous suspension>
I/flutter (19890): [2022-01-17 09:43:32.778044 | Catcher | INFO] #3      Stripe._initialise (package:flutter_stripe/src/stripe.dart:417:5)
I/flutter (19890): [2022-01-17 09:43:32.778313 | Catcher | INFO] <asynchronous suspension>
I/flutter (19890): [2022-01-17 09:43:32.778809 | Catcher | INFO] #4      go.<anonymous closure> (package:xxx/main.dart:178:7)
I/flutter (19890): [2022-01-17 09:43:32.779124 | Catcher | INFO] <asynchronous suspension>

**Comment by jonasbark** [comment] 2022-01-17 08:06
Yes indeed, the value in your android manifest is wrong. Change it to your main activity or to flutter fragment activity.

**Comment by aris-1** [comment] 2022-01-17 08:16
@jonasbark, I changed the AndroidManifest.xml to point to ".MainActivity" and I get fatal error. 
 ```
  <application
         android:name=".MainActivity"
```

### Error report:
E/AndroidRuntime(24848): FATAL EXCEPTION: main
E/AndroidRuntime(24848): Process: com.xxx.xxx, PID: 24848
E/AndroidRuntime(24848): java.lang.RuntimeException: Unable to instantiate application com.xxx.xxx.MainActivity: java.lang.ClassNotFoundException: Didn't find class "com.xxx.xxx.MainActivity" on path: DexPathList[[zip file "/data/app/com.xxx.xxx-2/base.apk"],nativeLibraryDirectories=[/data/app/com.xxx.xxx-2/lib/arm64, /data/app/com.xxx.xxx-2/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
E/AndroidRuntime(24848): 	at android.app.LoadedApk.makeApplication(LoadedApk.java:811)
E/AndroidRuntime(24848): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5504)
E/AndroidRuntime(24848): 	at android.app.ActivityThread.-wrap2(ActivityThread.java)
E/AndroidRuntime(24848): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1611)
E/AndroidRuntime(24848): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(24848): 	at android.os.Looper.loop(Looper.java:165)
E/AndroidRuntime(24848): 	at android.app.ActivityThread.main(ActivityThread.java:6375)
E/AndroidRuntime(24848): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(24848): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
E/AndroidRuntime(24848): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802)

**Comment by jonasbark** [comment] 2022-01-17 08:20
include the java package name where you placed your MainActivity in - '.MainActivity' is referring to the wrong one apparently

**Comment by aris-1** [comment] 2022-01-17 10:18
@jonasbark, I believe the  AndroidManifest.xml should be something like bellow (removed the android:name="io.flutter.app.FlutterApplication" and the <activity android:name="io.flutter.embedding.android.FlutterActivity")

```
 <application
    <activity
            android:name=".MainActivity"
```
but it produces the above mentioned error and I can't find how to fix. Let's say the package name is "com.domain.app". I tried adding it in the name, but still it doesn't find it.

```
 <application
    <activity
            android:name="com.domain.app.MainActivity"
```

MainActivity.tk path: android/app/src/main/kotlin/com/domain/app/MainActivity.kt

### Error report:
E/AndroidRuntime(19532): java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.domain.app/com.domain.app.MainActivity}: java.lang.ClassNotFoundException: Didn't find class "com.domain.app.MainActivity" on path: DexPathList[[zip file "/data/app/com.domain.app-2/base.apk"],nativeLibraryDirectories=[/data/app/com.domain.app-2/lib/arm64, /data/app/com.domain.app-2/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
E

**Comment by aris-1** [comment] 2022-01-26 16:18
Can someone please help? Although I have given a response the issue since 9 days still has the label "Awaiting response"

**Comment by jonasbark** [comment] 2022-01-26 16:43
I think your question would be better suited on Stackoverflow. To me, it looks like a wrong configuration that is related to Android and not related to this plugin.
Maybe the Kotlin plugin isn't activate on the Android part, thus you're getting the ClassNotFoundException?

**Comment by remonh87** [comment] 2022-02-12 15:30
We created a trouble shooting page that hopefully will help. https://docs.page/flutter-stripe/flutter_stripe/troubleshooting 

Closing it for now

**Closed by remonh87** 2022-02-12 15:30 UTC
Labels: Awaiting response
