### ISSUE TITLE
Flutter stable 3.7.1 android error

### ISSUE THREAD

**Issue by arnair** [flutter-stripe/flutter_stripe#1106] opened 2023-02-03 07:18 UTC
**Describe the bug**
`e: /Users/arnau/.pub-cache/hosted/pub.dev/stripe_android-8.0.0/android/src/main/kotlin/com/flutter/stripe/StripeSdkCardFormPlatformView.kt: (54, 34): Unresolved reference: getIntOrNull
e: /Users/arnau/.pub-cache/hosted/pub.dev/stripe_android-8.0.0/android/src/main/kotlin/com/flutter/stripe/StripeSdkCardFormPlatformView.kt: (55, 35): Unresolved reference: getIntOrNull
e: /Users/arnau/.pub-cache/hosted/pub.dev/stripe_android-8.0.0/android/src/main/kotlin/com/flutter/stripe/StripeSdkCardFormPlatformView.kt: (56, 23): Unresolved reference: getValOr
e: /Users/arnau/.pub-cache/hosted/pub.dev/stripe_android-8.0.0/android/src/main/kotlin/com/flutter/stripe/StripeSdkCardFormPlatformView.kt: (58, 72): Unresolved reference: it
e: /Users/arnau/.pub-cache/hosted/pub.dev/stripe_android-8.0.0/android/src/main/kotlin/com/flutter/stripe/StripeSdkCardFormPlatformView.kt: (64, 65): Unresolved reference: it
e: /Users/arnau/.pub-cache/hosted/pub.dev/stripe_android-8.0.0/android/src/main/kotlin/com/flutter/stripe/StripeSdkCardPlatformView.kt: (57, 26): Unresolved reference: getValOr
e: /Users/arnau/.pub-cache/hosted/pub.dev/stripe_android-8.0.0/android/src/main/kotlin/com/flutter/stripe/StripeSdkCardPlatformView.kt: (58, 34): Unresolved reference: getIntOrNull
e: /Users/arnau/.pub-cache/hosted/pub.dev/stripe_android-8.0.0/android/src/main/kotlin/com/flutter/stripe/StripeSdkCardPlatformView.kt: (59, 35): Unresolved reference: getIntOrNull
e: /Users/arnau/.pub-cache/hosted/pub.dev/stripe_android-8.0.0/android/src/main/kotlin/com/flutter/stripe/StripeSdkCardPlatformView.kt: (60, 23): Unresolved reference: getValOr
e: /Users/arnau/.pub-cache/hosted/pub.dev/stripe_android-8.0.0/android/src/main/kotlin/com/flutter/stripe/StripeSdkCardPlatformView.kt: (62, 52): Unresolved reference: it
e: /Users/arnau/.pub-cache/hosted/pub.dev/stripe_android-8.0.0/android/src/main/kotlin/com/flutter/stripe/StripeSdkCardPlatformView.kt: (73, 45): Unresolved reference: it
e: /Users/arnau/.pub-cache/hosted/pub.dev/stripe_android-8.0.0/android/src/main/kotlin/com/reactnativestripesdk/CardFieldViewManager.kt: (84, 18): Unresolved reference: getValOr
e: /Users/arnau/.pub-cache/hosted/pub.dev/stripe_android-8.0.0/android/src/main/kotlin/com/reactnativestripesdk/CardFieldViewManager.kt: (85, 26): Unresolved reference: getIntOrNull
e: /Users/arnau/.pub-cache/hosted/pub.dev/stripe_android-8.0.0/android/src/main/kotlin/com/reactnativestripesdk/CardFieldViewManager.kt: (86, 27): Unresolved reference: getIntOrNull
e: /Users/arnau/.pub-cache/hosted/pub.dev/stripe_android-8.0.0/android/src/main/kotlin/com/reactnativestripesdk/CardFieldViewManager.kt: (87, 15): Unresolved reference: getValOr

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':stripe_android:compileDebugKotlin'.`
**To Reproduce**
1. Install flutter_stripe: ^8.0.0+1 using Flutter stable 3.7.1 
2. Follow installation instruction for android

**Expected behavior**
Compile app

**Smartphone / tablet**
Android simulator Pixel 5 API32
flutter_stripe: ^8.0.0+1
Flutter (Channel stable, 3.7.1, on macOS 12.6.3 21G419 darwin-arm64,

**Additional context**
On the IOS simulator works

**Comment by remonh87** [comment] 2023-02-03 08:11
duplicate of #1103

**Closed by remonh87** 2023-02-03 08:11 UTC
Labels: needs triage
