### ISSUE TITLE
8.0.0 resource drawable/googlepay_button_content not found.

### ISSUE THREAD

**Issue by rasmusGrift** [flutter-stripe/flutter_stripe#1150] opened 2023-03-07 22:13 UTC
**Describe the bug**
When building my app with 8.0.0 or 8.0.0+1 it crashes and gives this error:
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask$TaskAction
   > Android resource linking failed
     ERROR:$APPDIRECTORY\build\stripe_android\intermediates\packaged_res\debug\layout\plain_googlepay_button.xml:10: AAPT: error: resource drawable/googlepay_button_content (aka ...:drawable/googlepay_button_content) not found.
```
Changing the version in pubspec.yaml to 7.0.0, everything works.

I indeed do not see googlepay_button_content in any of the drawable directories

**To Reproduce**
1. add flutter_stripe: ^8.0.0 to pubspec.yaml
2. run the app on device
3. Observe the failure with exception

**Expected behavior**
correctly build application just as with the 7.0.0 version.

**Smartphone / tablet**
 - Device: OnePlus 7t Pro
 - OS: Android 11
 - Package version: ^8.0.0 and ^8.0.0+1
 - Flutter version:
```
 Flutter 3.7.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 12cb4eb7a0 (6 days ago) • 2023-03-01 10:29:26 -0800
Engine • revision ada363ee93
Tools • Dart 2.19.3 • DevTools 2.20.1
```

**Additional context**
flutter doctor -v:
```
[√] Flutter (Channel stable, 3.7.6, on Microsoft Windows [Version 10.0.19045.2604], locale en-150)
    • Flutter version 3.7.6 on channel stable at ...
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 12cb4eb7a0 (6 days ago), 2023-03-01 10:29:26 -0800
    • Engine revision ada363ee93
    • Dart version 2.19.3
    • DevTools version 2.20.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at ...\AppData\Local\Android\sdk
    • Platform android-33, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.76.0)
    • VS Code at ...\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.60.0

[√] Connected device (2 available)
    • HD1913 (mobile)   • e3432b15 • android-arm64 • Android 11 (API 30)
    • Windows (desktop) • windows  • windows-x64   • Microsoft Windows [Version 10.0.19045.2604]

[√] HTTP Host Availability
    • All required HTTP hosts are available
```

**Comment by michaelsoliman1** [comment] 2023-03-08 10:35
Same Issue happening after upgrading to 8.0.0

**Comment by jonasbark** [comment] 2023-03-08 11:29
Try a `flutter clean` and ensure that the stripe_android version in your pubspec.lock is at least 8.0.0.

**Comment by rasmusGrift** [comment] 2023-03-08 20:26
> Try a `flutter clean` and ensure that the stripe_android version in your pubspec.lock is at least 8.0.0.

Tried flutter clean and checked if pubspec.lock stripe_android, 8.0.0
even went as far to delete the whole pubspec.lock file and regenerate it.

Both instances it resulted in the same error.

pubspec.lock:
```
stripe_android:
    dependency: transitive
    description:
      name: stripe_android
      sha256: "3cf43dfb70d8011ded0730c091e741b94cd4aaccaad22732a19f5941503072d6"
      url: "https://pub.dev"
    source: hosted
    version: "8.0.0+1"
```

**Comment by jonasbark** [comment] 2023-03-10 08:15
Fixed in 8.0.0+1

**Comment by jonasbark** [comment] 2023-03-10 08:23
I created a new project, added `flutter_stripe: 9.0.0+1` as a dependency, and the compilation worked fine. It must be on your side, e.g. dependency cache or similar.

I'm closing this accordingly. If you can provide a reproducible example project then I can take another look.

**Closed by jonasbark** 2023-03-10 08:23 UTC
Labels: needs triage

**Comment by rasmusGrift** [comment] 2023-03-23 00:50
Got it working,

I had a constraint in my dependencies in the app/build.gradle . Not sure why, probably because of an old problem.

My solution was to delete:
`constraints { implementation('com.stripe:stripe-android') { version { strictly '20.11.0' } } } `

**Comment by TinyGiantDigital** [comment] 2023-05-26 11:35
I had this hardcoded because of: https://github.com/flutter-stripe/flutter_stripe/issues/1000

Removing now sorts it
