### ISSUE TITLE
No billing address showing up in stripe charge

### ISSUE THREAD

**Issue by eliezerp3** [flutter-stripe/flutter_stripe#482] opened 2021-12-12 22:28 UTC
Added billing address to initPaymentSheet but although the charge is going through without a problem; the billing address is not showing up in the stripe charge.

```

Future<void> checkout() async {
    final billingDetails = BillingDetails(
      email: 'email@stripe.com',
      phone: '+48888000888',
      address: Address(
        city: 'Houston',
        country: 'US',
        line1: '1459  Circle Drive',
        line2: '',
        state: 'Texas',
        postalCode: '77063',
      ),
    );
    try {
      /// retrieve data from the backend
      final _paymentSheetData = await API.createPaymentIntent();
      print(_paymentSheetData.data);
      await Stripe.instance.initPaymentSheet(
          paymentSheetParameters: SetupPaymentSheetParameters(
        // applePay: true,
        // googlePay: true,
        style: ThemeMode.dark,
        testEnv: true,
        merchantCountryCode: 'US',
        merchantDisplayName: 'Flutter Stripe Store Demo',
        customerId: _paymentSheetData.data['customer_id'],
        paymentIntentClientSecret: _paymentSheetData.data['client_secret'],
        customerEphemeralKeySecret: _paymentSheetData.data['ephemeral_key'],
        billingDetails: billingDetails,
      ));
      
      await Stripe.instance.presentPaymentSheet();
    } catch (e) {
      if (e is StripeException)
        ScaffoldMessenger.of(context).showSnackBar(SnackBar(
            content: Text(
          e.error.localizedMessage ??
              'There was an error proccesing your payment',
          textAlign: TextAlign.center,
        )));
      else
        ScaffoldMessenger.of(context).showSnackBar(SnackBar(
            content: Text(
          e.toString(),
          textAlign: TextAlign.center,
        )));
    }
  }

```

**Comment by jonasbark** [comment] 2021-12-13 16:44
I think this is a duplicate of https://github.com/flutter-stripe/flutter_stripe/issues/185 - feel free to reply again if you mean something different

**Closed by jonasbark** 2021-12-13 16:44 UTC
Labels: needs triage

**Comment by eliezerp3** [comment] 2021-12-13 18:02
@jonasbark Any update on that thread?
