### ISSUE TITLE
PlatformException(flutter_stripe initialization failed, The plugin failed to initialize. Are you using FlutterFragmentActivity?

### ISSUE THREAD

**Issue by xlcod** [flutter-stripe/flutter_stripe#238] opened 2021-07-27 08:50 UTC
**Describe the bug**
PlatformException(flutter_stripe initialization failed, The plugin failed to initialize. Are you using FlutterFragmentActivity?

**To Reproduce**
i followed the guide, the following changes were made as stated in requirements, i also checked for  other 
 issues like mine, the solutions provided doesn´t work for me . 

1-Gradle wrapper  :  distributionUrl=https\://services.gradle.org/distributions/gradle-6.7.1-all.zip
2-MainActivity.kt : `
                                import io.flutter.embedding.android.FlutterActivity
                                 import io.flutter.embedding.android.FlutterFragmentActivity
                                class MainActivity: FlutterFragmentActivity() {
                                }
`

3-build.gradle :
```
 buildscript {
    ext.kotlin_version = "1.5.0"
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.google.gms:google-services:4.3.3'
        classpath 'com.android.tools.build:gradle:4.1.2'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}
```

4-manifest-xml : 
```<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.com.com">
    <application
        android:name=".MainActivity" `**_here if i write this app doesn´t launch , stuck forever on installing._**`
        android:label="xxxxxxxxx"
        android:icon="@mipmap/ic_launcher"
        android:requestLegacyExternalStorage="true"
        android:usesCleartextTraffic="true"
        >

        <!-- Establece el icono que se mostrará en la notificación en android estando la app en segundo plano o cerrada -->
        <meta-data
          android:name="com.google.firebase.messaging.default_notification_icon"
          android:resource="@drawable/a_blanco_verde"
          />
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:showWhenLocked="true"
            android:turnScreenOn="true"
            android:windowSoftInputMode="adjustResize">
```

**Smartphone / tablet**
 - Device: Android emulator
 - OS:  Android 10
 - Package version: latest
 - Flutter version 2.2.3

**Comment by jonasbark** [comment] 2021-07-27 08:53
Dupe of https://github.com/flutter-stripe/flutter_stripe/issues/166
Double-check the java package ("com.com.com") looks weird.

**Closed by jonasbark** 2021-07-27 08:53 UTC

**Comment by xlcod** [comment] 2021-07-27 08:54
@jonasbark i write that to not show my package name........

**Comment by xlcod** [comment] 2021-07-27 08:56
@jonasbark  Please do not close issue immediately after giving useless help to your own plugin

**Comment by xlcod** [comment] 2021-07-27 08:59
@jonasbark i know its duplicated , as i already said , the solutions provided in that issue doesn´t solve anything in my case.

**Comment by jonasbark** [comment] 2021-07-27 08:59
It's a duplicate, so I'm closing it. Thanks for calling it useless - as open-source maintainers spending our own time on it we're always happy to help you ;)

**Comment by xlcod** [comment] 2021-07-27 09:02
> It's a duplicate, so I'm closing it. Thanks for calling it useless - as open-source maintainers spending our own time on it we're always happy to help you ;)

at least you can give more useful help to people that use your plugin , i know its an open source plugin and i appreciate your work(really) but that doesn´t hide that the fact that closing an issue doesn´t solve anything.

**Comment by jonasbark** [comment] 2021-07-27 09:14
Neither does opening a new ticket for something that is neither a bug nor a feature request - rather continue on the original one.

**Comment by xlcod** [comment] 2021-07-27 09:43
i already comented on that issue aswell.

**Comment by remonh87** [comment] 2021-07-27 10:03
Your manifest application name is `  android:name=".MainActivity"`  . this is not allowed.  Check also the android logs since this will provide you some useful  info. I agree with @jonasbark  that this is not related to the plugin. I really would check our example app https://github.com/flutter-stripe/flutter_stripe/blob/main/example/android/app/src/main/AndroidManifest.xml .

**Comment by xlcod** [comment] 2021-07-27 10:10
@remonh87 in the example it shows  android:name=".MainActivity" as i have in mine , it needs to be different or i´m understanding it wrongly? 

```<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.myfakepackage.name">
    <!-- io.flutter.app.FlutterApplication is an android.app.Application that
         calls FlutterMain.startInitialization(this); in its onCreate method.
         In most cases you can leave this as-is, but you if you want to provide
         additional functionality it is fine to subclass or reimplement
         FlutterApplication and put your custom class here. -->
    <application
        android:name="io.flutter.app.FlutterApplication"  /////In this line  i tried with  ".MainActivity" also
        android:label="(my app name)"
        android:icon="@mipmap/ic_launcher"
        android:requestLegacyExternalStorage="true"
        android:usesCleartextTraffic="true"
        >

        
        <meta-data
          android:name="com.google.firebase.messaging.default_notification_icon"
          android:resource="@drawable/a_blanco_verde"
          />
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:showWhenLocked="true"
            android:turnScreenOn="true"
            android:windowSoftInputMode="adjustResize">
            
            <meta-data
              android:name="io.flutter.embedding.android.NormalTheme"
              android:resource="@style/NormalTheme"
              />
           
            <meta-data
              android:name="io.flutter.embedding.android.SplashScreenDrawable"
              android:resource="@drawable/launch_background"
              />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
            
            <intent-filter>
              <action android:name="FLUTTER_NOTIFICATION_CLICK" />
              <category android:name="android.intent.category.DEFAULT" />
            </intent-filter>

        </activity>
        <!-- Don't delete the meta-data below.
             This is used by the Flutter tool to generate GeneratedPluginRegistrant.java -->
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
    </application>
</manifest>```
