### ISSUE TITLE
Strange disappearing payment sheet

### ISSUE THREAD

**Issue by KevinSinSH** [flutter-stripe/flutter_stripe#1988] opened 2024-11-07 06:01 UTC
**Describe the bug**
Quote from apple: "When we tapped on the Apple Pay button, the app refreshes, and goes back to the same page (shown in the screenshot)." from apple

Video from Apple:
https://github.com/user-attachments/assets/05b5899e-f0aa-4261-bdab-0e3ee35f8f02

**To Reproduce**
We are unable to reproduce the stated issue indicated in apple (ios18, iPhone 13 and iPad Gen10th).
But here is what we have done
1. Publish the app normally, now apple pay is working fine
2. remove the app from apple store
3. use another apple developer account
4. use a new app bundle id for the app in Apple's developer portal,
5. created a new merchant id in Apple's developer portal, 
6. Delete the old apple cert in Stripe (we directly delete without switching off apple pay)
7. Doing cert sign request in Stripe using the new merchant id 
8. Replace app's bundle Id and apple pay merchant id in xcode
9. Build the app 

**Expected behavior**
No refresh behavior

**Smartphone / tablet**
 - Device: multiple
 - OS: [e.g. iOS 18]
 - Package version: [e.g. 11.2.0]
 - Flutter version [e.g.  3.24.1]

**Additional context**
working fine in simulator ios18 (iPhone 13 and iPad Gen10th).
working fine in simulator ios 17.2 for at least 2 iPhone and 2 iPad
working fine in real iPhone 8 of ios 16.7.10
with the same code, android version app is working correctly
After step 9, We also tried flipping "enable/disable" Apple pay in Stripe portal's payment method, but no use.
I use IntelliJ, My MacMini OS, x-code is up-to-date (last checked on this issue's creating day)
As we can publish apps, the problem occur only when I change the developer account.
This is not transfer of app.

Please help, thanks

**Comment by remonh87** [comment] 2024-11-13 07:24
there must be some device logs there that can provide context what is going on there .  Can you share these. We cannot reproduce this based on the provide steps

**Comment by KevinSinSH** [comment] 2024-11-13 07:58
@remonh87 Sorry, we are unable to provide the log as we are unable to reproduce the error as well. The problem only encounter by Apple's review team. That issue happen on early October, we published a version without apple pay. After the approval, we try re-enabling it in the next version by redoing again the step5-9, and it got approved.

**Comment by remonh87** [comment] 2024-11-15 07:42
ok I will close it for now then feel free to reopen it when the issue occurs

**Closed by remonh87** 2024-11-15 07:42 UTC
Labels: Awaiting response, needs triage
