### ISSUE TITLE
Problem with ING bank when trying to create a payment intent at the 3D secure step

### ISSUE THREAD

**Issue by Nicolas-Sugranes** [flutter-stripe/flutter_stripe#629] opened 2022-03-11 15:15 UTC
**Describe the bug**
When we are creating a payment intent with the 3D secure system activated, it always works (on Android and iOS) except for one bank called ING. For this bank, the 3D secure page does not display and the process returns an error log.

**To Reproduce**
1. Entering card numbers from ING bank.
2. Start a create payment intent process with 3d secure verification.
3. Observe that the 3D secure does not display and see the error logs as below

**Expected behavior**
We expected to see the 3D secure validation page and to have a payment intent created as a return value.

**Smartphone / tablet**
 - Device: [iPhone 8.4, oneplus 6]
 - OS: [iOS 13.4.1, Android 10]
 - Package version: [2.10.3]
 - Flutter version [2.3.0]

**Additional context**
With the ING bank the user receives a code from them and he must enter this code in the 3D Secure page to continue the process (the UI part to enter the code is the part which is not working) whereas with the other banks, the user only needs to validate the action in the bank app (and it works).

The problem is probably from the 3D secure page which is not the same when you need to send an additional validation code.

Failure logs we get :

LOG ANALYTICS: ["apple_pay_enabled": 0, "app_name": "our_app", "product_usage": ["STPPaymentCardTextField"], "publishable_key": "...", "required_billing_address_fields": "zip", "required_shipping_address_fields": "none", "pay_var": "legacy", "device_type": "iPhone8,4", "plugin_type": "flutter", "additional_payment_methods": "none", "install": "C", "additional_info": [], "app_version": "1.0.0", "event": "stripeios.3ds2_authenticate", "intent_id": "the_intent_id", "os_version": "13.4.1", "shipping_type": "shipping", "ocr_type": "none", "ui_usage_level": "card_text_field", "bindings_version": "21.12.0", "analytics_ua": "analytics.stripeios-1.0", "company_name": "our_app", "apple_merchant_identifier": "unknown"]

**Comment by remonh87** [comment] 2022-03-12 15:55
It looks like this is related to the following issue in the Stripe SDK: https://github.com/stripe/stripe-react-native/issues/733

**Comment by remonh87** [comment] 2022-03-13 10:24
duplicate of #431

**Closed by remonh87** 2022-03-13 10:24 UTC
Labels: bug, blocked
