### ISSUE TITLE
Billing details are not showing in stripe payment.

### ISSUE THREAD

**Issue by Seddik-Boukhalfa** [flutter-stripe/flutter_stripe#438] opened 2021-11-09 18:18 UTC
At first, thanks for all the hard work you are doing guys.

Before the new update 2.0.2, i used the CardField in favor of the Payment sheet just to use the billing details which was not provided in the payment sheet. after the 2.0.2 update, i wanted to switch back to the payment sheet but my problem is the billing details are not showing in the stripe account payments billing details. After adding it as a parameter in paymentSheetParameters, it doesn't seem to work, even though it works perfectly fine when using Cardfield, and i'm assuming it's overridden by the the presented payment sheet selected country as the only payment billing details available is the country code.

The problem for me can be produced just by using the provided example in the package.

As i supposed if the billing details is provided, there will be no need to display and choose the country. 

 - Device: emulator iPhone 12 Pro Max
 - OS: iOS 14.4
 - Package version: 2.0.2
 - Flutter version : 2.5.3

**Comment by jonasbark** [comment] 2021-11-09 20:04
Hi - thanks for reporting!
I think this is a dupe of https://github.com/flutter-stripe/flutter_stripe/issues/185

**Comment by Seddik-Boukhalfa** [comment] 2021-11-11 15:33
I don't think this is the case here, at least not the one mentioned in #185, the problem with the billing details is that none of the provided information such as email nor the name etc is displayed in the stripe payment details while using the cardfield, those same information are displayed correctly. I'm not entirely sure what's the cause of this issue so far. i'll be glad if you look into it.

**Comment by remonh87** [comment] 2021-11-30 17:32
@Seddik-Boukhalfa  I did some tests and it is indeed related to the issue mentioned. Closing it

**Closed by remonh87** 2021-11-30 17:32 UTC
