### ISSUE TITLE
"Unhandled Exception: type 'String' is not a subtype of type 'int' in type cast" when trying to create a card token on iOS

### ISSUE THREAD

**Issue by LordpeaceDev** [flutter-stripe/flutter_stripe#1247] opened 2023-05-19 19:34 UTC
**Describe the bug**
An error is raised when trying to create a card token on ios.

```
final paymentMethod = await Stripe.instance.createToken(
        CreateTokenParams.card(
          params: CardTokenParams(
            type: TokenType.Card,
            address: Address(
              country: "US",
              line1: "Somewhere",
              city: '',
              line2: '',
              state: '',
              postalCode: "123250",
            ),
            currency: user.pays.symboleMonnaie,
          ),
        ),
      );
```

```
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: type 'String' is not a subtype of type 'int' in type cast
#0      _$$_TokenDataFromJson (package:stripe_platform_interface/src/models/create_token_data.g.dart:146:32)
#1      new _$_TokenData.fromJson (package:stripe_platform_interface/src/models/create_token_data.freezed.dart:1778:7)
#2      _$TokenDataFromJson (package:stripe_platform_interface/src/models/create_token_data.freezed.dart:1577:21)
#3      new TokenData.fromJson (package:stripe_platform_interface/src/models/create_token_data.dart:146:7)
#4      MethodChannelStripe.createToken.<anonymous closure> (package:stripe_platform_interface/src/method_channel_stripe.dart:287:44)
#5      ResultParser.parse (package:stripe_platform_interface/src/result_parser.dart:14:24)
#6      MethodChannelStripe.createToken (package:stripe_platform_interface/src/method_channel_stripe.dart:288:10)
<asynchronous suspension>
#7      Stripe.createToken (package:flutter_stripe/src/stripe.dart:314:25)
<asynch<…>
```

**To Reproduce**
Flutter 3.10.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 84a1e904f4 (10 days ago) • 2023-05-09 07:41:44 -0700
Engine • revision d44b5a94c9
Tools • Dart 3.0.0 • DevTools 2.23.1

`flutter doctor -v`

```
[✓] Flutter (Channel stable, 3.10.0, on macOS 13.2.1 22D68 darwin-arm64 (Rosetta), locale en-US)
    • Flutter version 3.10.0 on channel stable at /Users/user239313/Downloads/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 84a1e904f4 (10 days ago), 2023-05-09 07:41:44 -0700
    • Engine revision d44b5a94c9
    • Dart version 3.0.0
    • DevTools version 2.23.1

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.77.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.64.0

[✓] Connected device (3 available)
    • iPhone 14 Pro (mobile) • F715B685-0C55-43EF-A648-A7F6719610EC • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 13.2.1 22D68 darwin-arm64 (Rosetta)
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 112.0.5615.49

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
**Smartphone / tablet**

  Device: [iPhone 14 Pro (mobile) com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)]
  OS: [iOS 16-4]
  Package version: [9.2.0]
  Flutter version [3.10.0]

**Expected behavior**
Expect a TokenData object to be returned.

**Comment by haritest101** [comment] 2023-05-23 09:18
even i got the same issue, any soon fixes most appreciated.

**Comment by remonh87** [comment] 2023-05-23 18:56
Duplicate of #1112  . Will be fixed in next sync

**Closed by remonh87** 2023-05-23 18:56 UTC
Labels: needs triage
