### ISSUE TITLE
Apple Pay 

### ISSUE THREAD

**Issue by hateshkumar** [flutter-stripe/flutter_stripe#1300] opened 2023-07-05 14:26 UTC
# Apple Pay

### Steps:

1. Charging payment from apple pay successfully.
2. Creating payment intent.
3. Creating token.
4. Creating payment method.
5. Confirming payment. 

I am having issues with step 3 despite the paymentResult containing correct data.

<img width="898" alt="image" src="https://github.com/flutter-stripe/flutter_stripe/assets/18635520/91957eac-8601-4ff3-86dc-33635526221d">
    
    

This code is supposed to return the token when the payment is made from Apple Pay but I am getting an error with this message:

There was an unexpected error -- try again in a few seconds.

**Comment by hateshkumar** [comment] 2023-07-07 12:38
@remonh87 could you please response on this

**Comment by remonh87** [comment] 2023-07-12 07:36
duplicate of #1299

**Closed by remonh87** 2023-07-12 07:36 UTC
Labels: needs triage
