### ISSUE TITLE
Manually attach card details to createPaymentMethod

### ISSUE THREAD

**Issue by lbk9** [flutter-stripe/flutter_stripe#111] opened 2021-06-02 13:43 UTC
Using the now discontinued flutter_stripe package, it was simple to manually attach a CreditCard object to the createPaymentMethod call. This doesn't seem possible with this plugin as the card details are somehow automatically passed to the function. For apps with existing UI that cannot be changed, this approach doesn't really seem feasible.

**Comment by jonasbark** [comment] 2021-06-02 13:44
Duplicate of https://github.com/flutter-stripe/flutter_stripe/issues/40

**Closed by jonasbark** 2021-06-02 13:44 UTC
