### ISSUE TITLE
Close on icon on the payment sheet, executes the try block and shows the snackbar, it is suppose to run the error block to handle the error

### ISSUE THREAD

**Issue by kalptech2021** [flutter-stripe/flutter_stripe#189] opened 2021-07-07 15:52 UTC
try{ 

       await Stripe.instance.presentPaymentSheet(parameters: PresentPaymentSheetParameters(

        clientSecret: _paymentIntentData!['paymentIntent'],

        confirmPayment: true,

      )).whenComplete((){
        setState(() {
          _paymentIntentData = null;
        });
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Successful')),
        );
      });

    }catch(e){
      print(e.toString());
    }

**Comment by jonasbark** [comment] 2021-07-07 18:12
Dupe of https://github.com/flutter-stripe/flutter_stripe/issues/184

**Closed by jonasbark** 2021-07-07 18:12 UTC
