### ISSUE TITLE
CardField throws MissingPluginException error on Android.

### ISSUE THREAD

**Issue by awaik** [flutter-stripe/flutter_stripe#276] opened 2021-08-12 10:29 UTC
**Describe the bug**
When I use the code from the plugin example

```
            CardField(
              style: Theme.of(context).textTheme.bodyText1,
              autofocus: true,
              onCardChanged: (card) {
                setState(() {
                  _card = card;
                });
              },
            ),
```

on the iOs it works well, but on the Android it throws an error

```
E/flutter ( 7147): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: MissingPluginException(No implementation found for method onPlaceholderChanged on channel flutter.stripe/card_field/0)
E/flutter ( 7147): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:7)
```

**To Reproduce**
1. Run the sample app on the Android.

**Smartphone / tablet**
 - Device: Samsung Galaxy S7
 - OS: Android 8.0.0
 - Package version: 1.2.0
 - Flutter version Channel stable, 2.0.6

**Comment by jonasbark** [comment] 2021-08-19 09:39
Thanks for reporting - unfortunately, I haven't been able to reproduce this locally.
Can you narrow it down, e.g. by checking if only certain Android OS versions are affected?

**Comment by diegopq** [comment] 2021-08-20 01:06
same error 
My code:
`CardField(
          onCardChanged: (cardField) {
            final data = NewPaymentCard(
              last4: cardField?.last4,
              month: cardField?.expiryMonth.toString(),
              year: cardField?.expiryYear.toString(),
              brand: cardField?.brand,
            );
            context.read<WriteDataCardCubit>().writeData(data);
            if (cardField!.complete) {
              context.read<PaymentMethodsBloc>().add(WriteNewCardData(data));
            } else if (cardField.last4!.isEmpty) {
              context.read<PaymentMethodsBloc>().add(ClearNewCardData());
            }
          },
          decoration: InputDecoration(
            border: OutlineInputBorder(
              borderRadius: BorderRadius.circular(10),
              borderSide: const BorderSide(
                color: Colors.transparent,
              ),
            ),
            filled: true,
            fillColor: theme.colorScheme.onSurface.withOpacity(0.05),
            // hintText: hintText,
            hintStyle: theme.textTheme.headline4!.copyWith(
              color: theme.colorScheme.onSurface.withOpacity(0.2),
              fontWeight: FontWeight.normal,
            ),
            errorText: null,
            errorStyle: const TextStyle(
              height: 0,
            ),
            enabledBorder: OutlineInputBorder(
              borderRadius: BorderRadius.circular(10),
              gapPadding: 1.0,
              borderSide: const BorderSide(
                color: Colors.transparent,
              ),
            ),
            focusedBorder: OutlineInputBorder(
              borderRadius: BorderRadius.circular(10),
              gapPadding: 1.0,
              borderSide: const BorderSide(
                color: Colors.transparent,
              ),
            ),
            alignLabelWithHint: true,
          ),
          style: theme.textTheme.headline4!.copyWith(
            fontWeight: FontWeight.w400,
          ),
          expirationHintText: 'MM/AA',
          cursorColor: theme.textSelectionTheme.cursorColor!,
        ),`

The error:
**E/flutter (20383): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: MissingPluginException(No implementation found for method clearFocus on channel flutter.stripe/card_field/1)
E/flutter (20383): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156)
E/flutter (20383): <asynchronous suspension>**

and the text field is not showing.
The package version is 1.1.0

flutter doctor -v :
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.5 20G71 darwin-x64, locale es-419)
    • Flutter version 2.2.3 at /Users/diegopadillaquijas/fvm/versions/stable
    • Framework revision f4abaa0735 (hace 7 semanas), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/diegopadillaquijas/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.59.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (2 available)
    • Redmi Note 6 Pro (mobile) • 3f3bacff • android-arm64  • Android 9 (API 28)
    • Chrome (web)              • chrome   • web-javascript • Google Chrome 92.0.4515.159

• No issues found!

**Comment by AymericLeFeyer** [comment] 2021-08-21 12:34
Same problem here with minimal code
```
CardField(onCardChanged: (card) {
            print(card);
          }),
```
throws
```
E/flutter ( 5057): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: MissingPluginException(No implementation found for method blur on channel flutter.stripe/card_field/0)
```

**Comment by jamesblasco** [comment] 2021-08-30 07:35
We will push a new version this week that should solve this issue

**Comment by KaMing811** [comment] 2021-09-06 04:04
hi  i have the same problem and it throw this:
E/flutter ( 7738): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: MissingPluginException(No implementation found for method focus on channel flutter.stripe/card_field/1)

**Comment by diegopq** [comment] 2021-09-07 17:00
@jamesblasco the new version does not solve the problem 😖

**Comment by remonh87** [comment] 2021-09-09 05:57
Another user just reported the issue is resolved by upgrading to the latest greatest flutter version. Can you try this out?

**Comment by diegopq** [comment] 2021-09-09 06:09
> Another user just reported the issue is resolved by upgrading to the latest greatest flutter version. Can you try this out?

@remonh87 That problem no longer has it but now what I indicate in this error happens to me #326

**Closed** 2021-09-15 11:06 UTC
Labels: Awaiting response
