### ISSUE TITLE
PaymentSheet stuck on loading

### ISSUE THREAD

**Issue by giandifra** [flutter-stripe/flutter_stripe#93] opened 2021-05-30 13:45 UTC
**Describe the bug**
I tried [payment_sheet_screen](https://github.com/flutter-stripe/flutter_stripe/blob/main/example/lib/screens/payment_sheet_screen.dart) example but the sheet stuck on loading.  
There aren't error on console (only 4 lines with HI text).
Additional console feedback would be helpful.

**Smartphone**
- Pixel 2XL
- Android 11

Thanks

```
// 2. initialize the payment sheet
      await f_stripe.Stripe.instance.initPaymentSheet(
        paymentSheetParameters: f_stripe.SetupPaymentSheetParameters(
          applePay: false,
          googlePay: false,
          style: ThemeMode.dark,
          testEnv: true,
          merchantCountryCode: 'IT',
          merchantDisplayName: 'Flutter Stripe Store Demo',
          customerId: _customer.stripeCustomerId,
          paymentIntentClientSecret: _paymentIntent.stripeClientSecret,
          customerEphemeralKeySecret: _ephemeralKey.secret,
        ),
      );
```

**Comment by jonasbark** [comment] 2021-05-30 15:56
Additional information: https://github.com/stripe/stripe-react-native/issues/281
To me, it happened as well but was caused by the wrong client secret / ephemeral key secret.

**Comment by wilpar** [comment] 2021-07-04 17:46
I also have a problem getting the payment sheet to display.  I've copied the payment_sheet_screen from the example app to start as simply as possible.

_initpaymentsheet works fine - I modified it to get my pub key from firebase, and have moved the _createSheet function from the local express server to firebase functions.  Both of these modifications are replying with the expected results. Stripe logs show:
-  a get request for the customer
- a post request for the ephemeral key
- a post request for the payment intent

But _displayPaymentSheet never completes. There are no errors, so I don't know where to start debugging.  Your assistance is greatly appreciated!

```
import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:flutter_stripe/flutter_stripe.dart';
import 'package:http/http.dart' as http;

import '../../../services/stripe_service.dart';
import '../../../models/order.dart';

class ReservationCheckoutTest extends StatefulWidget {
  final Order order;
  const ReservationCheckoutTest({
    this.order,
    Key key,
  }) : super(key: key);

  @override
  _ReservationCheckoutTestState createState() =>
      _ReservationCheckoutTestState();
}

class _ReservationCheckoutTestState extends State<ReservationCheckoutTest> {
  Map<String, dynamic> _paymentSheetData;
  final StripeService _stripeService = StripeService();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            OutlinedButton(
              onPressed: _paymentSheetData != null ? null : _initPaymentSheet,
              child: const Text('Init payment sheet'),
            ),
            const SizedBox(height: 24),
            OutlinedButton(
              onPressed:
                  _paymentSheetData != null ? _displayPaymentSheet : null,
              child: const Text('Show payment sheet'),
            ),
          ],
        ),
      ),
    );
  }

  Future<void> _initPaymentSheet() async {
    try {
      // 1. create payment intent on the server
      _paymentSheetData = await _createTestPaymentSheet();

      if (_paymentSheetData['error'] != null) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Error code: ${_paymentSheetData['error']}'),
          ),
        );
        print(_paymentSheetData['error']);
        return;
      }

      // 2. get the pubkey
      Stripe.publishableKey = await _stripeService.getPubKey('ca');

      // 3. initialize the payment sheet
      await Stripe.instance.initPaymentSheet(
        paymentSheetParameters: SetupPaymentSheetParameters(
          applePay: true,
          googlePay: true,
          style: ThemeMode.dark,
          testEnv: true,
          merchantCountryCode: 'CA',
          merchantDisplayName: 'Flutter Stripe Store Demo',
          customerId: _paymentSheetData['customer'],
          paymentIntentClientSecret: _paymentSheetData['paymentIntent'],
          customerEphemeralKeySecret: _paymentSheetData['ephemeralKey'],
        ),
      );
      setState(() {});
    } catch (e) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text('Error: $e')),
      );
    }
  }

  Future<Map<String, dynamic>> _createTestPaymentSheet() async {
    final String baseUrl =
        "https://xxxx.cloudfunctions.net/";
    final url = Uri.parse('$baseUrl/stripe-payment_sheet');
    final response = await http.post(
      url,
      headers: {
        'Content-Type': 'application/json',
      },
      body: json.encode({
        'a': 'a',
      }),
    );
    return json.decode(response.body);
  }

  Future<void> _displayPaymentSheet() async {
    print('display sheet');
    try {
      // 4. display the payment sheet.
      await Stripe.instance.presentPaymentSheet(
          parameters: PresentPaymentSheetParameters(
        clientSecret: _paymentSheetData['paymentIntent'],
        confirmPayment: true,
      ));

      setState(() {
        _paymentSheetData = null;
      });

      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text('Payment succesfully completed'),
        ),
      );
    } catch (e) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text('$e'),
        ),
      );
    }
  }
}
```

**Comment by remonh87** [comment] 2021-07-07 18:14
@jonasbark  @giandifra  can you check if the issue still occurs with 1.1.0?

**Comment by remonh87** [comment] 2021-07-11 12:05
Close this issue for now since I cannot reproduce it on `main` branch. Besides this we integrated better error handling in the payment sheet and now provide a result object In case something is wrong it will provide you with a meaningful message. Feel free to reopen with additional info (logcat logs) in case it still doesn't work

**Closed by remonh87** 2021-07-11 12:05 UTC
