### ISSUE TITLE
Unable to instantiate fragment com.reactnativestripesdk.PaymentLauncherFragment: could not find Fragment constructor

### ISSUE THREAD

**Issue by hczmail** [flutter-stripe/flutter_stripe#2009] opened 2024-12-10 02:19 UTC
**Describe the bug**
Google Play crash error

**Expected behavior**
Exception java.lang.RuntimeException:
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:4164)
  at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:4322)
  at android.app.servertransaction.LaunchActivityItem.execute (LaunchActivityItem.java:103)
  at android.app.servertransaction.TransactionExecutor.executeCallbacks (TransactionExecutor.java:139)
  at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:96)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2685)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loopOnce (Looper.java:230)
  at android.os.Looper.loop (Looper.java:319)
  at android.app.ActivityThread.main (ActivityThread.java:8919)
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:578)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1103)
Caused by androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment com.reactnativestripesdk.PaymentLauncherFragment: could not find Fragment constructor
  at androidx.fragment.app.Fragment.instantiate (Fragment.java:688)
  at androidx.fragment.app.FragmentContainer.instantiate (FragmentContainer.java:57)
  at androidx.fragment.app.FragmentManager$3.instantiate (FragmentManager.java:621)
  at androidx.fragment.app.FragmentState.instantiate (FragmentState.java:84)
  at androidx.fragment.app.FragmentStateManager.<init> (FragmentStateManager.java:92)
  at androidx.fragment.app.FragmentManager.restoreSaveStateInternal (FragmentManager.java:2728)
  at androidx.fragment.app.FragmentManager.attachController (FragmentManager.java:2887)
  at androidx.fragment.app.FragmentController.attachHost (FragmentController.java:117)
  at androidx.fragment.app.FragmentActivity.lambda$init$3 (FragmentActivity.java:139)
  at androidx.activity.contextaware.ContextAwareHelper.dispatchOnContextAvailable (ContextAwareHelper.kt:84)
  at androidx.activity.ComponentActivity.onCreate (ComponentActivity.java:358)
  at androidx.fragment.app.FragmentActivity.onCreate (FragmentActivity.java:216)
  at io.flutter.embedding.android.FlutterFragmentActivity.onCreate (FlutterFragmentActivity.java:380)
  at com.callie.app.MainActivity.onCreate (MainActivity.kt:21)
  at android.app.Activity.performCreate (Activity.java:8975)
  at android.app.Activity.performCreate (Activity.java:8944)
  at android.app.Instrumentation.callActivityOnCreate (Instrumentation.java:1456)
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:4146)
Caused by java.lang.NoSuchMethodException: com.reactnativestripesdk.PaymentLauncherFragment.<init> []
  at java.lang.Class.getConstructor0 (Class.java:3395)
  at java.lang.Class.getConstructor (Class.java:2487)
  at androidx.fragment.app.Fragment.instantiate (Fragment.java:673)

**Smartphone / tablet**
 - Device: motorola denver
 - OS: Android 12
 - Package version: 11.1.0
 - Flutter version 3.24.2

**Additional context**

![image](https://github.com/user-attachments/assets/11e61884-be9f-4ed1-8ad7-548966ae46bf)

**Comment by remonh87** [comment] 2024-12-16 15:04
duplicate of #996

**Closed by remonh87** 2024-12-16 15:04 UTC
Labels: needs triage
