### ISSUE TITLE
PaymentRequestButton Stripe Element support for flutter_stripe_web [web]

### ISSUE THREAD

**Issue by par400** [flutter-stripe/flutter_stripe#1130] opened 2023-02-21 23:18 UTC
I'm trying to integrated one of the stripe elements in order to support Apple Pay / Google Pay for web app. but as of now, the current [PaymentElement](https://github.com/flutter-stripe/flutter_stripe/blob/main/packages/stripe_web/lib/src/widgets/payment_element.dart) has an issue #1129  . I was wondering when we can add [paymentRequestButton](https://stripe.com/docs/stripe-js/elements/payment-request-button) stripe element  for `flutter_stripe_web` library? Any plans for this feature?  that would be awesome.

https://stripe.com/docs/stripe-js/elements/payment-request-button

**Comment by cornwe19** [comment] 2023-11-07 00:13
I think this is a duplicate of #1122

**Comment by remonh87** [comment] 2024-04-14 15:13
this is now part of `flutter_stripe_web`

**Closed by remonh87** 2024-04-14 15:12 UTC
Labels: web
