### ISSUE TITLE
Google Pay button is not displayed on the payment sheet

### ISSUE THREAD

**Issue by joeloudjinz** [flutter-stripe/flutter_stripe#259] opened 2021-08-02 12:13 UTC
**Describe the bug**
Google pay button wasn't displayed on the paymentSheet despite setting the flage `googlePay: true` in `SetupPaymentSheetParameters` while initializing the payment sheet using `Stripe.instance.initPaymentSheet()`

**Expected behavior**
The button to be displayed

**Smartphone**
 - Device: Xiaomi Redmi 9
 - OS: Android 10, MIUI 12.0.1.0
 - Package version: ^1.2.0
 - Flutter version 2.2.3

**Additional context**
- the examples project doesn't provide anything about configuring google pay in payment sheet other than setting the flag to true
- i followed these [instructions ](https://stripe.com/docs/payments/accept-a-payment?platform=android&ui=payment-sheet#google-pay) form stripe's documentations to integrate google pay
#### My code
``` dart
  Future<void> initializePaymentSheet(
    PaymentCredentials credentials,
  ) async {
    Stripe.instance.initPaymentSheet(
      paymentSheetParameters: SetupPaymentSheetParameters(
        applePay: Stripe.instance.isApplePaySupported.value,
        googlePay: true,
        style: ThemeMode.dark,
        testEnv: true,
        merchantCountryCode: 'USA',
        merchantDisplayName: 'Our App. Inc.',
        customerId: credentials.clientId,
        paymentIntentClientSecret: credentials.paymentIntent,
        customerEphemeralKeySecret: credentials.eKey,
        customFlow: false,
      ),
    );
  }

  Future<void> presentPaymentSheet(String paymentIntent) async =>
      Stripe.instance.presentPaymentSheet(
        parameters: PresentPaymentSheetParameters(
          clientSecret: paymentIntent,
          confirmPayment: true,
        ),
      );
```

**Comment by jamesblasco** [comment] 2021-08-09 11:24
Could you confirm that you have implemented the following step? 

https://stripe.com/docs/google-pay#setup

**Comment by joeloudjinz** [comment] 2021-08-09 11:51
@jamesblasco  Only theses lines where added
```
<meta-data
    android:name="com.google.android.gms.wallet.api.enabled"
    android:value="true" />
```
Since i couldn't find a solution to this issue, i used google pay button provided by `pay` package and it worked. But for the payment sheet, the button is not shown.

**Comment by OMGloom** [comment] 2021-08-11 13:59
I'm having the same issue. Everything is set up exactly as OP.
I'm migrating the project from https://github.com/jonasbark/flutter_stripe_payment where we had Google Pay functional, so I'm sure our android setup is correct.

**Comment by AGKireev** [comment] 2021-08-11 14:47
Confirming same issue. All Stripe configurations are correct, Google Pay support on the mobile phone is verified, and there is no Google Pay button when calling presentPaymentSheet.

**Comment by UsamaKarim** [comment] 2021-08-12 06:07
Confirming issue on example app

**Comment by AGKireev** [comment] 2021-08-20 08:40
In my case the issue was in incorrect placement of the code:
`<meta-data
    android:name="com.google.android.gms.wallet.api.enabled"
    android:value="true" />`
inside the AndroidManifest.xml file.

The code was inside <application ..><activity ..> block, moving it up to <application ..> fixed the issue.

**Comment by joeloudjinz** [comment] 2021-10-18 08:31
as @anupin said, google pay button was displayed when gpay app is installed and there is at least a card available on google pay.
I was using separate google pay button on my app using `pay` plugin and it was displayed along with google pay sheet so i figured it should be shown on stripe's payment sheet as well.

**Comment by remonh87** [comment] 2022-01-06 16:14
Cannot reproduce this anymore on the latest SDK.

**Closed by remonh87** 2022-01-06 16:14 UTC

**Comment by aneeshjoshi** [comment] 2022-01-21 21:41
I'm following the example app the payment_sheet option and have enabled the api via AndroidManifest and build.gradle configurations. 

When I run the example app I'm able to launch the google pay on my android phone. When I mirror the flow for my own app, I receive OR_BIBED_07 as the error. I read that this might mean that Google Pay did not get instantiated. I can't seem to determine which part of the code in the example  payment_sheet (non custom) flow does this. 

![Screen Shot 2022-01-21 at 4 34 58 PM](https://user-images.githubusercontent.com/3219307/150603168-18429eba-51ba-4f32-bc91-8b1b454fae88.png)
 
Is this something that's missing in the documentation? Is the below json file required for the flow? 
![Screen Shot 2022-01-21 at 4 36 37 PM](https://user-images.githubusercontent.com/3219307/150603345-36203967-69b9-49b3-a5f2-70fe70dcd174.png)

I don't see it being utilized in the code except in the google_pay_screen.dart

Any help you can provide would be much appreciated
