### ISSUE TITLE
Payment Sheet - set default Country when user enters Card details

### ISSUE THREAD

**Issue by seanyyyyyy** [flutter-stripe/flutter_stripe#487] opened 2021-12-15 01:35 UTC
Currently the default Country in Payment Sheet is always United States would be nice to be able to change this.
Perhaps have it default to the same country as merchantCountryCode and also allow setting it manually through a variable in SetupPaymentSheetParameters?

**Comment by remonh87** [comment] 2021-12-15 12:57
duplicate of #285

**Closed by remonh87** 2021-12-15 12:57 UTC
Labels: needs triage
