### ISSUE TITLE
flutter stripe CardField input type should be number

### ISSUE THREAD

**Issue by avinashk369** [flutter-stripe/flutter_stripe#307] opened 2021-08-28 07:33 UTC
card input in CardField widget should be number or phone.

https://user-images.githubusercontent.com/5073425/131210279-42c60cfd-bd78-4eb1-82dd-6c36cb23df1a.mp4

its not a good experience for user to switch between input type for each number. 
tested on android.

**Comment by jonasbark** [comment] 2021-08-28 09:33
This is a duplicate of https://github.com/flutter-stripe/flutter_stripe/issues/14
You can use a very new Flutter version (e.g. dev channel) - it should show the correct keyboard at least

**Closed by jonasbark** 2021-08-28 09:33 UTC
