### ISSUE TITLE
confirmSetupIntent failing on Android

### ISSUE THREAD

**Issue by julesbacon** [flutter-stripe/flutter_stripe#173] opened 2021-06-30 04:52 UTC
I have a payment method entry screen with a similar setup to https://github.com/flutter-stripe/flutter_stripe/blob/07356f109f90f61f99d64106169a14269ca51eda/example/lib/screens/setup_future_payment_screen.dart (CardField stores card in state and then calls `confirmSetupIntent`) This works fine on iOS, but on Android it fails with the following logs:

```I/flutter (18788): Unhandled error type 'Null' is not a subtype of type 'String' in type cast occurred in Instance of 'AddPaymentMethodActionBloc'.
I/flutter (18788): #0      JSONMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:166:29)
I/flutter (18788): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158:18)
I/flutter (18788): <asynchronous suspension>
I/flutter (18788): #2      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:358:43)
I/flutter (18788): <asynchronous suspension>
I/flutter (18788): #3      MethodChannelStripe.confirmSetupIntent (package:stripe_platform_interface/src/method_channel_stripe.dart:98:20)
I/flutter (18788): <asynchronous suspension>
I/flutter (18788): #4      Stripe.confirmSetupIntent (package:flutter_stripe/src/stripe.dart:228:27)
I/flutter (18788): <asynchronous suspension>
```

Has anyone seen related android setup issues? I am using Flutter 2.2.2, with Pixel 3 emulator as my main testing device. Likely unrelated, but I have also been running into this issue with my CardField: https://github.com/flutter-stripe/flutter_stripe/issues/14

**Comment by remonh87** [comment] 2021-07-04 11:43
Can you try using our `sync` branch? I am able to confirm an setupintent without issues. For more info how to use remote branches check: https://dart.dev/tools/pub/dependencies#git-packages . We are planning to release a new major version soon.

**Comment by julesbacon** [comment] 2021-07-07 00:36
@remonh87 I tried using the `sync branch` by adding the following:
```flutter_stripe:
    git:
      url: git@github.com:flutter-stripe/flutter_stripe.git
      ref: sync
      path: packages/stripe```
      
I'm still seeing the issue on Android (and it still works fine on iOS)

**Comment by remonh87** [comment] 2021-07-11 11:50
I  am not able to reproduce it. Can you try using our example app? Also Can you send me the full log since I miss the actual error message. The stacktrace that you provided just says some decoding went wrong but not what is wrong

**Comment by remonh87** [comment] 2021-07-19 14:16
We did implement the new result parsing compliant with stripe sdk so it should be fixed in the next version

**Closed by remonh87** 2021-07-19 14:16 UTC
Labels: Android
