### ISSUE TITLE
Android failing to inflate card_input_widget

### ISSUE THREAD

**Issue by lbk9** [flutter-stripe/flutter_stripe#202] opened 2021-07-12 14:27 UTC
**Describe the bug**
The CardField widget is throwing a PlatformException on the latest version of the package on Android

**To Reproduce**

1. Launch app on Android
2. Navigate to page with the CardField widget
3. See following exception;

`PlatformException (PlatformException(error, Binary XML file line #22 in com.csl.freshcar:layout/card_input_widget`

**Expected behavior**
You expect to see the widget correctly rendered as it does on iOS

**Smartphone / tablet**
 - Device: OnePlus 9 Pro
 - OS: Android 11
 - Package version: [e.g. 1.1.0]
 - Flutter version [e.g. 2.2.3.]

**Comment by lbk9** [comment] 2021-07-12 14:30
Trouble package in code;
```
import 'package:flutter_stripe/flutter_stripe.dart' as stripe;
stripe.CardField(
            onCardChanged: (card) {},
          ),
        )
```

Logs;
E/MethodChannel#flutter/platform_views(25889): Caused by: java.lang.IllegalArgumentException: The style on this component requires your app theme to be Theme.AppCompat (or a descendant).
E/MethodChannel#flutter/platform_views(25889): 	at com.google.android.material.internal.ThemeEnforcement.checkTheme(ThemeEnforcement.java:243)
E/MethodChannel#flutter/platform_views(25889): 	at com.google.android.material.internal.ThemeEnforcement.checkAppCompatTheme(ThemeEnforcement.java:213)
E/MethodChannel#flutter/platform_views(25889): 	at com.google.android.material.internal.ThemeEnforcement.checkCompatibleTheme(ThemeEnforcement.java:148)
E/MethodChannel#flutter/platform_views(25889): 	at com.google.android.material.internal.ThemeEnforcement.obtainTintedStyledAttributes(ThemeEnforcement.java:115)
E/MethodChannel#flutter/platform_views(25889): 	at com.google.android.material.textfield.TextInputLayout.<init>(TextInputLayout.java:463)
E/MethodChannel#flutter/platform_views(25889): 	at com.google.android.material.textfield.TextInputLayout.<init>(TextInputLayout.java:422)
E/MethodChannel#flutter/platform_views(25889): 	... 31 more

**Comment by jonasbark** [comment] 2021-07-12 14:34
Please read the Readme - dupe of #69

**Closed by jonasbark** 2021-07-12 14:34 UTC

**Comment by lbk9** [comment] 2021-07-12 14:40
@jonasbark issue still persists, here is my styles.xml
`<?xml version="1.0" encoding="utf-8"?>
<resources>
    
    <style name="LaunchTheme" parent="Theme.AppCompat.Light.NoActionBar">
        
        <item name="android:windowBackground">@drawable/launch_background</item>
    </style>
    
    <style name="NormalTheme" parent="Theme.AppCompat.Light.NoActionBar">
        <item name="android:windowBackground">?android:colorBackground</item>
    </style>
</resources>`

**Comment by jonasbark** [comment] 2021-07-12 14:47
Please continue with the issue I linked. 
There's also a styles.xml for dark mode and you will have to adjust to use FlutterFragmentActivity

**Comment by lbk9** [comment] 2021-07-12 14:48
@jonasbark 
build.grade;
`classpath 'com.android.tools.build:gradle:4.1.2'`

mainactivity;
```
import io.flutter.embedding.android.FlutterActivity
import io.flutter.embedding.android.FlutterFragmentActivity

class MainActivity: FlutterFragmentActivity() {
}
```

**Comment by lbk9** [comment] 2021-07-12 14:59
Missed the dark themed one, brilliant @jonasbark
