### ISSUE TITLE
Unknown result this is likely a problem in the plugin {paymentOption: null}

### ISSUE THREAD

**Issue by appeventic** [flutter-stripe/flutter_stripe#1526] opened 2023-12-07 06:00 UTC
**Describe the bug**
Start card payment for a user that doesn't have any payment method in Stripe profile using customFlow = true.

**Error:**
"Unknown result this is likely a problem in the plugin {paymentOption: null}"

**Smartphone / tablet**
 - Device: iPhone 15 Pro Max Simulator
 - OS: iOS 17
 - Package version: ^9.5.0
 - Flutter version 3.13.1

**Additional context**
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.1, on macOS 13.5.1 22G90 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.82.1)
[✓] Connected device (5 available)
[✓] Network resources

Note: in Android it works fine.

**Comment by appeventic** [comment] 2023-12-12 03:53
@remonh87 Thanks for looking into it, I have created two gist -

PaymentIntent - https://gist.github.com/appeventic/d0fa99dc764fb992bc09888c87b78e9b
Client side payment flow - https://gist.github.com/appeventic/07744dd91ac6813bc6edf1d05df6b36e

Please let me know if I can provide more context. This error happening for a new user without any payment method linked to their profile.

**Comment by appeventic** [comment] 2023-12-14 06:50
Hi @remonh87 please let me know if you need more info. Is there any updates on this?

**Comment by appeventic** [comment] 2023-12-15 20:28
Could someone please help with this issue, this is blocking our app launch.

**Comment by remonh87** [comment] 2023-12-18 19:44
duplicate of #1465

**Closed by remonh87** 2023-12-18 19:44 UTC
Labels: Awaiting response
