### ISSUE TITLE
iOS Only - 3DS Authentication webview doesn't automatically close

### ISSUE THREAD

**Issue by juleshyacinthe** [flutter-stripe/flutter_stripe#1081] opened 2023-01-09 15:27 UTC
**Describe the bug**
When the Stripe SDK asks for a 3D Secure authentication (for payment or when attaching a payment method to a customer), the webview won't automatically close and will instead display a blank page.
This only happens when I set a `urlScheme` in the Stripe config at app launch. Not setting the `urlScheme` parameter will display a page asking the user to close the window instead.

**To Reproduce**
1. Enter a credit card number requiring an authentication in the card field, e.g. 4000 0000 0000 3220
2. Confirm the authentication.
3. The webview stays open.

**Expected behavior**
The webview should be closed after the authentication is performed.

**Smartphone / tablet**
 - Device: iPhone SE
 - OS: iOS 16
 - Package version: 5.0.0 - 7.0.0
 - Flutter version: 3.3.10

**Additional context**
I've tried versions 5.0.0 to 7.0.0 of the package and had the issue with each version.

**Comment by jonasbark** [comment] 2023-01-20 17:01
Closing this as duplicate of https://github.com/flutter-stripe/flutter_stripe/issues/955

**Closed by jonasbark** 2023-01-20 17:01 UTC
Labels: needs triage
