### ISSUE TITLE
Throws Card details not complete 

### ISSUE THREAD

**Issue by imrishuroy** [flutter-stripe/flutter_stripe#672] opened 2022-04-09 21:30 UTC
I am testing on an android device sometimes it works, but most of the time it gives this error 
StripeException(error: LocalizedErrorMessage(code: FailureCode.Failed, localizedMessage: Card details not complete, message: Card details not complete, stripeErrorCode: null, declineCode: null, type: null))

and my payment method log

PaymentMethod(id: pm_*************, livemode: false, type: Card, billingDetails: BillingDetails(email: null, address: Address(city: null, country: null, line1: null, line2: null, postalCode: null, state: null), phone: null, name: null), card: Card(brand: Visa, country: US, expYear: 2024, expMonth: 12, funding: credit, last4: 4242), sepaDebit: SepaDebit(country: null, bankCode: null, fingerprint: null, last4: null), bacsDebit: BacsDebit(sortCode: null, fingerprint: null, last4: null), auBecsDebit: AuBecsDebit(fingerprint: null, last4: null, bsbNumber: null), sofort: Sofort(country: null), ideal: Ideal(bankIdentifierCode: null, bank: null), fpx: Fpx(bank: null, accountHolderType: null), upi: Upi(vpa: null), customerId: null)

also  cvc and card number is printing null

**Comment by remonh87** [comment] 2022-04-10 08:28
I would recommend to add a `CardEditController` to the field and see if the all the data is updated correctly. Can you add the value of `controller.details` to this ticket (if you are not using test card you can anonymise the card).


See  https://github.com/flutter-stripe/flutter_stripe/blob/893a8449765af4d135a6737bdef1b53e5e6afa63/example/lib/screens/card_payments/no_webhook_payment_screen.dart#L19

**Comment by imrishuroy** [comment] 2022-04-10 17:13
Here are card details printed on the console

CardFieldInputDetails(complete: true, last4: 6927, expiryMonth: 12, expiryYear: 24, postalCode: null, brand: MasterCard, number: null, cvc: null, validExpiryDate: CardValidationState.Valid, validCVC: CardValidationState.Valid, validNumber: CardValidationState.Valid)

**Comment by remonh87** [comment] 2022-04-11 17:05
I cannot reproduce it on my side can you provide us a reproduction example  so we can triage the issue?

**Comment by kwstasarva** [comment] 2022-04-15 13:55
Hello @remonh87 . We are facing the same issue. For what it's worth, we are using BLOC as our state management solution. The issue only occurs on Android. We are using a cardEditController in our UI and then we try to confirm the payment within our BLOC. The details of the card are complete, however when we try to process the payment, a stripe exception occurs: 

`StripeException(error: LocalizedErrorMessage(code: FailureCode.Failed, localizedMessage: Card details not complete, message: Card details not complete, stripeErrorCode: null, declineCode: null, type: null))`

And further below this: 

`WARNING! Initial card data value has been ignored. 
      Handling card data manually will break PCI compliance provided by Stripe. Please make sure you understand the severe consecuences of it. [https://stripe.com/docs/security/guide#validating-pci-compliance](). 
      To handle PCI compliance yourself and allow to edit card data programatically,set `dangerouslyGetFullCardDetails: true``

We do not handle the card data on our own though.

**Comment by remonh87** [comment] 2022-04-15 14:47
@kwstasarva  we really need a GIST or repository containing some code where we can reproduce the issue. If this is not possible I am afraid I have to close this issue. I spent quite some time trying to find it but no success. Hopefully you can provide something to us.

**Comment by kwstasarva** [comment] 2022-04-15 14:52
Since we are working on a production application in a private repo, would it be possible for you to arrange a brief call to go through the code and have a look at the issue? Because it would be difficult to create a new repo to repro the issue. If not, I will do my best to provide a GIST. Thank you @remonh87

**Comment by adlion** [comment] 2022-04-16 05:22
Same issue using riverpod.
Card details are correct and pass validations.
The moment you send trigger `Stripe.instance.confirmPayment( ...)`
is showing the card details are not correct.

**Comment by kwstasarva** [comment] 2022-04-18 09:23
@remonh87 Please let me know of a way we can contact each other so I can help in any way to resolve the issue :)

**Comment by adlion** [comment] 2022-04-18 23:02
By investigating further I found out if you put the card element in provider states it will throw the unmentioned error. 
If you keep the card element outside the riverpod states is working correctly.
I was wondering what will happen if I put Stripe in a Statenotifier and manage its state from there.
I suppose it might work but have not tried yet due to some deadlines with current project.

**Comment by remonh87** [comment] 2022-04-19 07:07
@kwstasarva  feel free to send a me a dm on [twitter](https://twitter.com/remonh87?lang=en ) or [linkedin](https://www.linkedin.com/in/remon-helmond).

**Comment by kwstasarva** [comment] 2022-04-20 06:55
@remonh87  Unfortunately I cannot message you in any platform. All I am getting is "This user can't be messaged"

**Comment by fernan542** [comment] 2022-04-21 07:00
> @remonh87 Unfortunately I cannot message you in any platform. All I am getting is "This user can't be messaged"

Try to add a property in your `bloc` state that will handle the changes from the card.
```
class AddPaymentMethodState extends Equatable {
  const AddPaymentMethodState({
    this.details = const CardFieldInputDetails(complete: false),
    this.status = EventStatus.initial,
    this.errorMessage,
  });
  final CardFieldInputDetails details;
  final EventStatus status;
  final String? errorMessage;
  @override
  List<Object?> get props => [details, status, errorMessage];

  AddPaymentMethodState copyWith({
    CardFieldInputDetails? details,
    EventStatus? status,
    String? errorMessage,
  }) {
    return AddPaymentMethodState(
      details: details ?? this.details,
      status: status ?? this.status,
      errorMessage: errorMessage ?? this.errorMessage,
    );
  }

  @override
  String toString() {
    return ''' AddPaymentMethodState: { details: ${details.complete}, status: $status, error: $errorMessage } ''';
  }
}

```
Then on your UI:

```
 CardFormField(
              enablePostalCode: true,
              backgroundColor: Colors.white,
              onCardChanged: (details) => context
                  .read<AddPaymentMethodCubit>()
                  .onDetailsChanged(details),
            ),
``

This way you can check if the `CardFieldInputDetails` is really completed via logs.

**Comment by remonh87** [comment] 2022-04-23 14:12
yes the above solution of @fernan542  is correct.

Keep in mind The UI elements are not flutter UI objects but native objects (due to PCI compliance we have to use Stripe sdk elements) and all data must be updated through the methodchannels. I would really recommend to stick to our example implementations of the Cardfield and Cardformfield.  use the listeners on either the `controller` or the `onCardChanged` callback to determine whether or not the details are complete. It is fine to update BLOC or Riverpod based on these callbacks .

**Comment by kwstasarva** [comment] 2022-04-28 08:07
@fernan542 This is exactly what I am doing as well. However when I call 
```
final paymentIntent = await paymentClient.confirmPayment(
        paymentIntentClientSecret: initStripePayment.stripeToken,
        data: PaymentMethodParams.card(
          //only when customer accepts future usage
          setupFutureUsage: state.saveCardForFutureUsage.value
              ? PaymentIntentsFutureUsage.OffSession
              : null,
        ),
      );
```
I am still getting the same error as above. 
I believe there is something wrong with the instance of the card when used within the BLOC. 

Note: The paymentClient is an instance of Stripe.

**Comment by remonh87** [comment] 2022-05-01 08:38
closing this for now. feel free to reopen it when there is a reproduction scenario so we can debug the specifics.

**Closed by remonh87** 2022-05-01 08:38 UTC
Labels: Awaiting response

**Comment by naoaki-kaito** [comment] 2022-06-22 04:31
Hello, I faced same issue.

In my page, I want to get token using my holding data.

I edited the sample "legacy_token_card_screen.dart", but I got an error like the title.

The URL of gist is as follows.
https://gist.github.com/naoaki-kaito/a3405fbfd2fb1b87f667ab299a8ebfef

Thank you.

**Comment by naoaki-kaito** [comment] 2022-06-22 05:34
I solved it myself by using` CardDetails`.

```
CardDetails _card = CardDetails();

_card = _card.copyWith(number: '4242424242424242');
_card = _card.copyWith(expirationMonth: 9);
_card = _card.copyWith(expirationYear: 2024);
_card = _card.copyWith(cvc: '999');

await Stripe.instance.dangerouslyUpdateCardDetails(_card);

final tokenData =
          await Stripe.instance.createToken(CreateTokenParams.card(
              params: CardTokenParams(currency: 'USD')));
```

**Comment by Inventrohyder** [comment] 2022-07-15 18:21
We are also getting the same error

`StripeException(error: LocalizedErrorMessage(code: FailureCode.Failed, localizedMessage: Card details not complete, message: Card details not complete, stripeErrorCode: null, declineCode: null, type: null))`

However, downgrading to flutter_stripe 2.4.0 fixes the issue

**Comment by HatsuneMikuV** [comment] 2022-09-23 08:03
We are also getting the same error(Stripe 5.0 & 4.0), Everything works fine on ios

 
 `{complete: true, last4: 8600, expiryMonth: 7, expiryYear: 2024, postalCode: , brand: Visa, number: null, cvc: null, validExpiryDate: Unknown, validCVC: Unknown, validNumber: Unknown}`
 
`[log] confirmPayment error: StripeException(error: LocalizedErrorMessage(code: FailureCode.Failed, localizedMessage: Card details not complete, message: Card details not complete, stripeErrorCode: null, declineCode: null, type: null))`

**Comment by ydag** [comment] 2022-11-01 10:28
>StripeException(error: LocalizedErrorMessage(code: FailureCode.Failed, localizedMessage: Card details not complete, message: Card details not complete, stripeErrorCode: null, declineCode: null, type: null))

(Only for Android as well)

I am also having the same issue, I think this issue is not resolved yet @imrishuroy , @kwstasarva ? Could you open again @remonh87 ? Might be something related with android platform implementation since it works for iOS.

**Comment by kwstasarva** [comment] 2022-11-01 10:31
@ydag Are you using a state management library? BLOC, Riverpod or something? What I did to resolve my issue back then, was to move all the payment logic in the UI layer and not in our BLOCs. Can you check if this helps you?

**Comment by ydag** [comment] 2022-11-01 10:32
@kwstasarva 

Yes, I am using bloc as well. But the weird thing is it works on iOS. So not sure if it is related with state management solution?

**Comment by kwstasarva** [comment] 2022-11-01 10:34
@ydag I can't be sure either. When I moved the logic in the UI, it works fine for both platforms.

**Comment by ydag** [comment] 2022-11-01 10:57
Alright, thanks for your answer. @kwstasarva But I think this can be investigated further since we should be able to use with bloc as well. I still found it really interesting since it works on iOS.

**Comment by kwstasarva** [comment] 2022-11-01 11:29
@ydag I did not spend any more time looking into the issue to be honest. If you find a solution, please ping me. I am curious to know what the issue was

**Comment by ydag** [comment] 2022-11-14 16:31
@remonh87 Could you reopen this issue? I am still having it with 5.1.0.

**Comment by AlexChalakov** [comment] 2022-12-27 20:57
Can confirm the problem still occurs on android with flutter_stripe: ^7.0.0

**Comment by remonh87** [comment] 2022-12-27 21:06
Like said before please provide us with a reproduction scenario so we can fix it in the library.

**Comment by ShaowenSu** [comment] 2023-01-04 09:03
To everyone who is stuck with this issue, DO NOT dispose (close) of the card field until the payment is confirmed.

**Comment by ShaowenSu** [comment] 2023-01-04 09:05
> @ydag I did not spend any more time looking into the issue to be honest. If you find a solution, please ping me. I am curious to know what the issue was

DO NOT close the card field until the payment is confirmed.

**Comment by Minch909** [comment] 2023-10-17 07:03
> > @ydag I did not spend any more time looking into the issue to be honest. If you find a solution, please ping me. I am curious to know what the issue was
> 
> DO NOT close the card field until the payment is confirmed.

I still get this error even if I dont close the card field

**Comment by phawadshah** [comment] 2024-12-09 20:28
I have the same issue. In my case it works fine on IOS but throws that exception on andriod. 

Plus i want to ask if this would be PCI Complaince. i know it's not a bug but i just couldn't get it clearly from the docs. 
Thanks


         Padding(
              padding: const EdgeInsets.all(16),
              child: Column(
                children: [
                  CustomCardForm(
                    onCardSubmitted: (card) {
                      log('Card: $card');
                      cardDetails = card;
                      _handlePayPress(cardDetails!);
                    },
                  ),
                ],
              ),
            ),

 Future<void> _handlePayPress(CardDetails card) async {
    await Stripe.instance.dangerouslyUpdateCardDetails(card);
    try {

         // Step -1 Create Payment Intent
      PaymentMethod paymentMethod = await Stripe.instance.createPaymentMethod(
        params: const PaymentMethodParams.card(
          paymentMethodData: PaymentMethodData(),
        ),
      );
     
     // Step-2 CreateIntent
      String clientSecret = await createIntent(30);

     // Step-3 ConfirmPayment
      PaymentIntent intent = await Stripe.instance.confirmPayment(
        paymentIntentClientSecret: clientSecret,
        data: PaymentMethodParams.cardFromMethodId(
          paymentMethodData: PaymentMethodDataCardFromMethod(
            paymentMethodId: paymentMethod.id,
          ),
        ),
      );

      log('intent: $intent');
      ScaffoldMessenger.of(context)
          .showSnackBar(SnackBar(content: Text('Success: ${intent.status}')));
    } catch (e) {
      ScaffoldMessenger.of(context)
          .showSnackBar(SnackBar(content: Text('Error: $e')));
      rethrow;
    }
  }


@kwstasarva @HatsuneMikuV @remonh87 @Inventrohyder @ShaowenSu @Minch909

**Comment by remonh87** [comment] 2024-12-09 21:38
@phawadshah everything where you use a custom element to process card data is NOT pci compliant by default. 

To be clear every organisation that is handling payment cards need to be PCI compliant but when you use Stripe you normally need to be compliant at the lowest level. In your case it requires a higher lever and more bureacracy. 

I would really recommend integrating the paymentsheet as this is Stripes standard and comes with much more advantages than the cardfield:
- smoother animations
- out of the box integration of multiple payment methods
- handling the wallets
- error handling
- localisation

**Comment by phawadshah** [comment] 2024-12-10 17:33
@remonh87 Thank you very much for clearing it up. 

I agree about payment sheet, which is very easy to use but I have a very weird payment flow as per client requirements and i couldn't get it done in almost a week(not crying). The flow is like this

1 user has to enter card details, i use cardFormField(which is a stateful widget) for that in bottomSheet and when he clicks on the apply card button i update the ui with last4 and brand from cardFormField with an option to change it.
 
 2 then i update the checkout total with stripe charges which is considered as handling fee.
 3 user then can proceed with placing the order. (i create paymentMethod and then confirmMethod, which is working fine)
 
 the issues are
1.  this works completly fine on ios but throws card details incomplete on the andriod.
2. you might have noticed that i give user an option to change the card, once he clicks on the cardFormField appears with empty initial data al though he is trying to change and he does not then card in the stripe is set to null.


It will be really helpful if you guide me through this. Thank you

@kwstasarva @HatsuneMikuV @Inventrohyder @ShaowenSu

**Comment by crazyfeyn** [comment] 2025-01-20 06:24
Error presenting payment sheet: StripeException(error: LocalizedErrorMessage(code: FailureCode.Failed, localizedMessage: No such setupintent: 'seti_1QjE9I2c7xGGQHT5rH2IPmh7', message: No such setupintent: 'seti_1QjE9I2c7xGGQHT5rH2IPmh7', stripeErrorCode: resource_missing, declineCode: null, type: invalid_request_error))


I'm only gettign that error. The error is about invalid setupintent, but that setupintent client secret is working on web not on mobile. WHY?
