### ISSUE TITLE
How to disable Country/region and Zip code Field in Payment Sheet Screen?

### ISSUE THREAD

**Issue by pradeep14598** [flutter-stripe/flutter_stripe#455] opened 2021-11-19 11:45 UTC
In my case i have already collected user's country and postal code ,but while initiating payment it again ask to fill  country and zip code field .I need to disable it in my condition and please say how to do it?

**Comment by remonh87** [comment] 2021-11-21 10:09
duplicate of #330

**Closed by remonh87** 2021-11-21 10:09 UTC
