### ISSUE TITLE
.pub-cache/hosted/pub.dartlang.org/stripe_android-6.0.0/android/src/main/kotlin/com/facebook/react/bridge/WritableNativeMap.java:22: error: no suitable constructor found for ReadableMap(HashMap<Object,Object>)

### ISSUE THREAD

**Issue by SandipVKalola** [flutter-stripe/flutter_stripe#1018] opened 2022-11-10 10:45 UTC
Error with latest version: 6.0.0

/home/gmits-e20/.pub-cache/hosted/pub.dartlang.org/stripe_android-6.0.0/android/src/main/kotlin/com/facebook/react/bridge/WritableNativeMap.java:22: error: no suitable constructor found for ReadableMap(HashMap<Object,Object>)
        super(new HashMap<>());
        ^
    constructor ReadableMap.ReadableMap(JSONObject) is not applicable
      (argument mismatch; HashMap<Object,Object> cannot be converted to JSONObject)
    constructor ReadableMap.ReadableMap(Map<String,Object>) is not applicable
      (argument mismatch; HashMap<Object,Object> cannot be converted to Map<String,Object>)
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':stripe_android:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 50s
Exception: Gradle task assembleDebug failed with exit code 1

![Screenshot from 2022-11-10 16-13-58](https://user-images.githubusercontent.com/5462110/201070693-cfb4b7de-2b2e-4318-a427-59bb8dd6b124.png)

**Comment by Joran-Dob** [comment] 2022-11-11 13:56
Hi, I resolved the issue by following the steps in this issue https://github.com/flutter-stripe/flutter_stripe/issues/903

**Comment by remonh87** [comment] 2022-11-14 18:49
closing because is duplicate of #903

**Closed by remonh87** 2022-11-14 18:49 UTC
Labels: needs triage
