### ISSUE TITLE
borderRadius arg crash Method initPaymentSheet [ANDROID ONLY]

### ISSUE THREAD

**Issue by Artpel1805** [flutter-stripe/flutter_stripe#1411] opened 2023-09-12 19:39 UTC
**Describe the bug**
The border radius argument in the function initPaymentSheet throw an exception. The init works very well without it. 

**To Reproduce**
```
   await instance.initPaymentSheet(
          paymentSheetParameters: SetupPaymentSheetParameters(
        merchantDisplayName: '****',
        style: ThemeMode.light,
        appearance: PaymentSheetAppearance(
            shapes:
                PaymentSheetShape(borderRadius: 15,0),
            colors: PaymentSheetAppearanceColors(
                primaryText: TfColors.grey9.value,
                secondaryText: TfColors.grey5.value,
                primary: TfColors.primaryLight.value,
                error: TfColors.negativeDefault.value,
                icon: TfColors.primaryDefault.value)),
        paymentIntentClientSecret: paymentIntent?['client_secret'],
      ));
```
throw an `Exception` involving `borderRadius`
Work super well without it but storesheet has no border radius 

**Expected behavior**

I expect the scoresheet to init when having borderRadius arg

**Smartphone / tablet**
 - Device: A5010
 - OS:  Android 10
 - Package version: 9.4.0
 - Flutter version 3.10.4

**Additional context**

**Comment by remonh87** [comment] 2024-04-14 15:36
this is should be fixed now in latest sdk. I cannot reproduce it anymore

**Closed by remonh87** 2024-04-14 15:36 UTC
Labels: bug, Android
