### ISSUE TITLE
App got crashed after adding CardField

### ISSUE THREAD

**Issue by vishnuhifx** [flutter-stripe/flutter_stripe#194] opened 2021-07-09 10:03 UTC
My Android App got crashed after adding the CardField.
I added all the changes mentioned below.
Android 5.0 (API level 21) and above
Kotlin version 1.5.0 and above: example
Using a descendant of Theme.AppCompact for your activity:
Using FlutterFragmentActivity instead of FlutterActivity in MainActivity.kt:

I am getting this response

E/AndroidRuntime(32373): FATAL EXCEPTION: main
E/AndroidRuntime(32373): Process: com.tagcash, PID: 32373
E/AndroidRuntime(32373): java.lang.NoSuchMethodError: No direct method <init>(Landroid/content/Context;Lio/flutter/plugin/common/MethodChannel;)V in class Lcom/facebook/react/uimanager/ThemedReactContext; or its super classes (declaration of 'com.facebook.react.uimanager.ThemedReactContext' appears in /data/app/com.example-At200xy5dGa5WiVCgef58A==/base.apk!classes3.dex)
E/AndroidRuntime(32373): 	at com.flutter.stripe.StripeSdkCardPlatformView.<init>(StripeSdkCardPlatformView.kt:31)
E/AndroidRuntime(32373): 	at com.flutter.stripe.StripeSdkCardPlatformViewFactory.create(StripeSdkCardPlatformViewFactory.kt:19)
E/AndroidRuntime(32373): 	at io.flutter.plugin.platform.PlatformViewsController$1.createAndroidViewForPlatformView(PlatformViewsController.java:146)
E/AndroidRuntime(32373): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:101)
E/AndroidRuntime(32373): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:59)
E/AndroidRuntime(32373): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/AndroidRuntime(32373): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/AndroidRuntime(32373): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/AndroidRuntime(32373): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/AndroidRuntime(32373): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/AndroidRuntime(32373): 	at android.os.Looper.loop(Looper.java:182)
E/AndroidRuntime(32373): 	at android.app.ActivityThread.main(ActivityThread.java:7782)
E/AndroidRuntime(32373): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(32373): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/AndroidRuntime(32373): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:981)
I/Process (32373): Sending signal. PID: 32373 SIG: 9
Lost connection to device.

**Comment by jonasbark** [comment] 2021-07-09 10:07
Which Android device are you using for testing? Which Android version does it have?

**Comment by vishnuhifx** [comment] 2021-07-12 12:32
> Which Android device are you using for testing? Which Android version does it have?

I am testing it on Realme X and my Android version is 10.

**Comment by jonasbark** [comment] 2021-07-13 12:15
Does the example app work for you?
Which other plugins are you using?

**Comment by vishnuhifx** [comment] 2021-07-14 07:34
The example is working.
I am using the package https://pub.dev/packages/jitsi_meet in my project which is used for video chat.
When I commented it, it's working.
I think there is some conflict in the packages. Is there any solution?

**Comment by jonasbark** [comment] 2021-07-14 07:40
Closing this as dupe of https://github.com/flutter-stripe/flutter_stripe/issues/197
It has class conflicts because Jitsi Meet seems to have their own react native wrappers for whatever reasons. We're looking into solutions.

**Closed by jonasbark** 2021-07-14 07:40 UTC

**Comment by lucasvps** [comment] 2023-01-13 13:11
> Closing this as dupe of #197 It has class conflicts because Jitsi Meet seems to have their own react native wrappers for whatever reasons. We're looking into solutions.

Hello, did you guys found any solution?
