### ISSUE TITLE
Drawable google play button conent not found

### ISSUE THREAD

**Issue by 4gmayank** [flutter-stripe/flutter_stripe#1175] opened 2023-03-20 09:28 UTC
/build/stripe_android/intermediates/packaged_res/debug/layout/plain_googlepay_button.xml:10: AAPT: error: resource drawable/googlepay_button_content (aka com.linkomed:drawable/googlepay_button_content) not found.
<img width="1246" alt="image" src="https://user-images.githubusercontent.com/45072941/226298828-e9f5d958-fb49-4319-80a6-90d91a371552.png">

**Comment by rasmusGrift** [comment] 2023-03-22 23:11
I have the same issue. Already reported it in https://github.com/flutter-stripe/flutter_stripe/issues/1150#issue-1614291890

But they couldn't help.

**Comment by rasmusGrift** [comment] 2023-03-23 00:51
got it to work, my solution was here:
https://github.com/flutter-stripe/flutter_stripe/issues/1150#issuecomment-1480433839

**Comment by jonasbark** [comment] 2023-03-25 11:31
Closing it as duplicate of https://github.com/flutter-stripe/flutter_stripe/issues/1150#issue-1614291890

**Closed by jonasbark** 2023-03-25 11:31 UTC
Labels: needs triage
