### ISSUE TITLE
Android CardEditController widget initialDetails Faied

### ISSUE THREAD

**Issue by Yangpengtao** [flutter-stripe/flutter_stripe#649] opened 2022-03-23 06:06 UTC
Describe the bug
On Android system, we try to use cardeditcontroller to initialize the card number information. Android system does not work, apple can work.

To Reproduce

CardEditController controller = CardEditController(initialDetails: CardFieldInputDetails(complete: false, expiryYear: 2024, expiryMonth: 4, number: "123456789"));
CardField(
numberHintText: "Card Number",
dangerouslyGetFullCardDetails: true,
dangerouslyUpdateFullCardDetails: true,
controller: controller,
),
Apple can add initialization information by default, and the input box is still empty when Android opens
Expected behavior
Android can initialize normally

Smartphone / tablet

Device: samsung
OS: Android 11
Package version: 2.4.0
Flutter version [e.g. 2.10.3.]
Additional context
empty!

**Comment by jonasbark** [comment] 2022-03-23 07:03
dupe of https://github.com/flutter-stripe/flutter_stripe/issues/637

**Closed by jonasbark** 2022-03-23 07:03 UTC
Labels: needs triage
