### ISSUE TITLE
The plugin `stripe_android` requires Android SDK version 34

### ISSUE THREAD

**Issue by PollyGlot** [flutter-stripe/flutter_stripe#1525] opened 2023-12-05 17:20 UTC
**Describe the bug**
Since 2 days my circleci build fails on Android with the following error:

> Warning: The plugin stripe_android requires Android SDK version 34.
For more information about build configuration, see https://docs.flutter.dev/deployment/android#reviewing-the-gradle-build-configuration.
One or more plugins require a higher Android SDK version.
Fix this issue by adding the following to /root/code/android/app/build.gradle:
android {
  compileSdkVersion 34
  ...
}

While locally everything is working fine. 
I use version 9.2.2 of `flutter_stripe` package with `Flutter 3.7.12` and `compileSdkVersion = 33` with `targetSdkVersion = 33`. I did what the error suggested to do but it still fails without proposed solutions: 

> * What went wrong:
> Execution failed for task ':stripe_android:compileReleaseJavaWithJavac'.
> error: invalid source release: 17

I do not really understand what has happend, I will appreciate any suggestion.

**Comment by remonh87** [comment] 2023-12-05 18:28
This is a duplicate of: https://github.com/flutter-stripe/flutter_stripe/issues/1513 .  We enforce now android compilesdk 34 and AGP8 as per Google's recommendations. If you still need to use an older compile sdk you can fix the version to 9.5.1 https://github.com/flutter-stripe/flutter_stripe/issues/1513#issuecomment-1833221851

**Closed by remonh87** 2023-12-05 18:28 UTC
Labels: needs triage
