### ISSUE TITLE
Uncaught Unsupported operation: Platform._operatingSystem when deployed to firebase hosting for web

### ISSUE THREAD

**Issue by jeedy20** [flutter-stripe/flutter_stripe#1618] opened 2024-01-27 20:58 UTC
I get an Uncaught Unsupported operation: Platform._operatingSystem after i deploy my flutter web app to firebase hosting and its stucked in the splash screen any solution to this?.
I think this is the cause of the error in my main.dart page.
`  await dotenv.load(fileName: ".env");
  Stripe.publishableKey = dotenv.env['StripePublishableKey']!;
  Stripe.merchantIdentifier = 'merchant.flutter.stripe.test';
  Stripe.urlScheme = 'flutterstripe';
  await Stripe.instance.applySettings();`

**Comment by jeffysmak** [comment] 2024-01-28 11:07
Getting same, any solution you found?

**Comment by jeedy20** [comment] 2024-01-28 11:14
Nothing yet

**Comment by remonh87** [comment] 2024-01-29 16:29
Can you fill in the required info of the issue? I need a full stacktrace + output of flutter doctor.

**Comment by jeedy20** [comment] 2024-01-29 18:36
<img width="392" alt="Untitled" src="https://github.com/flutter-stripe/flutter_stripe/assets/43072734/d90a2c90-5f5a-4a4e-bae6-ab71ef1ad2d4">
`[√] Flutter (Channel stable, 3.16.9, on Microsoft Windows [Version 10.0.22000.2538], locale en-NG)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[√] Chrome - develop for the web
[!] Visual Studio - develop Windows apps (Visual Studio Build Tools 2019 16.11.33)
    X The current Visual Studio installation is incomplete.
      Please use Visual Studio Installer to complete the installation or reinstall Visual Studio.
[!] Android Studio (version 2021.3)
    X Unable to determine bundled Java version.
[√] Android Studio (version 2023.1)
[√] VS Code (version 1.85.2)
[√] Connected device (4 available)
[√] Network resources`
These are what you requested for

**Comment by jeffysmak** [comment] 2024-01-30 20:44
i implemented this plugin's basic of functionality my self and full fill my requirements. with stripe js (client side) card-field element, tested on firebase works smoothly.

**Comment by remonh87** [comment] 2024-02-04 13:21
@jeedy20 I cannot see in the stack trace that it has to do something with our sdk. What kind of widget are you using ?

**Comment by jeedy20** [comment] 2024-02-06 21:40
> @jeedy20 I cannot see in the stack trace that it has to do something with our sdk. What kind of widget are you using ?

Payment Element sir.

**Comment by jonasbark** [comment] 2024-02-07 07:11
I was unable to reproduce this in the example app. Can you provide a small example repo / code?

**Comment by richardnovasnw** [comment] 2024-02-08 09:43
I had been experiencing the same issue then realised that I forgot to add `flutter_stripe_web: ^5.0.0` to the dependencies.
`flutter_stripe` and `flutter_stripe_web`, both are required to work on flutter web.

This worked for me! Hope this helps someone.

**Comment by jeffysmak** [comment] 2024-02-10 10:18
> I had been experiencing the same issue then realised that I forgot to add `flutter_stripe_web: ^5.0.0` to the dependencies. `flutter_stripe` and `flutter_stripe_web`, both are required to work on flutter web.
> 
> This worked for me! Hope this helps someone.

i added both dependencies flutter_stripe and flutter_stripe_web but not worked for me 🤨. it works fine in debug mode but when app deployed to firebase hosting than its not.

**Comment by jeedy20** [comment] 2024-02-13 19:49
Yeah. Any solution yet?

**Comment by remonh87** [comment] 2024-02-13 20:52
does the same happen when you run `flutter run --release` ?

**Comment by asdico** [comment] 2024-02-17 14:45
@remonh87 I'm having the same issue, but as long as I'm working locally everything works. So, it doesn't happen the same when I run `flutter run --release`

**Comment by remonh87** [comment] 2024-03-02 10:29
I looked into it and this is a flutter issue and not something from this sdk: https://github.com/flutter/flutter/issues/36126

**Comment by jeedy20** [comment] 2024-03-02 10:44
So what could be the solution?

**Comment by asdico** [comment] 2024-03-02 10:57
@jeedy20 I solved the issue upgrading both Flutter and the SDKs version.

flutter --version
```
Flutter 3.19.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision bae5e49bc2 (2 weeks ago) • 2024-02-13 17:46:18 -0800
Engine • revision 04817c99c9
Tools • Dart 3.3.0 • DevTools 2.31.1
```
Flutter SKDs version:
```
  flutter_stripe: ^10.0.0
  flutter_stripe_web: ^5.0.0
```  
Try this out, it worked for me.

**Comment by jeedy20** [comment] 2024-03-02 11:00
Okay thanks alot

**Comment by andrezanna** [comment] 2024-03-02 11:26
Since I can not upgrade to Flutter 3.19 I made an hacky edit in method_channel_stripe

```
StripePlatform create() => kIsWeb?MethodChannelStripe(
    methodChannel: const MethodChannel(
      'flutter.stripe/payments',
      JSONMethodCodec(),
    ),
    platformIsIos: false,
    platformIsAndroid: false,
  ):MethodChannelStripe(
        methodChannel: const MethodChannel(
          'flutter.stripe/payments',
          JSONMethodCodec(),
        ),
        platformIsIos: Platform.isIOS,
        platformIsAndroid: Platform.isAndroid,
      );
```

**Comment by Nicola-Cestaro** [comment] 2024-06-27 11:24
I fixed this issue that for some reason only happened on the Web version on Android devices (iOS Web and Desktop Web was working fine)

With this 

`    if(kIsWeb){
      WebStripe.instance.initialise(publishableKey: "stripePublicKey");
    } else {
      Stripe.publishableKey = "stripePublicKey";
    }
`

**Comment by remonh87** [comment] 2024-07-17 19:30
closing as this is a flutter framework issue and not something we can fix. We are also close to shipping a new js interop library that hopefully fix these issues as well.

**Closed by remonh87** 2024-07-17 19:30 UTC
Labels: Awaiting response

**Comment by ElihuJ** [comment] 2025-05-10 06:32
> I fixed this issue that for some reason only happened on the Web version on Android devices (iOS Web and Desktop Web was working fine)
> 
> With this
> 
> ` if(kIsWeb){ WebStripe.instance.initialise(publishableKey: "stripePublicKey"); } else { Stripe.publishableKey = "stripePublicKey"; }`

I had exactly the same problem, this has saved me, thank you!
