### ISSUE TITLE
Stripe.instance.createPaymentMethod cannot create card payment method

### ISSUE THREAD

**Issue by smsimone** [flutter-stripe/flutter_stripe#122] opened 2021-06-07 13:36 UTC
**Describe the bug**
When I try to make a payment by creating before a PaymentMethod flutter_stripe rises the error:
`type 'String' is not a subtype of type 'Map<dynamic, dynamic>?' in type cast`

**To Reproduce**
1- launch the example app
2- open 'Card payment without web hooks' example
3- put the number '5155-0094-6187-6461' in the card field with random expiration date and CVV
4- press the pay button

**Smartphone**
 - Device: iPhone 12 Pro (simulated)
 - OS: iOs 14.5
 - Package version: 1.0.1+3
 - Flutter version [e.g. 2.0.0.]

**Comment by remonh87** [comment] 2021-06-07 13:41
This is a duplicate of: #87 which will is fixed in the next version of the library.  For now you can use our main branch:

```yaml
flutter_stripe: 
    git:
      url: https://github.com/flutter-stripe/flutter_stripe
      path: stripe/
```

**Closed by remonh87** 2021-06-07 13:41 UTC

**Comment by ericel** [comment] 2021-07-13 01:15
@remonh87 

> Could not find a file named "stripe/pubspec.yaml" in https://github.com/flutter-stripe/flutter_stripe a8cf882fd7a57abac375e6d33767ff0c6bf333a7.
> pub get failed (1; Could not find a file named "stripe/pubspec.yaml" in https://github.com/flutter-stripe/flutter_stripe a8cf882fd7a57abac375e6d33767ff0c6bf333a7.)
> exit code 1
