### ISSUE TITLE
Could not resolve com.stripe:stripe-android:20.12.+

### ISSUE THREAD

**Issue by ufukhawk** [flutter-stripe/flutter_stripe#1000] opened 2022-10-30 18:43 UTC
* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve com.stripe:stripe-android:20.12.+.
     Required by:
         project :app > project :stripe_android
      > Failed to list versions for com.stripe:stripe-android.
         > Unable to load Maven meta-data from https://jcenter.bintray.com/com/stripe/stripe-android/maven-metadata.xml.
            > Could not HEAD 'https://jcenter.bintray.com/com/stripe/stripe-android/maven-metadata.xml'.
               > Read timed out

**Comment by mirafiorielia** [comment] 2022-10-30 19:15
> * What went wrong:
> Execution failed for task ':app:checkDebugAarMetadata'.
> > Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
>    > Could not resolve com.stripe:stripe-android:20.12.+.
>      Required by:
>          project :app > project :stripe_android
>       > Failed to list versions for com.stripe:stripe-android.
>          > Unable to load Maven meta-data from https://jcenter.bintray.com/com/stripe/stripe-android/maven-metadata.xml.
>             > Could not HEAD 'https://jcenter.bintray.com/com/stripe/stripe-android/maven-metadata.xml'.
>                > Read timed out
> 
> 

I'm facing the same issue.

I tried:
• to change the maven url
• to change the gradle version
• to change flutter_stripe version
• to fork the flutter_stripe repo

None of this attempts worked for me.

**Comment by TheoBo** [comment] 2022-10-30 20:16
Same here

**Comment by mahanabd** [comment] 2022-10-30 20:40
and same

**Comment by myfknoll** [comment] 2022-10-30 20:51
Must be some kind of issue with jCenter
See also https://updownradar.com/status/jcenter.bintray.com
And I don't expect solutions on Sunday ;) So just wait till tomorrow and it will resolve by itself (I hope)

**Comment by SerdarN92** [comment] 2022-10-30 20:52
same problem here

**Comment by ufukhawk** [comment] 2022-10-30 20:55
> Must be some kind of issue with jCenter See also https://updownradar.com/status/jcenter.bintray.com And I don't expect solutions on Sunday ;) So just wait till tomorrow and it will resolve by itself (I hope)

yes, I think so too :)

**Comment by mirafiorielia** [comment] 2022-10-30 21:03
> Must be some kind of issue with jCenter
> See also https://updownradar.com/status/jcenter.bintray.com
> And I don't expect solutions on Sunday ;) So just wait till tomorrow and it will resolve by itself (I hope)

Actually I do think the same.

If you browse:
https://jcenter.bintray.com/com/stripe/stripe-android
you will get a 403 error code.

I dunno if the resources are blocked by default,
if not then there should be some problems server-side.

Tell me what do you think.

**Comment by tariq-alskran** [comment] 2022-10-30 21:33
+1

**Comment by brhomapps** [comment] 2022-10-31 01:23
same with me but 
Could not resolve com.stripe:stripe-android:20.1.+

**Comment by brhomapps** [comment] 2022-10-31 01:50
I change it to  20.1.0 it;s work for me

**Comment by cdwangco** [comment] 2022-10-31 02:28
Changing it to 20.1.0 made the first error go away. I tried to do the same thing for financial-connections but then got the error:

"Could not resolve com.stripe:financial-connections:20.1.0"

What is your financial-connections set to @brhomapps?

**Comment by raphaelbarbosaqwerty** [comment] 2022-10-31 03:10
> Must be some kind of issue with jCenter See also https://updownradar.com/status/jcenter.bintray.com And I don't expect solutions on Sunday ;) So just wait till tomorrow and it will resolve by itself (I hope)

Probably the issue is related to the jCenter, because yesterday I was working on the project, and today when I tried to build, it crashed with the same problem.

**Comment by panchalAlpit** [comment] 2022-10-31 04:22
I'm also facing the same issue any one can find the solution?

**Comment by tomyamGTX** [comment] 2022-10-31 04:24
same issue

**Comment by panchalAlpit** [comment] 2022-10-31 04:58
> I change it to 20.1.0 it;s work for me

where to change the version? please help me.

**Comment by iamsahilsonawane** [comment] 2022-10-31 05:33
There's a possible outage at jcenter as per https://updownradar.com/status/jcenter.bintray.com

**Comment by himani2022** [comment] 2022-10-31 05:33
> > I change it to 20.1.0 it;s work for me
> 
> where to change the version? please help me.

It's in gradle file of stripe in (READER MODE).
I'm also not able to change it.
can anybody please help? getting same issue :

Could not resolve com.stripe:financial-connections:20.4.+.

**Comment by nashirdrabi** [comment] 2022-10-31 05:45
I am facing the same issue while running the app . any update?

**Comment by n3rdkid** [comment] 2022-10-31 05:49
Facing the same issue. 😢

**Comment by MalikAreeb** [comment] 2022-10-31 05:52
facing the same issue

**Comment by himani2022** [comment] 2022-10-31 05:53
not able to run the app due to this issue

**Comment by wrteamJignesh** [comment] 2022-10-31 06:37
Add this code in your app->build.gradle file
in the code block of dependencies 


    constraints {
    implementation('com.stripe:stripe-android') {
        version {
            strictly '20.11.0'
        }
    }
}
constraints {
    implementation('com.stripe:financial-connections') {
        version {
            strictly '20.11.0'
        }
    }
}

**Comment by briankariuki** [comment] 2022-10-31 06:39
> Add this code in your app->build.gradle file in the code block of dependencies
> 
> `constraints { implementation('com.stripe:stripe-android') { version { strictly '20.11.0' } } } constraints { implementation('com.stripe:financial-connections') { version { strictly '20.11.0' } } }`

Please provide a better example.. by probably posting a sample build.gradle file with your proposed changes

**Comment by wrteamJignesh** [comment] 2022-10-31 06:42
> > Add this code in your app->build.gradle file in the code block of dependencies
> > `constraints { implementation('com.stripe:stripe-android') { version { strictly '20.11.0' } } } constraints { implementation('com.stripe:financial-connections') { version { strictly '20.11.0' } } }`
> 
> Please provide a better example.. by probably posting a sample build.gradle file with your proposed changes

![Capture](https://user-images.githubusercontent.com/111416494/198947263-cf0c6140-4691-4111-8e39-e623aeac625f.PNG)

**Comment by jonasbark** [comment] 2022-10-31 06:59
If you have jcenter() as part of your Androids repository sources then I recommend removing it altogether.

```
allprojects {
    repositories {
        google()
        mavenCentral()
    }
}
```

**Comment by 7Muzammil** [comment] 2022-10-31 07:02
> If

i dont have jcenter in my code, but getting same error

**Comment by briankariuki** [comment] 2022-10-31 07:03
> 

I have mavenCentral() in my build.gradle but I think this jCenter error is from the plugin itself

**Comment by egnimos** [comment] 2022-10-31 07:03
> > > Add this code in your app->build.gradle file in the code block of dependencies
> > > `constraints { implementation('com.stripe:stripe-android') { version { strictly '20.11.0' } } } constraints { implementation('com.stripe:financial-connections') { version { strictly '20.11.0' } } }`
> > 
> > 
> > Please provide a better example.. by probably posting a sample build.gradle file with your proposed changes
> > I hope this will work for you
> 
> ![Capture](https://user-images.githubusercontent.com/111416494/198947263-cf0c6140-4691-4111-8e39-e623aeac625f.PNG)

its working

**Comment by jonasbark** [comment] 2022-10-31 07:06
> I have mavenCentral() in my build.gradle but I think this jCenter error is from the plugin itself

neither the flutter_stripe nor stripe-android itself has any references to jcenter.

**Comment by 7Muzammil** [comment] 2022-10-31 07:11
> neither the flutter_stripe nor stripe-android itself has any references to jcenter.

you can see flutter_stipe build.gradle in git, it uses jcenter

**Comment by jonasbark** [comment] 2022-10-31 07:14
> > neither the flutter_stripe nor stripe-android itself has any references to jcenter.
> 
> you can see flutter_stipe build.gradle in git, it uses jcenter

Where?
https://github.com/flutter-stripe/flutter_stripe/blob/main/packages/stripe_android/android/build.gradle

**Comment by 7Muzammil** [comment] 2022-10-31 07:19
> Where?
> https://github.com/flutter-stripe/flutter_stripe/blob/main/packages/stripe_android/android/build.gradle

in my code too i didnt used the word jcenter,

from where it is coming?

**Comment by jonasbark** [comment] 2022-10-31 07:20
You can try using 
https://stackoverflow.com/a/57677542/1068346
to see where it's coming from

**Comment by 7Muzammil** [comment] 2022-10-31 07:25
> You can try using
> https://stackoverflow.com/a/57677542/1068346
> to see where it's coming from

ok thank you,

i will check

**Comment by 7Muzammil** [comment] 2022-10-31 07:32
> You can try using
> https://stackoverflow.com/a/57677542/1068346
> to see where it's coming from

i am using razorpay package, jcenter is used by razorpay package,
what can i do if i need voth packages?

**Comment by jonasbark** [comment] 2022-10-31 07:33
Contact razorpay to remove jcenter usages.

**Comment by ajonno** [comment] 2022-10-31 07:34
we also can not build app with same error! (no references to jcenter)

**Comment by 7Muzammil** [comment] 2022-10-31 07:39
will it fixed soon or it wont work with jcenter in future too?

**Comment by jonasbark** [comment] 2022-10-31 07:42
**There's nothing wrong with flutter_stripe. It does not cause the issue.** 
Accordingly, I'm closing this issue.

jcenter is deprecated and should no longer be used. **Neither** flutter_stripe **nor** stripe-android uses jcenter. Other plugins may use it.

Use https://stackoverflow.com/a/57677542/1068346  to find out which and contact them to fix it.

**Comment by ufukhawk** [comment] 2022-10-31 07:51
> **There's nothing wrong with flutter_stripe. It does not cause the issue.** Accordingly, I'm closing this issue.
> 
> jcenter is deprecated and should no longer be used. **Neither** flutter_stripe **nor** stripe-android uses jcenter. Other plugins may use it.
> 
> Use https://stackoverflow.com/a/57677542/1068346 to find out which and contact them to fix it.

I don't use jCenter in my project anyway, but I keep getting this error.

**Comment by niranjandawadi** [comment] 2022-10-31 08:07
This issue has not been solved.

**Comment by briankariuki** [comment] 2022-10-31 08:08
```

2022-10-31T05:32:46.1399120Z ##[section]Starting: [Flutter] Flutter build
2022-10-31T05:32:46.1444590Z ==============================================================================
2022-10-31T05:32:46.1445970Z Task         : Bash
2022-10-31T05:32:46.1446440Z Description  : Run a Bash script on macOS, Linux, or Windows
2022-10-31T05:32:46.1446890Z Version      : 3.201.1
2022-10-31T05:32:46.1447410Z Author       : Microsoft Corporation
2022-10-31T05:32:46.1449600Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/bash
2022-10-31T05:32:46.1450360Z ==============================================================================
2022-10-31T05:32:46.3939030Z Generating script.
2022-10-31T05:32:46.4304330Z Script contents:
2022-10-31T05:32:46.4306010Z /Users/runner/work/1/s/flutter/bin/flutter build apk
2022-10-31T05:32:46.4325700Z ========================== Starting Command Output ===========================
2022-10-31T05:32:46.4344600Z [command]/bin/bash /Users/runner/work/_temp/*******.sh
2022-10-31T05:32:52.7768970Z 
2022-10-31T05:32:52.7793590Z 💪 Building with sound null safety 💪
2022-10-31T05:32:52.7794080Z 
2022-10-31T05:35:59.5986740Z Running Gradle task 'assembleRelease'...                        
2022-10-31T05:35:59.6041360Z 
2022-10-31T05:35:59.6066310Z FAILURE: Build failed with an exception.
2022-10-31T05:35:59.6067910Z 
2022-10-31T05:35:59.6134900Z * What went wrong:
2022-10-31T05:35:59.6160730Z Execution failed for task ':stripe_android:mergeReleaseResources'.
2022-10-31T05:35:59.6264290Z > Could not resolve all files for configuration ':stripe_android:releaseRuntimeClasspath'.
2022-10-31T05:35:59.6293540Z    > Could not resolve com.stripe:stripe-android:20.12.+.
2022-10-31T05:35:59.6343340Z      Required by:
2022-10-31T05:35:59.6345400Z          project :stripe_android
2022-10-31T05:35:59.6349340Z       > Failed to list versions for com.stripe:stripe-android.
2022-10-31T05:35:59.6437550Z          > Unable to load Maven meta-data from https://jcenter.bintray.com/com/stripe/stripe-android/maven-metadata.xml.
2022-10-31T05:35:59.6441590Z             > Could not GET 'https://jcenter.bintray.com/com/stripe/stripe-android/maven-metadata.xml'.
2022-10-31T05:35:59.6443680Z                > Read timed out
2022-10-31T05:35:59.6446280Z 
2022-10-31T05:35:59.6447630Z * Try:
2022-10-31T05:35:59.6449650Z > Run with --stacktrace option to get the stack trace.
2022-10-31T05:35:59.6574570Z > Run with --info or --debug option to get more log output.
2022-10-31T05:35:59.6589710Z > Run with --scan to get full insights.
2022-10-31T05:35:59.6594120Z 
2022-10-31T05:35:59.6614160Z * Get more help at https://help.gradle.org
2022-10-31T05:35:59.6626110Z 
2022-10-31T05:35:59.6627890Z BUILD FAILED in 3m 6s
2022-10-31T05:36:00.9810100Z Running Gradle task 'assembleRelease'...                          188.1s
2022-10-31T05:36:01.0042320Z Gradle task assembleRelease failed with exit code 1
2022-10-31T05:36:01.0306040Z ##[error]Bash exited with code '1'.
2022-10-31T05:36:01.0368310Z ##[section]Finishing: [Flutter] Flutter build


```


As you can see its the stripe_android package causing the issue.

I'm using flutter_stripe ^5.1.0

**Comment by briankariuki** [comment] 2022-10-31 08:12
> **There's nothing wrong with flutter_stripe. It does not cause the issue.** Accordingly, I'm closing this issue.
> 
> jcenter is deprecated and should no longer be used. **Neither** flutter_stripe **nor** stripe-android uses jcenter. Other plugins may use it.
> 
> Use https://stackoverflow.com/a/57677542/1068346 to find out which and contact them to fix it.

I've posted an error log above. Indeed the error is from this package, specifically v5.1.0

**Comment by jonasbark** [comment] 2022-10-31 08:13
No, it's not caused by stripe_android. stripe_android does not use jcenter. Some other plugin that you use is using jcenter. You need to find out which one and then contact their authors. That's all you can do, until jcenter resolves their outage.

Stop blaming flutter_stirpe for it. If this continues I will have to lock this conversation.

Again:
https://github.com/flutter-stripe/flutter_stripe/issues/1000#issuecomment-1296642409
https://github.com/flutter-stripe/flutter_stripe/issues/1000#issuecomment-1296711421

**Comment by ufukhawk** [comment] 2022-10-31 08:13
fixed my problem, working now.

pubspec.yml file

```
dependency_overrides:
  firebase_core_platform_interface: 4.5.1 # if you use firebase
```
android/app/build.gradle file 

![Screen Shot 2022-10-31 at 10 59 01](https://user-images.githubusercontent.com/30172226/198959831-49d2346d-7e65-4072-878e-790177828fbe.png)

```
    constraints { implementation('com.stripe:stripe-android') { version { strictly '20.11.0' } } }
    constraints { implementation('com.stripe:financial-connections') { version { strictly '20.11.0' } } }
```

But this seems like a temporary solution.

**Comment by briankariuki** [comment] 2022-10-31 08:14
> No, it's not caused by stripe_android. stripe_android does not use jcenter. Some other plugin that you use is using jcenter. You need to find out which one and then contact their authors. That's all you can do, until jcenter resolves their outage.
> 
> Stop blaming flutter_stirpe for it. If this continues I will have to lock this conversation.
> 
> Again: [#1000 (comment)](https://github.com/flutter-stripe/flutter_stripe/issues/1000#issuecomment-1296642409) [#1000 (comment)](https://github.com/flutter-stripe/flutter_stripe/issues/1000#issuecomment-1296711421)

Have you atleast looked into the error log I have posted above?

**Comment by jonasbark** [comment] 2022-10-31 08:17
@briankariuki yes, I have. It's just a standard resolution issues. Gradle looks into jcenter first, doesn't find the proper information there (due to the outage), and throws the error. Again, unrelated to this plugin.

@ufukhawk I do not recommend downgrading stripe-android or financial-connections. It will cause issues with this plugin. Get rid of any jcenter references instead.

**Comment by ufukhawk** [comment] 2022-10-31 08:20
> @briankariuki yes, I have. It's just a standard resolution issues. Gradle looks into jcenter first, doesn't find the proper information there (due to the outage), and throws the error. Again, unrelated to this plugin.
> 
> @ufukhawk I do not recommend downgrading stripe-android or financial-connections. It will cause issues with this plugin. Get rid of any jcenter references instead.

I don't use any jCenter in my project.
Yes you are right, this may not be a stripe-related problem, because I also get the facebook version of the same error in my other project and I don't use jCenter in it either.

Thanks.

**Comment by jonasbark** [comment] 2022-10-31 08:22
If you are getting similar resolution errors like 
```
2022-10-31T05:35:59.6349340Z       > Failed to list versions for com.stripe:stripe-android.
2022-10-31T05:35:59.6437550Z          > Unable to load Maven meta-data from https://jcenter.bintray.com/com/stripe/stripe-android/maven-metadata.xml.
2022-10-31T05:35:59.6441590Z             > Could not GET 'https://jcenter.bintray.com/com/stripe/stripe-android/maven-metadata.xml'.
2022-10-31T05:35:59.6443680Z                > Read timed out
```
then your project IS using jcenter - that happens when a dependency declares jcenter as repository source.

**Comment by icodelifee** [comment] 2022-10-31 08:31
> If you are getting similar resolution errors like
> 
> ```
> 2022-10-31T05:35:59.6349340Z       > Failed to list versions for com.stripe:stripe-android.
> 2022-10-31T05:35:59.6437550Z          > Unable to load Maven meta-data from https://jcenter.bintray.com/com/stripe/stripe-android/maven-metadata.xml.
> 2022-10-31T05:35:59.6441590Z             > Could not GET 'https://jcenter.bintray.com/com/stripe/stripe-android/maven-metadata.xml'.
> 2022-10-31T05:35:59.6443680Z                > Read timed out
> ```
> 
> then your project IS using jcenter - that happens when a dependency declares jcenter as repository source.
![Screenshot 2022-10-31 at 2 00 53 PM](https://user-images.githubusercontent.com/18023153/198965100-a5ef004c-2d79-4518-8a8a-48194d987fa4.png)

I just dont understand why is it linking with stripe_android, i just looked through all of my packages and many of them seens to have jcenter() in build.gradle

**Comment by jonasbark** [comment] 2022-10-31 08:37
Probably because stripe_android is being resolved first and then throws the error, letting you think it's stripe_androids fault. If you remove flutter_stripe it will probably fail with the next dependency instead.

**Comment by icodelifee** [comment] 2022-10-31 08:37
> > @briankariuki yes, I have. It's just a standard resolution issues. Gradle looks into jcenter first, doesn't find the proper information there (due to the outage), and throws the error. Again, unrelated to this plugin.
> > @ufukhawk I do not recommend downgrading stripe-android or financial-connections. It will cause issues with this plugin. Get rid of any jcenter references instead.
> 
> I don't use any jCenter in my project. Yes you are right, this may not be a stripe-related problem, because I also get the facebook version of the same error in my other project and I don't use jCenter in it either.
> 
> Thanks.

According to my friend, Its a JCenter() problem, Gradle plugin portal proxies Jcenter behind

**Comment by icodelifee** [comment] 2022-10-31 08:38
> Probably because stripe_android is being resolved first and then throws the error, letting you think it's stripe_androids fault. If you remove flutter_stripe it will probably fail with the next dependency instead.

Yea, makes sense. I guess ill have to wait out till they fix the issue

**Comment by 7Muzammil** [comment] 2022-10-31 10:11
> Probably because stripe_android is being resolved first and then throws the error, letting you think it's stripe_androids fault. If you remove flutter_stripe it will probably fail with the next dependency instead.

to be honest, if i remove flutter_stripe package, my project is running fine.

**Comment by nashirdrabi** [comment] 2022-10-31 10:13
I removed flutter_stripe package from my app it works perfectly . So this is a flutter_stripe issue don't close this issue now its not resolved yet

**Comment by 7Muzammil** [comment] 2022-10-31 10:24
and @jonasbark is right, it is not issue of flutter_stripe, because i tested with creating new project and install only stripe package and it worked

**Comment by jonasbark** [comment] 2022-10-31 10:27
Yes, https://stackoverflow.com/a/74261483/1068346 can indeed be a good workaround - thanks @7Muzammil

**Comment by Harsha-Somaraju** [comment] 2022-10-31 10:40
@jonasbark This solution works

**Comment by imsungnam** [comment] 2022-10-31 10:44
I got a msg when it attached on my src. How I do?
----
Could not get unknown property 'url' for object of type org.gradle.api.internal.artifacts.repositories.DefaultFlatDirArtifactRepository.

**Comment by 7Muzammil** [comment] 2022-10-31 11:03
this solved my issue completely for now,

https://stackoverflow.com/a/74262111

**Comment by VB10** [comment] 2022-10-31 11:27
when I updated my project like this, it worked.

Firstly I've changed android/app/build.gradle

`
    constraints { 
        implementation('com.stripe:stripe-android') { version { strictly '20.11.0' } } }
         constraints { implementation('com.stripe:financial-connections') { version { strictly '20.11.0' } }
          }
`
then going to change android/build gradle with remove Center code.
`
allprojects {
    repositories {
        google()
        mavenCenter()
    }
}
`

**Comment by wasihDev** [comment] 2022-10-31 13:42
What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
Could not resolve com.stripe:stripe-android:20.12.+.
Required by:
project :app > project :stripe_android
> Failed to list versions for com.stripe:stripe-android.
> Unable to load Maven meta-data from https://jcenter.bintray.com/com/stripe/stripe-android/maven-metadata.xml.
> Could not HEAD 'https://jcenter.bintray.com/com/stripe/stripe-android/maven-metadata.xml'.
> Read timed out

I'm facing the same issue.

I tried:
• to change the maven url
• to change the gradle version
• to change flutter_stripe version
• to fork the flutter_stripe repo

Who solved this error properly

**Comment by raphaelbarbosaqwerty** [comment] 2022-10-31 14:06
> fixed my problem, working now.
> 
> pubspec.yml file
> 
> ```
> dependency_overrides:
>   firebase_core_platform_interface: 4.5.1 # if you use firebase
> ```
> 
> android/app/build.gradle file
> 
> ![Screen Shot 2022-10-31 at 10 59 01](https://user-images.githubusercontent.com/30172226/198959831-49d2346d-7e65-4072-878e-790177828fbe.png)
> 
> ```
>     constraints { implementation('com.stripe:stripe-android') { version { strictly '20.11.0' } } }
>     constraints { implementation('com.stripe:financial-connections') { version { strictly '20.11.0' } } }
> ```
> 
> But this seems like a temporary solution.

This temporary solution worked well.

**Comment by MobilyteApps** [comment] 2022-10-31 15:15
same issue here.
My lots of live users are facing the issue. 
and the above solution is not working for me.

**Comment by gdlin** [comment] 2022-10-31 15:28
This does not seem to be a Stripe plugin issue. You can add the following code and you'll be able to see in the console the conflicting plugins. Also, it should compile. It has worked for me, I've spent around 4 hours trying to fix this issue, starting by adding the constraint at first.

Edit your **android/build.gradle**, and remove jcenter() if you still have it (I didn't). Then, your allprojects section should look like this:

```
allprojects {
    repositories {
        def REPOSITORY_URL = 'https://maven.aliyun.com/repository/jcenter'
        all { ArtifactRepository repo ->
            if (repo instanceof MavenArtifactRepository) {
                if (repo.url.toString().startsWith('https://jcenter.bintray.com/')) {
                    project.logger.lifecycle "Repository ${repo.url} replaced by $REPOSITORY_URL."
                    remove repo
                    maven {
                        url REPOSITORY_URL
                    }
                }
            }
        }
        google()
        mavenCentral()
//        gradlePluginPortal() // Uncomment this if it still wont work
    }
}
```

This code replaces the repos matching jcenter with the new repo set in REPOSITORY_URL. There is a mirror at the time being, you can replace the following lines for another repo, such as mavenCentral().
```
                    maven {
                        url REPOSITORY_URL
                    }
```
After doing this modifications, open Android Studio (in you flutter project, inside the android folder) and go to **File -> Sync Project files with Gradle files.**

This should get your Flutter project compiling.

**PS: If this works for you, please leave a leave a thumbs up instead of replying, so it does not spam all the thread followers. If you find yourself having this issue as well, please star this issue (at the top of the page).**

**Comment by remonh87** [comment] 2022-10-31 19:53
We are aware of the problem and will monitor the issues: 
 https://github.com/stripe/stripe-react-native/issues/1186 and https://github.com/stripe/stripe-android/issues/5757  we also asked our contacts at Stripe to investigate it. For now use the current workarounds.. Will reopen it awaiting a proper fix in the designated repositories.

**Comment by HarshilPindoriya40** [comment] 2022-11-02 11:00
> > > Add this code in your app->build.gradle file in the code block of dependencies
> > > `constraints { implementation('com.stripe:stripe-android') { version { strictly '20.11.0' } } } constraints { implementation('com.stripe:financial-connections') { version { strictly '20.11.0' } } }`
> > 
> > 
> > Please provide a better example.. by probably posting a sample build.gradle file with your proposed changes
> > I hope this will work for you
> 
> ![Capture](https://user-images.githubusercontent.com/111416494/198947263-cf0c6140-4691-4111-8e39-e623aeac625f.PNG)

yes sir it working 
Thank you for suggestion

**Closed** 2022-11-03 20:47 UTC
Labels: bug, blocked

**Comment by erjanakmahato** [comment] 2022-11-14 11:03
E/MethodChannel#flutter.stripe/payments(15558): 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2112)
E/MethodChannel#flutter.stripe/payments(15558): 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1770)
E/MethodChannel#flutter.stripe/payments(15558): 	at android.app.Activity.startActivityForResult(Activity.java:5473)

**Comment by vladimirpetrovski** [comment] 2022-12-22 13:58
This is still an issue on the latest version, and adding a hardcoded version like this is not a solution. Flutter stripe should not use versions with the + sign for android. This should be defined for example `20.15.4` and not `20.15.+`.
