### ISSUE TITLE
 iOS inAppBrowser "Return to Merchant" button does not return back with iDeal, Bancontact and FPX

### ISSUE THREAD

**Issue by vladms** [flutter-stripe/flutter_stripe#462] opened 2021-11-23 09:45 UTC
**Describe the bug**
I tried paying with iDeal in the example app. The iOS can open the payment link  in two ways: 
1. Opening safari as a different app
2. Opening InAppBrowser

After authorising the payment, the browser should redirect user to the app. This happens only when Safari is opened as a different app.  The "Return to Merchant" button gives me this log every time I tap it:
Deep Link does not contain valid required params. URL params: {
    "redirect_status" = succeeded;
    "setup_intent" = "<.....>";
    "setup_intent_client_secret" = "<......>";
}

**To Reproduce**
1. Download the example app
2. Change the stripe publishable key
3. Pay with iDeal
4. The inAppBrowser is opened
5. Authorise or decline the payment
6. Back to merchant is "blocked". Does not take the user back to the app

**Expected behavior**
After the payment was authorised/declined, the inAppBrowser should open the app

**Smartphone / tablet**
 - Device: Simulator iPhone 11 Pro Max

 - OS: 14.5
 - Package version: 2.0.2
 - Flutter version 2.5.2
 
  - Device: Simulator iPhone X
 - OS: 15.1
 - Package version: 2.0.2
 - Flutter version 2.5.2

**Additional context**
Here is a video of the issue: 
Uploading Simulator Screen Recording - iPhone 11 Pro Max - 2021-11-23 at 11.42.46.mp4…

**Comment by remonh87** [comment] 2021-11-28 17:11
Thanks for reporting I think I can reproduce it. The interesting thing is that on the example app the success callback is received. When I print the received routes in the material app I get: `?payment_intent=pi_3Kxxxxxxxx&payment_intent_client_secret=pi_3Kxxxxxx_secret_xxxxxx&redirect_status=succeeded null` . I think the return to merchant button not working is something specific to that site though and won't happen in production.  Will come back to you on this.

**Comment by remonh87** [comment] 2021-11-28 17:12
Other question can you still upload your video :) ? just to make sure the problem is the same

**Comment by jamesblasco** [comment] 2021-11-29 08:29
I think the error is because the example app right now has an invalid urlScheme setup in main.dart
`Stripe.urlScheme = 'flutterstripe';`

You should ensure a scheme that you have configured correctly to open back the app

**Comment by vladms** [comment] 2021-12-02 15:37
The urlScheme is correct because it works when I open the Safari app.
https://user-images.githubusercontent.com/11149275/144453291-56a20bb9-e5c6-4d38-8459-8464ddb2fe71.mp4

**Comment by remonh87** [comment] 2021-12-09 07:39
@vladms  I can reproduce it and I will raise a question to Stripe for advice since when I run it in Safari it works like it should be.

**Comment by VladBontaValentin** [comment] 2022-01-05 09:02
@remonh87 @jamesblasco Any updates on this issue?

**Comment by vladms** [comment] 2022-01-05 09:03
@jamesblasco  @remonh87  Any updates on this issue?

**Comment by remonh87** [comment] 2022-01-06 10:51
@vladms there is no reaction from Stripe yet I will poke them again

**Comment by vladms** [comment] 2022-01-19 08:59
@remonh87  Any answers from Stripe?

**Comment by vladms** [comment] 2022-02-02 08:53
@remonh87  Anything?

**Comment by remonh87** [comment] 2022-02-02 18:03
@vladms  I am thinking if it can be an issue on the stripe test page. I did some testing on flutter and I noticed the callback is received directly however the page is not closed and I have to press `return to merchant`. I will play a bit more in the weekend. I think however you wouldn't have issues in production (at least I didn't have ).

**Comment by ayushin** [comment] 2022-03-02 02:47
This is related to https://github.com/flutter-stripe/flutter_stripe/issues/609

Without return_url you'll get whatewhere scheme :/?safepay.... which is not correct in many case and doesn't work across platform.

**Comment by Sempakonka** [comment] 2022-03-02 13:53
Any updates? am also having this issue. Raised an issue [#608](https://github.com/flutter-stripe/flutter_stripe/issues/608) where I am not using the example app but experiencing the same behaviour.

**Comment by kawaldeep2507** [comment] 2022-03-10 17:08
Any updates on this? i am also having this issue.

**Comment by adar2378** [comment] 2022-04-01 12:15
We're also having the problem where return to merchant is not closing the WebView but deeplink url is returning when we use test failure in test mode.

**Comment by nitishk72** [comment] 2022-05-06 13:22
### Fixed after few days of Research  🎉 
After going through the Stripe SDK and their official library, I was able to fix it.
As I was in hurry, I fix it in my local and build my app.

Soon I'll share the solution with you all and a PR.

**Comment by mvnpavan** [comment] 2022-05-24 04:23
> ### Fixed after few days of Research 🎉
> After going through the Stripe SDK and their official library, I was able to fix it. As I was in hurry, I fix it in my local and build my app.
> 
> Soon I'll share the solution with you all and a PR.

Any update.

**Comment by gsfeng** [comment] 2022-05-25 12:52
> ### Fixed after few days of Research 🎉
> After going through the Stripe SDK and their official library, I was able to fix it. As I was in hurry, I fix it in my local and build my app.
> 
> Soon I'll share the solution with you all and a PR.

Any update??

**Comment by anderscheow** [comment] 2022-05-27 05:51
> ### Fixed after few days of Research  🎉 
> 
> After going through the Stripe SDK and their official library, I was able to fix it.
> 
> As I was in hurry, I fix it in my local and build my app.
> 
> 
> 
> Soon I'll share the solution with you all and a PR.

Hey sir, any update on this? Need it badly

**Comment by remonh87** [comment] 2022-06-06 18:15
Fixed in version 3.1.0 thanks @anderscheow  for the fix!

**Closed by remonh87** 2022-06-06 18:15 UTC
Labels: bug, iOS, blocked

**Comment by adar2378** [comment] 2022-06-07 05:55
@anderscheow 
On iOS, the in-app browser is still not closing when pressed "Return to Merchant". But the deep link is pushed from the callback in the router. So the user has to manually press the "Close"(in in-app browser) button to go back to the payment success bottomsheet.

Is there anything I'm missing?

**Tested on 3.1.0**

**Comment by Sempakonka** [comment] 2022-06-07 06:50
> @anderscheow 
> 
> On iOS, the in-app browser is still not closing when pressed "Return to Merchant". But the deep link is pushed from the callback in the router. So the user has to manually press the "Close"(in in-app browser) button to go back to the payment success bottomsheet.
> 
> 
> 
> Is there anything I'm missing?
> 
> 
> 
> **Tested on 3.1.0**

I am also still experiencing this behaviour.

**Comment by anderscheow** [comment] 2022-06-08 03:29
@adar2378 @Sempakonka 

Can just follow the `example` and should have just work

1. Set url scheme, `Stripe.urlScheme = 'examplestripe'
2. Make sure the same url scheme is configure in `Info.plist`

**Comment by Sempakonka** [comment] 2022-06-08 12:05
> @adar2378 @Sempakonka
> 
> Can just follow the `example` and should have just work
> 
> 1. Set url scheme, `Stripe.urlScheme = 'examplestripe'`
> 2. Make sure the same url scheme is configure in `Info.plist`

Its working, Thanks :partying_face:

**Comment by adar2378** [comment] 2022-06-09 17:29
> > @adar2378 @Sempakonka
> > Can just follow the `example` and should have just work
> > 
> > 1. Set url scheme, `Stripe.urlScheme = 'examplestripe'`
> > 2. Make sure the same url scheme is configure in `Info.plist`
> 
> Its working, Thanks 🥳

Hi @Sempakonka Could you share your config for info.plist?

I've added 

`<dict>
			<key>CFBundleTypeRole</key>
			<string>Editor</string>
			<key>CFBundleURLName</key>
			<string>safepay</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>flutterstripe</string>
			</array>
		</dict>
		`
Also `Stripe.urlScheme = 'flutterstripe';`

But still it is not closing the webview from 'Return to merchant'

Could it be the `returnUrl` need to match `flutterStripe://safepay/` as prefix?

**Comment by Sempakonka** [comment] 2022-06-09 18:11
@adar2378 
```
	<array>
		<dict>
			<key>CFBundleTypeRole</key>
			<string>Editor</string>
			<key>CFBundleURLName</key>
			<string>com.mycompany.myapp</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>com.mycompany.myapp</string>
			</array>
		</dict>
	</array>
```
In Dart:
`Stripe.urlScheme = 'com.divics.svglanerbrug-dev://safepay';`
Both need to be the same.

**Comment by nitishk72** [comment] 2022-06-11 07:06
I solved this solution more in the way which is recommended by the Stripe team.

- I look into the react-native stripe first
- I found that it react-native takes the deep link and then closes the app
- This means to close the webview, flutter needs to send the event to the stripe plugin.


`handleURLCallback` is being called on react native side to close the webview. The solution that @anderscheow sent does the same using the swift side. This thing should be done from the flutter side to have the same logic and standard.

**Comment by saiful-apx** [comment] 2022-09-21 21:57
This should fix the issue with `handleURLCallback` method. From Flutter side whenever the deep-link is pushed we will need to pass the full redirect url sent from stripe to `Stripe.instance.handleURLCallback` method. This will close the webview.

https://github.com/flutter-stripe/flutter_stripe/pull/939
