### ISSUE TITLE
Question: Can you save Google/Apple Pay for later use via the PaymentSheet?

### ISSUE THREAD

**Issue by Flajt** [flutter-stripe/flutter_stripe#426] opened 2021-11-07 22:03 UTC
As the title mentions can one use the PaymentSheet with a SetupIntent to save a card via GooglePay / ApplePay?
I've got GooglePay installed on my device, added the required xml entry, and set google pay & apple pay parameters to true, passed the setupIntent secret but it doesn't pop up as a button. So I'm wondering if that is possible this way or not?

**Comment by remonh87** [comment] 2021-11-09 18:11
I think this should be possible. Do not forget to use the latest library and set `allowsDelayedPaymentMethods ` to true

**Comment by Flajt** [comment] 2021-11-09 18:47
I've done it now like this:

```dart
 await Stripe.instance.initPaymentSheet(
        paymentSheetParameters: SetupPaymentSheetParameters(
            merchantDisplayName: "Simple Checkout",
            allowsDelayedPaymentMethods: true,
            googlePay: true,
            setupIntentClientSecret: secret,
            style: ThemeMode.light,
            testEnv: true));
await Stripe.instance.presentPaymentSheet();
```

It doesn't show GooglePay as an option, do I need to call: 

```dart 
await Stripe.instance.initGooglePay(GooglePayInitParams(merchantName: "Simple Checkout", countryCode: "DE", testEnv: true))
```
this beforehand as well?

**Comment by remonh87** [comment] 2021-11-14 20:11
I do not think setupintents are compatible with Google pay, since they are used to save card details for later use. I tested on our library with a payment intent and then I have google pay and then with a setup intent and then Google pay is not there.  

If you want absolute certainty I would recommend to talk with Stripe support.

**Comment by matthewfx** [comment] 2021-12-03 05:26
@Flajt & @remonh87 any luck with it? According to Stripe docs it is possible.
https://stripe.com/docs/payments/save-and-reuse

**Comment by matthewfx** [comment] 2021-12-09 10:20
I've just tested it on iPhone and unfortunately if Apple Pay button is used from the sheet but it doesn't show the Apple pay bottom sheet and the app never gets out of the code executed by `await Stripe.instance.presentPaymentSheet();` :( There is no exception being thrown either. On Stripe there is a setup intent initialised but it is incomplete (missing payment metod) so it feels like it doesn't pass the Apple pay token...  I briefly checked that I can get a card from an Apple Pay token and pass it manually to create a setup token and that creates a setup intent. So it looks like that is possible but something is broken in the library. It would be great if you could look into it. Thank you in advance :)

**Comment by matthewfx** [comment] 2021-12-09 23:19
@remonh87 I just spent quite some time with Stripe support and they told me it should be working fine because Apple Pay can be used for setup intents and can be used from the payment sheet UI component. Could you please reopen the issue and hopefully someone soon will be able look into why it doesn't work?

**Comment by matthewfx** [comment] 2021-12-10 08:30
@remonh87 So I've just received an email from Stripe support. 

_"...My team and I thoroughly checked this here on our back end; however, we confirmed that Apple Pay and Google Pay are currently not supported for Setup Intents. I totally understand that you prefer to utilize Setup Intents since you’ll be charging your customers for a subscription on a monthly basis rather than Payment Intents..."_

:(

**Comment by remonh87** [comment] 2021-12-10 09:41
thanks @matthewfx  for providing this information. I will make sure to add this to the docs so other users of this library knows this as well!

**Comment by toklive** [comment] 2022-01-05 13:59
We have got it working and it is not true that setup intent can't save mobile wallets info. We got the confirmation from strip devs in discord channel as well

**Comment by remonh87** [comment] 2022-01-06 08:02
@toklive  thanks for lettings us know can you provide some info  how you did solve it so others can benefit from this?

**Comment by jonasbark** [comment] 2022-01-18 19:53
@toklive can you please share your findings?

**Comment by jonasbark** [comment] 2022-01-21 07:08
I reached out to Stripe support and a fix is pending for stripe-react-native:
https://github.com/stripe/stripe-react-native/pull/774

Closing this issue when the fix is integrated to flutter_stripe

**Comment by matthewfx** [comment] 2022-01-24 23:25
@toklive We've got just Apple Pay working in a scenario when we use the payment sheet for subscription (which requires the setup intent). Could you please tell us if Google Pay works for you and if does please share how have you achieved it?

**Comment by hawkinsjb1** [comment] 2022-02-02 00:24
Looks like the react-native fix was merged, any ETA on Flutter integration?

**Comment by remonh87** [comment] 2022-02-02 18:05
We will integrate it with the next Stripe sync I will label it so we will test it once stripe releases a new version of the sdk. Not sure about an ETA but we will keep an close eye on the stripe repo

**Comment by remonh87** [comment] 2022-02-14 18:33
We launched version `2.2.0` to pub.dev

**Closed by remonh87** 2022-02-14 18:33 UTC
Labels: Generic question

**Comment by dragouf** [comment] 2022-04-14 12:20
I successfully display apple pay for setup intent but apple sent me back my app telling that I don't display any price on payment sheet. 

Since it's just to record the card (setup) and not to pay directly, it seems normal for me. Did someone successfully use apple pay for setup intent and was able to pass apple validation ? 

Also, is it possible to display information about future payment on the setup intent sheet ?

**Comment by jonasbark** [comment] 2022-04-14 13:36
Hi @dragouf - these questions are best posted on the official https://github.com/stripe/stripe-ios repository :)
