### ISSUE TITLE
Option of Removing Country in CardFormField or Disable Selection or List Alteration

### ISSUE THREAD

**Issue by doshikh** [flutter-stripe/flutter_stripe#628] opened 2022-03-11 12:11 UTC
I want to restrict country list or hide Country drop down same as enablePostalCode: false , option from CardFormField

But there is no option in plugin for that 
Problem : When ever user changed country postcode field appear again
If it's there please let me know 

I am using version 1.3.0 of flutter_stripe in my flutter project

Please refer screenshots for check.

<img width="387" alt="Screenshot 2022-03-11 at 5 41 56 PM" src="https://user-images.githubusercontent.com/4567442/157864717-c5d10746-ce60-4204-b18e-41e0d5b5f1b8.png">
<img width="395" alt="Screenshot 2022-03-11 at 5 42 40 PM" src="https://user-images.githubusercontent.com/4567442/157864813-d9e47691-edd2-4f0f-82c2-ecabc24ae023.png">

**Comment by remonh87** [comment] 2022-03-14 19:18
We need to wait when Stripe fixes country behavior in their sdk. See: https://github.com/stripe/stripe-react-native/issues/695. and  https://github.com/stripe/stripe-react-native/issues/816

**Comment by memishood** [comment] 2022-10-25 12:39
same problem here..

**Comment by jamesdixon** [comment] 2023-03-06 17:09
@remonh87 it seems they now allow for the country to be overridden on Android: https://github.com/stripe/stripe-react-native/pull/974

**Comment by komailabbas12** [comment] 2023-03-13 18:17
@jamesdixon 
```

 if (initSheet.error) return Alert.alert(initSheet.error.message);
    const presentSheet = await stripe.presentPaymentSheet({
      clientSecret,
    });
```

how you set the default country?

**Comment by remonh87** [comment] 2023-03-13 18:35
@jamesdixon  you can add the countryside to the card form on Android it is still not implemented for iOS. 

@komailabbas12  this ticket is related to the card form and not the payment sheet. The payment sheet uses the phones locale but you can change it by providing `billingDetails`

**Comment by komailabbas12** [comment] 2023-03-13 18:44
@remonh87 
 ```
const initSheet = await stripe.initPaymentSheet({
      paymentIntentClientSecret: clientSecret,
      merchantDisplayName: paymentDetails?.senderUser?.fullname,
      defaultBillingDetails:{
        address :{
        country: 'GB'
        }}
     
    });
```
this works on android side Thank you

**Comment by udayakr** [comment] 2023-08-29 05:17
Is there an option to restrict the country list to USA and Canada from stripe dashboard ?

**Comment by remonh87** [comment] 2024-04-14 14:35
Default countries is supplied the option to disable is duplicate of #320  so will close this is one now

**Closed by remonh87** 2024-04-14 14:35 UTC
Labels: enhancement, blocked
