### ISSUE TITLE
Card details not complete error on GooglePayment 

### ISSUE THREAD

**Issue by myunggeonchung** [flutter-stripe/flutter_stripe#644] opened 2022-03-17 08:22 UTC
**Describe the bug**

          final paymentResult = await payClient.showPaymentSelector(
            provider: payProvider,
            paymentItems: paymentItems,
          );
          String tokenId;
            final token =
                paymentResult['paymentMethodData']['tokenizationData']['token'];
            final tokenJson = Map.castFrom(json.decode(token));
            tokenId = tokenJson['id'];

          final paymentIntent = await Stripe.instance.confirmSetupIntent(
            value.setupIntentClientSecret!,
            PaymentMethodParams.cardFromToken(token: tokenId),
          );

The app tries to confirm setupIntent with secretKey and token
But the 'Card details not complete' also occurs as below
StripeException(error: LocalizedErrorMessage(code: FailureCode.Failed, localizedMessage: Card details not complete, message: Card details not complete, stripeErrorCode: null, declineCode: null, type: null)

Can you check it out? I'm under the pressure from my company.

**Comment by remonh87** [comment] 2022-03-18 10:51
Creating the same issue doesn't help. We try to triage issues as quick as we can but we also have our other obligations :) 
duplicate of #612

**Closed by remonh87** 2022-03-18 10:51 UTC
Labels: needs triage

**Comment by myunggeonchung** [comment] 2022-08-24 12:46
@remonh87 Did you fix this issue?
