### ISSUE TITLE
Firebase Crash Events Fatal Exception

### ISSUE THREAD

**Issue by KallepalliTirumalesh** [flutter-stripe/flutter_stripe#1793] opened 2024-06-10 07:15 UTC
I am using V10.1.1 for my flutter app i see this two crash events on production in firebase crashlytics

1.GooglePayLauncherFragment.onViewCreated
oo.k0 - lateinit property configuration has not been initialized
com.reactnativestripesdk
GooglePayLauncherFragment.java:13

`Fatal Exception: oo.k0
lateinit property configuration has not been initialized
com.reactnativestripesdk.GooglePayLauncherFragment.onViewCreated (GooglePayLauncherFragment.java:13)
androidx.fragment.app.Fragment.performViewCreated (Fragment.java:14)
androidx.fragment.app.FragmentStateManager.createView (FragmentStateManager.java:313)
androidx.fragment.app.FragmentStateManager.moveToExpectedState (FragmentStateManager.java:124)
androidx.fragment.app.FragmentStore.moveToExpectedState (FragmentStore.java:30)
androidx.fragment.app.FragmentManager.moveToState (FragmentManager.java:27)
androidx.fragment.app.FragmentManager.dispatchStateChange (FragmentManager.java:9)
androidx.fragment.app.FragmentManager.dispatchActivityCreated (FragmentManager.java:11)
androidx.fragment.app.FragmentController.dispatchActivityCreated (FragmentController.java:4)
androidx.fragment.app.FragmentActivity.onStart (FragmentActivity.java:20)
android.app.Instrumentation.callActivityOnStart (Instrumentation.java:1582)
android.app.Activity.performStart (Activity.java:8977)
android.app.ActivityThread.handleStartActivity (ActivityThread.java:4198)
android.app.servertransaction.TransactionExecutor.performLifecycleSequence (TransactionExecutor.java:225)
android.app.servertransaction.TransactionExecutor.cycleToPath (TransactionExecutor.java:205)
android.app.servertransaction.TransactionExecutor.executeLifecycleState (TransactionExecutor.java:177)
android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:98)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:2685)
android.os.Handler.dispatchMessage (Handler.java:106)
android.os.Looper.loopOnce (Looper.java:230)
android.os.Looper.loop (Looper.java:319)
android.app.ActivityThread.main (ActivityThread.java:8893)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:608)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1103)`

/--------------/

PaymentConfiguration$Companion.loadInstance
java.lang.IllegalStateException - PaymentConfiguration was not initialized. Call PaymentConfiguration.init().
com.stripe.android
PaymentConfiguration.java:19

`Fatal Exception: java.lang.IllegalStateException
PaymentConfiguration was not initialized. Call PaymentConfiguration.init().
com.stripe.android.PaymentConfiguration$Companion.loadInstance (PaymentConfiguration.java:19)
com.stripe.android.PaymentConfiguration$Companion.getInstance (PaymentConfiguration.java:11)
com.stripe.android.view.CardWidgetViewModel$Factory.create$lambda$0 (CardWidgetViewModel.java:7)
com.stripe.android.view.CardWidgetViewModel.determineCbcEligibility (CardWidgetViewModel.java:60)
com.stripe.android.view.CardWidgetViewModel.access$determineCbcEligibility (CardWidgetViewModel.java)
com.stripe.android.view.CardWidgetViewModel$1.invokeSuspend (CardWidgetViewModel.java:42)
kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith (BaseContinuationImpl.java:11)

kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run (CoroutineScheduler.java)`

**Comment by remonh87** [comment] 2024-06-17 16:48
did you initialise the stripe library correctly?  https://github.com/flutter-stripe/flutter_stripe/blob/main/example/lib/main.dart

**Comment by KallepalliTirumalesh** [comment] 2024-06-18 04:57
Yes the functionality works fine in debug mode and release mode as well but I see these logs in firebase in production.

**Comment by remonh87** [comment] 2024-06-23 11:03
This is duplicate of #1282  and also it is something that needs to be fixed by the stripe library see: https://github.com/stripe/stripe-react-native/issues/1425

**Closed by remonh87** 2024-06-23 11:03 UTC
Labels: Awaiting response, needs triage
