### ISSUE TITLE
PlatformException(flutter_stripe initialization failed, The plugin failed to initialize. Are you using FlutterFragmentActivity?

### ISSUE THREAD

**Issue by emran92** [flutter-stripe/flutter_stripe#388] opened 2021-10-09 09:18 UTC
**Describe the bug**
If I [add tools:replace on AndroidManifest.xml](https://github.com/emran92/stripe_test_mrn/blob/1b5164e9ef8c35570b3ba93a1bd746cd4ef7e7df/android/app/src/main/AndroidManifest.xml#L6) which in my case was required for jitsi_meet plugin, The error occurs after the splash screen. But removing tools:replace it works fine. 

**To Reproduce**
1. Add jitsi_meet plugin to example project.
2. Add required setups for jitsi_meet plugin.
3. The app gets stuck after splash screen with error PlatformException(flutter_stripe initialization failed, The plugin failed to initialize. Are you using FlutterFragmentActivity?

or run this project -> https://github.com/emran92/stripe_test_mrn

**Expected behavior**

**Smartphone / tablet**
 - Device: POCO F1
 - OS: Android 10
 - Package version: 2.0.0
 - Flutter version: Channel master, 2.6.0-12.0.pre.196

**Additional context**
N/A

Please suggest me a solution.

**Comment by jonasbark** [comment] 2021-10-10 08:45
Dupe of https://github.com/flutter-stripe/flutter_stripe/issues/197
The jitsi_meet plugin is not compatible with this package.

**Closed by jonasbark** 2021-10-10 08:45 UTC
