### ISSUE TITLE
The payment was made with an incorrect postal code format

### ISSUE THREAD

**Issue by LeliaVlasenko** [flutter-stripe/flutter_stripe#1350] opened 2023-08-02 08:14 UTC
The payment was made with an incorrect postal code format for several countries on iOS only:
Test data: "ABC123" (USA), "1234567" (UK), "XYZ" (Canada)
1. Click the «Pay» button
2. Enter «Test» on the Name field
3. Enter «4242424242424242» on the Card number field
4. Enter «12/24» 
5. Enter «242» CVC
6. Choose UK Country
7. Enter «1234567» on the Postal code 

Reproduce for several countries:
Test data: "ABC123" (USA), "1234567" (UK), "XYZ" (Canada)

Expected behavior: Payment declined. An error is displayed

 - Device: [iPhone 12]
 - OS: [e.g. iOS 16.6 ]
 - Package version: 9.2.2
 - Flutter version 3.10.5

**Comment by remonh87** [comment] 2023-08-03 18:36
Duplicate of #1334

**Closed by remonh87** 2023-08-03 18:36 UTC
Labels: needs triage
