### ISSUE TITLE
Flutter_Stripe and Jitsi_Meet_Wrapper dependencies not working together

### ISSUE THREAD

**Issue by mbebs** [flutter-stripe/flutter_stripe#1332] opened 2023-07-24 00:25 UTC
**Describe the bug**
Any project that has both Flutter Stripe and Jitsi_Meet_Wrapper dependencies, the Jitsi_Meet_Wrapper crashes, the Flutter_Stripe also crashes the app.

**To Reproduce**
1. Copy the Jitsi_Meet_Wrapper example flutter app from pub.dev
2. Add Jitsi_Meet_Wrapper dependency: 
3. Add Flutter_Stripe dependency: e.g flutter_stripe: ^9.3.0
4. Try to create or join a meeting. App crashes. Without the flutter_Stripe dependency added, app runs with no issues.

**Expected behavior**
Meeting is expected to start with no issues

**Errors **
D/ReactInstanceManagerHolder(28424): initializing RN with Activity
D/AndroidRuntime(28424): Shutting down VM
E/AndroidRuntime(28424): FATAL EXCEPTION: main
E/AndroidRuntime(28424): Process: com.myadd.jitsi, PID: 28424
E/AndroidRuntime(28424): java.lang.NoSuchMethodError: No static method builder()Lcom/facebook/react/common/MapBuilder$Builder; in class Lcom/facebook/react/common/MapBuilder; or its super classes (declaration of 'com.facebook.react.common.MapBuilder' appears in /data/app/~~DVwcobJ_5v53qTVM-P-ESA==/com.myadd.jitsi-2hp7u0MQWNoXC1yia3aPIA==/base.apk!classes14.dex)
E/AndroidRuntime(28424): at com.facebook.react.ReactAndroidHWInputDeviceHelper.(ReactAndroidHWInputDeviceHelper.java:25)
E/AndroidRuntime(28424): at com.facebook.react.ReactRootView.(ReactRootView.java:100)
E/AndroidRuntime(28424): at org.jitsi.meet.sdk.JitsiMeetView.createReactRootView(JitsiMeetView.java:181)
E/AndroidRuntime(28424): at org.jitsi.meet.sdk.JitsiMeetView.setProps(JitsiMeetView.java:224)
E/AndroidRuntime(28424): at org.jitsi.meet.sdk.JitsiMeetView.join(JitsiMeetView.java:157)
E/AndroidRuntime(28424): at org.jitsi.meet.sdk.JitsiMeetActivity.join(JitsiMeetActivity.java:174)
E/AndroidRuntime(28424): at org.jitsi.meet.sdk.JitsiMeetActivity.initialize(JitsiMeetActivity.java:220)
E/AndroidRuntime(28424): at org.jitsi.meet.sdk.JitsiMeetActivity.onCreate(JitsiMeetActivity.java:109)
E/AndroidRuntime(28424): at dev.saibotma.jitsi_meet_wrapper.JitsiMeetWrapperActivity.onCreate(JitsiMeetWrapperActivity.kt:37)
E/AndroidRuntime(28424): at android.app.Activity.performCreate(Activity.java:8000)
E/AndroidRuntime(28424): at android.app.Activity.performCreate(Activity.java:7984)
E/AndroidRuntime(28424): at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
E/AndroidRuntime(28424): at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)
E/AndroidRuntime(28424): at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
E/AndroidRuntime(28424): at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
E/AndroidRuntime(28424): at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime(28424): at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime(28424): at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
E/AndroidRuntime(28424): at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(28424): at android.os.Looper.loop(Looper.java:223)
E/AndroidRuntime(28424): at android.app.ActivityThread.main(ActivityThread.java:7656)
E/AndroidRuntime(28424): at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(28424): at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/AndroidRuntime(28424): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/JitsiMeetSDK(28424): JitsiMeetUncaughtExceptionHandler FATAL ERROR
E/JitsiMeetSDK(28424): java.lang.NoSuchMethodError: No static method builder()Lcom/facebook/react/common/MapBuilder$Builder; in class Lcom/facebook/react/common/MapBuilder; or its super classes (declaration of 'com.facebook.react.common.MapBuilder' appears in /data/app/~~DVwcobJ_5v53qTVM-P-ESA==/com.zabtel.njangi-2hp7u0MQWNoXC1yia3aPIA==/base.apk!classes14.dex)
E/JitsiMeetSDK(28424): at com.facebook.react.ReactAndroidHWInputDeviceHelper.(ReactAndroidHWInputDeviceHelper.java:25)
E/JitsiMeetSDK(28424): at com.facebook.react.ReactRootView.(ReactRootView.java:100)
E/JitsiMeetSDK(28424): at org.jitsi.meet.sdk.JitsiMeetView.createReactRootView(JitsiMeetView.java:181)
E/JitsiMeetSDK(28424): at org.jitsi.meet.sdk.JitsiMeetView.setProps(JitsiMeetView.java:224)
E/JitsiMeetSDK(28424): at org.jitsi.meet.sdk.JitsiMeetView.join(JitsiMeetView.java:157)
E/JitsiMeetSDK(28424): at org.jitsi.meet.sdk.JitsiMeetActivity.join(JitsiMeetActivity.java:174)
E/JitsiMeetSDK(28424): at org.jitsi.meet.sdk.JitsiMeetActivity.initialize(JitsiMeetActivity.java:220)
E/JitsiMeetSDK(28424): at org.jitsi.meet.sdk.JitsiMeetActivity.onCreate(JitsiMeetActivity.java:109)
E/JitsiMeetSDK(28424): at dev.saibotma.jitsi_meet_wrapper.JitsiMeetWrapperActivity.onCreate(JitsiMeetWrapperActivity.kt:37)
E/JitsiMeetSDK(28424): at android.app.Activity.performCreate(Activity.java:8000)
E/JitsiMeetSDK(28424): at android.app.Activity.performCreate(Activity.java:7984)
E/JitsiMeetSDK(28424): at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
E/JitsiMeetSDK(28424): at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)
E/JitsiMeetSDK(28424): at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
E/JitsiMeetSDK(28424): at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
E/JitsiMeetSDK(28424): at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/JitsiMeetSDK(28424): at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/JitsiMeetSDK(28424): at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
E/JitsiMeetSDK(28424): at android.os.Handler.dispatchMessage(Handler.java:106)
E/JitsiMeetSDK(28424): at android.os.Looper.loop(Looper.java:223)
E/JitsiMeetSDK(28424): at android.app.ActivityThread.main(ActivityThread.java:7656)
E/JitsiMeetSDK(28424): at java.lang.reflect.Method.invoke(Native Method)
E/JitsiMeetSDK(28424): at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/JitsiMeetSDK(28424): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/JitsiMeetSDK(28424):
E/JitsiMeetSDK(28424): java.lang.NoSuchMethodError: No static method builder()Lcom/facebook/react/common/MapBuilder$Builder; in class Lcom/facebook/react/common/MapBuilder; or its super classes (declaration of 'com.facebook.react.common.MapBuilder' appears in /data/app/~~DVwcobJ_5v53qTVM-P-ESA==/com.zabtel.njangi-2hp7u0MQWNoXC1yia3aPIA==/base.apk!classes14.dex)
E/JitsiMeetSDK(28424): at com.facebook.react.ReactAndroidHWInputDeviceHelper.(ReactAndroidHWInputDeviceHelper.java:25)
E/JitsiMeetSDK(28424): at com.facebook.react.ReactRootView.(ReactRootView.java:100)
E/JitsiMeetSDK(28424): at org.jitsi.meet.sdk.JitsiMeetView.createReactRootView(JitsiMeetView.java:181)
E/JitsiMeetSDK(28424): at org.jitsi.meet.sdk.JitsiMeetView.setProps(JitsiMeetView.java:224)
E/JitsiMeetSDK(28424): at org.jitsi.meet.sdk.JitsiMeetView.join(JitsiMeetView.java:157)
E/JitsiMeetSDK(28424): at org.jitsi.meet.sdk.JitsiMeetActivity.join(JitsiMeetActivity.java:174)
E/JitsiMeetSDK(28424): at org.jitsi.meet.sdk.JitsiMeetActivity.initialize(JitsiMeetActivity.java:220)
E/JitsiMeetSDK(28424): at org.jitsi.meet.sdk.JitsiMeetActivity.onCreate(JitsiMeetActivity.java:109)
E/JitsiMeetSDK(28424): at dev.saibotma.jitsi_meet_wrapper.JitsiMeetWrapperActivity.onCreate(JitsiMeetWrapperActivity.kt:37)
E/JitsiMeetSDK(28424): at android.app.Activity.performCreate(Activity.java:8000)
E/JitsiMeetSDK(28424): at android.app.Activity.performCreate(Activity.java:7984)
E/JitsiMeetSDK(28424): at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
E/JitsiMeetSDK(28424): at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)
E/JitsiMeetSDK(28424): at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
E/JitsiMeetSDK(28424): at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
E/JitsiMeetSDK(28424): at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/JitsiMeetSDK(28424): at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/JitsiMeetSDK(28424): at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
E/JitsiMeetSDK(28424): at android.os.Handler.dispatchMessage(Handler.java:106)
E/JitsiMeetSDK(28424): at android.os.Looper.loop(Looper.java:223)
E/JitsiMeetSDK(28424): at android.app.ActivityThread.main(ActivityThread.java:7656)
E/JitsiMeetSDK(28424): at java.lang.reflect.Method.invoke(Native Method)
E/JitsiMeetSDK(28424): at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/JitsiMeetSDK(28424): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)'

Below are the dependencies
flutter_stripe: ^9.0.0+1
jitsi_meet_wrapper: ^0.2.0+1

**Comment by jonasbark** [comment] 2023-07-24 07:39
Closing as duplicate of https://github.com/flutter-stripe/flutter_stripe/issues/1232

**Closed by jonasbark** 2023-07-24 07:39 UTC
Labels: needs triage
