### ISSUE TITLE
 keyboard not visible in when open flutter stripe payment default dialog in Android 12 device

### ISSUE THREAD

**Issue by BrijalKothari** [flutter-stripe/flutter_stripe#1433] opened 2023-10-01 03:27 UTC
**Describe the bug**

**To Reproduce**
1. Entering number 123-456-789 into the cardfield.
2. Tapping the confirm button.
3. Observe a failure with exception (including the part of the stack trace, belonging to this package) …

**Expected behavior**

**Smartphone / tablet**
 - Device: [e.g. iPhone X]
 - OS: [e.g. iOS 13, Android 10]
 - Package version: [e.g. 1.0.0]
 - Flutter version [e.g. 2.0.0.]

**Additional context**

**Comment by BrijalKothari** [comment] 2023-10-01 03:28
Any solutions?

**Comment by remonh87** [comment] 2023-10-01 19:22
Can you give me more context about the issue ? For example a reproducible scenario? I have no idea what you mean with default dialog/

**Comment by dakman** [comment] 2023-12-19 06:05
Sounds similar to my issue.. https://github.com/flutter-stripe/flutter_stripe/issues/1560

**Comment by remonh87** [comment] 2024-04-14 15:38
closing this because no reaction when asking for clarification

**Closed by remonh87** 2024-04-14 15:38 UTC
Labels: needs triage
