### ISSUE TITLE
Bump/repost of [39]: Stripe Terminal support

### ISSUE THREAD

**Issue by ZeWhiteHatHacker** [flutter-stripe/flutter_stripe#1503] opened 2023-11-26 09:39 UTC
https://github.com/flutter-stripe/flutter_stripe/issues/39

"Would it be possible to include the terminal SDK into this new project, there is a andriod and iOS SDK available from stripe but no flutter implementation that I can find currently.

There is a growing use case for accepting in person payments via stripe as well as online payments
[stripe terminal docs](https://stripe.com/docs/terminal)"

2 years later, there is a grown and still growing need for this integration into a reliable sdk for flutter!

Thanks!

**Comment by remonh87** [comment] 2023-11-26 15:37
duplicate of #39  we would love to integrate the terminal but at the moment we are only with 2 maintainers and it is very hard to keep up to date with the main sdk of stripe so progress on it is super slow.

**Closed by remonh87** 2023-11-26 15:37 UTC
Labels: needs triage
