### ISSUE TITLE
Google Pay without webhook: PlatformException(Failed, Card details not complete, null, null)

### ISSUE THREAD

**Issue by quentinleguennec** [flutter-stripe/flutter_stripe#278] opened 2021-08-12 15:28 UTC
**Describe the bug**
I'm trying to use Google Pay without having a webhook setup. Here is my issue:

Getting a `PlatformException(Failed, Card details not complete, null, null)` when calling `Stripe.instance.createPaymentMethod(PaymentMethodParams.cardFromToken(token: tokenId));`
`tokenId` is the token obtained from Google Pay as described in the example of this plugin:
```
token = paymentResult['paymentMethodData']['tokenizationData']['token'] as String;
      final Map<String, dynamic> tokenJson = json.decode(token) as Map<String, dynamic>;
      tokenId = tokenJson['id'] as String;
```

**To Reproduce**
1. Setup Google Pay.
2. Use the `GooglePayButton` like in the plugin example (google_pay_screen.dart) to get a `paymentResult`
3. Extract the token from `paymentResult` and pass it to `Stripe.instance.createPaymentMethod` (see under).
```
  Future<void> processGooglePayPayment(Map<String, dynamic> paymentResult) async {
    // 1. Get token Id
    final String token = paymentResult['paymentMethodData']['tokenizationData']['token'] as String;
    final Map<String, dynamic> tokenJson = json.decode(token) as Map<String, dynamic>;
    final String tokenId = tokenJson['id'] as String;
    print('tokenId = $tokenId');

    // 2. Create payment method
    // THIS THROWS `PlatformException(Failed, Card details not complete, null, null)`
    final PaymentMethod paymentMethod = await Stripe.instance.createPaymentMethod(
      PaymentMethodParams.cardFromToken(token: tokenId),
    );
  }
```

**Expected behavior**
`Stripe.instance.createPaymentMethod` would return a valid PaymentMethod that I could send to my backend to process the payment (without needing a webhook).

**Smartphone**
 - Device: Android MI 9 with android-arm64 
 - OS: Android 10 (API 29)
 - Package version: flutter_stripe: 1.2.0
 - Flutter version: Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-x64, locale en-GB)

**Additional context**
Might be related to #153

**Comment by remonh87** [comment] 2021-08-14 13:56
@quentinleguennec did you add the google pay config to the assets like described in: https://github.com/flutter-stripe/flutter_stripe/blob/main/example/assets/google_pay_payment_profile.json

also shouldn't create a payment method but confirm the payment method and use the token that you retrieved .

**Comment by quentinleguennec** [comment] 2021-08-17 13:25
@remonh87 I did add the google pay config with the proper values. I'm using the Pay plugin to retrieve the card token (which works fine).

The goal was to avoid the need for the clientSecret, as I though it would only work with Stripe webhooks configured. But turns out webhooks are not a requirement.
We changed our flow to use PaymentIntents (with clientSecret), which work fine.

I still think this error message is suggesting something is broken in the plugin, as it throws a PlatformException rather than a StripeException.

**Comment by remonh87** [comment] 2021-08-22 17:55
Thanks for giving additional context I  think it is a bug and we will investigate it. Btw we are releasing a new version soon with a new google pay integration so hopefully it will fix this scenario

**Comment by remonh87** [comment] 2021-08-23 18:23
I cannot reproduce it on our `sync` branch. We are integrating latest Stripe sdk as we speak. I will close it for now but let's reopen it in case the issue is still there in the new version which I expect we will release this week.

**Closed by remonh87** 2021-08-23 18:23 UTC

**Comment by idrish-sorathiya** [comment] 2021-12-16 06:19
Still getting this issue.  I am using 2.0.2 version of plugin. I am trying to create Payment method from token. Is any fix available?

**Comment by BriceChk** [comment] 2022-01-14 13:38
Getting the exact same issue. I'm getting the `tok_xxx` token but when I call  `Stripe.instance.createPaymentMethod(PaymentMethodParams.cardFromToken(token: tokenId))` I get the following exception:

````
StripeException(error: LocalizedErrorMessage(code: FailureCode.Failed, localizedMessage: Card details not complete, message: Card details not complete, stripeErrorCode: null, declineCode: null, type: null))
````

Any idea?

**Comment by LucaJeevanjee** [comment] 2022-07-14 06:09
Any updates, really need this feature?
