### ISSUE TITLE
[Google Pay] `confirmPlatformPayPaymentIntent(` with `PlatformPayConfirmParams.googlePay(...)` throws `MissingPluginException`

### ISSUE THREAD

**Issue by wrbl606** [flutter-stripe/flutter_stripe#1493] opened 2023-11-22 09:59 UTC
**Describe the bug**
Confirming a Google Pay payment, like so:

```dart
.confirmPlatformPayPaymentIntent(
    clientSecret: clientSecret,
    confirmParams: PlatformPayConfirmParams.googlePay(
      googlePay: GooglePayParams(
        testEnv: true,
        merchantCountryCode: 'de',
        currencyCode: 'EUR',
        merchantName: '[REDACTED]',
      ),
    ),
  );
```
throws 

```plain
MissingPluginException:
No implementation found for method confirmPlatformPay on channel flutter.stripe/payments
```

**To Reproduce**

1. Obtain payment intent and client secret for a payment.
2. Use the `clientSecret` in `.confirmPlatformPayPaymentIntent` method with values described above.

**Expected behavior**
Google Pay native UI is shown, allowing the use to fullfill the payment.

**Smartphone / tablet**
 - Device: Android Emulator, Motorola One Action, Motorola One Zoom, and more
 - OS: Android 13, Android 14
 - Package version: 9.5.0+1
 - Flutter version 3.13.9

**Additional context**
Google Pay payment, with the exact same parameters works great on `flutter_stripe: 9.4.0`.

**Comment by wojciechzahradnikdeviniti** [comment] 2023-11-23 11:01
The same issue on my side

**Comment by remonh87** [comment] 2023-11-26 16:30
This should be fixed in the next version

**Comment by wrbl606** [comment] 2023-11-28 09:03
For anyone struggling with this issue, backing out to `stripe_android: 9.4.0` fixes the issue. In `pubspec.yaml`:

```yaml
...

dependencies:
  flutter_stripe: 9.5.0+1

dependencies_overrides:
  stripe_android: 9.4.0
``` 

@remonh87 Is there a timeline for the fix delivery?

**Comment by remonh87** [comment] 2023-11-28 20:38
Version 9.6.0 is released now

**Closed by remonh87** 2023-11-28 20:38 UTC
Labels: bug, Android

**Comment by oruabhinav** [comment] 2023-11-30 17:31
I am getting this error 
```
Because every version of flutter from sdk depends on meta 1.9.1 and stripe_platform_interface >=9.6.0 depends on meta ^1.10.0, flutter from sdk is incompatible with stripe_platform_interface >=9.6.0.
And because flutter_stripe >=9.6.0 depends on stripe_platform_interface ^9.6.0, flutter from sdk is incompatible with flutter_stripe >=9.6.0.
```

Can anyone help please @remonh87

**Comment by appeventic** [comment] 2023-12-15 18:01
> I am getting this error
> 
> ```
> Because every version of flutter from sdk depends on meta 1.9.1 and stripe_platform_interface >=9.6.0 depends on meta ^1.10.0, flutter from sdk is incompatible with stripe_platform_interface >=9.6.0.
> And because flutter_stripe >=9.6.0 depends on stripe_platform_interface ^9.6.0, flutter from sdk is incompatible with flutter_stripe >=9.6.0.
> ```
> 
> Can anyone help please @remonh87

Try 

![image](https://github.com/flutter-stripe/flutter_stripe/assets/141521094/2b3faa91-62dd-49b2-b77b-639f95124fe4)

**Comment by remonh87** [comment] 2023-12-18 19:47
> > I am getting this error
> > ```
> > Because every version of flutter from sdk depends on meta 1.9.1 and stripe_platform_interface >=9.6.0 depends on meta ^1.10.0, flutter from sdk is incompatible with stripe_platform_interface >=9.6.0.
> > And because flutter_stripe >=9.6.0 depends on stripe_platform_interface ^9.6.0, flutter from sdk is incompatible with flutter_stripe >=9.6.0.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Can anyone help please @remonh87
> 
> Try
> 
> ![image](https://private-user-images.githubusercontent.com/141521094/290901239-2b3faa91-62dd-49b2-b77b-639f95124fe4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5MjkwOTUsIm5iZiI6MTcwMjkyODc5NSwicGF0aCI6Ii8xNDE1MjEwOTQvMjkwOTAxMjM5LTJiM2ZhYTkxLTYyZGQtNDliMi1iNzdiLTYzOWY5NTEyNGZlNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxOFQxOTQ2MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMWExYTMyMjM1MWI1ZDc2MTljMGZiN2IyNjUyM2Q0ZTk3MWVjODc0YjZlYzFlZDYwZjQ4NzBjMmU2Yjk5OTc0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.wm0LJta2o2U-Ew4qT88xxl9zRl28jZcsCTNQpInysgk)

To add to it you must use flutter 3.16 for 9.6.0

**Comment by jon-mly** [comment] 2024-03-07 10:52
The same issue does occur when using flutter_stripe 10.0.0 and 10.1.0, running on Flutter 3.19.2

**Comment by Akhrameev** [comment] 2024-05-24 11:40
The issue is in `GooglePayLauncherFragment.kt` function `presentGooglePaySheet`. It tries to get integer value for `amount`  `(this.amount = googlePayParams.getInt("amount"))` and fails as there is no `amount` in `googlePayParams`. Sync from React Native is not always correct (it has `amount` String value in `googlePayParams` as it is stated [here](https://stripe.dev/stripe-react-native/api-reference/modules/PaymentSheet.html))
