### ISSUE TITLE
Keyboard switches on its own when using CardField on Android.

### ISSUE THREAD

**Issue by sakyoyuto** [flutter-stripe/flutter_stripe#135] opened 2021-06-11 01:40 UTC
flutter_stripe 1.0.2. I'm trying to use CardField to enter cards.
However, when I use Android, the keyboard switches every time I enter a number in the CardField.
I am running it on an actual Pixel 4a.

![screen-20210611-102656_2](https://user-images.githubusercontent.com/45416100/121617922-d9a55000-caa0-11eb-8dda-1609c213bc03.gif)

On iOS, only the number keyboard is displayed, which is very easy to use.

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.1, on macOS 11.4 20F71 darwin-arm, locale ja-JP)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.57.0)
[✓] Connected device (2 available)

• No issues found!
```

Thank you.

**Comment by jamesblasco** [comment] 2021-06-11 04:49
Hello, there is an issue in Flutter that affects the keyboard input and we have been forced to implemented like this. The issue is fixed now and should arrive soon yo master

We will make the needed changes in our package when next stable version is released

https://github.com/flutter-stripe/flutter_stripe/issues/14

**Closed by jamesblasco** 2021-06-11 04:49 UTC
