### ISSUE TITLE
lateinit property stripeSdk has not been initialized

### ISSUE THREAD

**Issue by Alfaizkhan** [flutter-stripe/flutter_stripe#1023] opened 2022-11-16 05:18 UTC
**Describe the bug**
Getting the below exception on app opened.

`E/MethodChannel#flutter.stripe/payments(12785): Failed to handle method call
E/MethodChannel#flutter.stripe/payments(12785): kotlin.UninitializedPropertyAccessException: lateinit property stripeSdk has not been initialized
E/MethodChannel#flutter.stripe/payments(12785):     at com.flutter.stripe.StripeAndroidPlugin.getStripeSdk(StripeAndroidPlugin.kt:33)
E/MethodChannel#flutter.stripe/payments(12785):     at com.flutter.stripe.StripeAndroidPlugin.onMethodCall(StripeAndroidPlugin.kt:85)
E/MethodChannel#flutter.stripe/payments(12785):     at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/MethodChannel#flutter.stripe/payments(12785):     at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/MethodChannel#flutter.stripe/payments(12785):     at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/MethodChannel#flutter.stripe/payments(12785):     at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#flutter.stripe/payments(12785):     at android.os.Handler.handleCallback(Handler.java:938)
E/MethodChannel#flutter.stripe/payments(12785):     at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#flutter.stripe/payments(12785):     at android.os.Looper.loopOnce(Looper.java:201)
E/MethodChannel#flutter.stripe/payments(12785):     at android.os.Looper.loop(Looper.java:288)
E/MethodChannel#flutter.stripe/payments(12785):     at android.app.ActivityThread.main(ActivityThread.java:7839)
E/MethodChannel#flutter.stripe/payments(12785):     at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter.stripe/payments(12785):     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/MethodChannel#flutter.stripe/payments(12785):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)`

Device : Android 12.
Version: flutter_stripe 7.0.0

**Comment by alihassan143** [comment] 2022-11-16 06:23
@remonh8
Facing Same Issue
i can confirm that its happening  in latest version
`flutter_stripe: ^7.0.0`
on is in android 
ios working fine

**Comment by alihassan143** [comment] 2022-11-16 17:40
@remonh87 
kindly check this issue now also this happening in older version of plugins also

**Comment by jonasbark** [comment] 2022-11-16 17:58
Does the example app work for you?
How are you initializing the Plugin?

Please provide a reproducible example application.

**Comment by alihassan143** [comment] 2022-11-16 18:03
@jonasbark 
i am using flutter stripe from version 2 
but now i am upgrading the project previously until from version 4 it works perfectly now it s troughing late initalize error after upgrading to latest version
event though you revert changes

**Comment by remonh87** [comment] 2022-11-16 20:52
@alihassan143  please can you provide us with reproduction steps also check if it happens in the example app. Else I fear I have to close this issue.

**Comment by alihassan143** [comment] 2022-11-17 05:28
@remonh87 
i think. their is issue with other plugins when i create separate project with. single flutter stripe_sdk it works fine when adding other plugins its did not initialized
Note:
All plugins i am using all support android 33

**Comment by Alfaizkhan** [comment] 2022-11-17 06:39
@remonh87 
Don't closed the issue.
Let me try in my application.
Will post updates here.

**Comment by jonasbark** [comment] 2022-11-17 12:07
We need a reproducible example to help here. If it's another plugin causing the issue, then we need to know which one.

**Comment by alihassan143** [comment] 2022-11-17 12:11
@jonasbark  i am using different plugins so i need to check one by one which plugin is causing issue

**Comment by alihassan143** [comment] 2022-11-17 12:15
**These are the plugins i am using**
```fluttertoast: ^8.1.1
 
  geolocator: ^9.0.2

  permission_handler: ^10.2.0
 


  firebase_core: ^2.2.0
  firebase_messaging: ^14.1.0
  google_maps_flutter: ^2.2.1
  geocoding: ^2.0.5
  image_picker: ^0.8.6
  flutter_stripe: ^7.0.0


  http: ^0.13.5

  flutter_local_notifications: ^12.0.3+1

```

**Comment by remonh87** [comment] 2022-11-29 19:40
I added the same dependencies to the example app and also my current project have almost the same dependencies.  did you check that you did  the following in main: 

```dart
 WidgetsFlutterBinding.ensureInitialized();
 await Stripe.instance.applySettings();
```

@jonasbark  created an extra check in android if the sdk is initialized #1030. Closing this for now as we cannot reproduce it.

**Closed by remonh87** 2022-11-29 19:40 UTC
Labels: needs triage
