### ISSUE TITLE
Layout inconsistency in iOS Dark mode

### ISSUE THREAD

**Issue by viktor-ohanyan** [flutter-stripe/flutter_stripe#420] opened 2021-10-31 18:11 UTC
**Describe the bug**
Payment Sheet has extra dark space at the bottom in device dark mode

**To Reproduce**
1. Go to iPhone Settings > Display & Brightness > APPEARANCE
2. Change appearance from Light to Dark
3. Observe a black space at the bottom

![IMG_2671-3](https://user-images.githubusercontent.com/1379131/139596363-91541ee5-dae6-4def-8f94-d58d8597ba8f.png) ![IMG_2670-3](https://user-images.githubusercontent.com/1379131/139596370-be58facd-93ee-461d-a106-bc595f01d403.png)

**Expected behavior**
Payment Sheet view should be the same on both device modes

**Smartphone / tablet**
 - Device: iPhone 12
 - OS: iOS 15.1
 - Package version: 2.0.1
 - Flutter version: 2.5.3

**Comment by remonh87** [comment] 2021-11-03 17:59
This is also looks like it is fixed in the newest version of the sync with the native Stripe SDK cannot reproduce it anymore there.

**Comment by remonh87** [comment] 2021-11-08 07:32
fixed in version 2.0.2

**Comment by viktor-ohanyan** [comment] 2021-11-09 08:36
@viktor-ohanyan Unfortunately, we are still facing this problem in version 2.0.2.
It's not fixed.

**Comment by remonh87** [comment] 2021-11-09 17:48
I see the issue I will raise a ticket on Stripe SDK

**Comment by remonh87** [comment] 2021-11-09 17:57
waiting for ticket: https://github.com/stripe/stripe-react-native/issues/709

**Comment by aryanbm** [comment] 2021-12-06 12:32
@remonh87 
I have the same problem, and it hasn't been fixed (flutter_stripe: ^2.0.2)

**Comment by remonh87** [comment] 2021-12-06 19:01
@aryanbm  we are waiting for stripe to fix it there is nothing on our side that we can do about it.

**Comment by remonh87** [comment] 2022-09-12 19:17
This is solved in version https://pub.dev/packages/flutter_stripe/changelog#310 where you can style the paymentsheet.

**Closed by remonh87** 2022-09-12 19:17 UTC
Labels: iOS, blocked
