### ISSUE TITLE
aubecs Texteditor doesn't work 

### ISSUE THREAD

**Issue by An9sh** [flutter-stripe/flutter_stripe#713] opened 2022-05-10 05:19 UTC
Aubecs text editor does not work if we type something in other page and open the AubecsFormField.

**Comment by remonh87** [comment] 2022-05-10 06:53
please follow the issue template and provide us some example code so we can properly triage the issue.

**Comment by An9sh** [comment] 2022-05-10 23:24
D/InputMethodManager(25363): showSoftInput() view=com.stripe.android.view.BecsDebitBsbEditText{4d4ddf1 VFED..CL. .F.P..ID 0,0-635,149 #7f080087 app:id/bsb_edit_text aid=1073741835} flags=0 reason=SHOW_SOFT_INPUT
2
D/InsetsController(25363): show(ime(), fromIme=true)
<img width="342" alt="Screen Shot 2022-05-11 at 9 22 51 am" src="https://user-images.githubusercontent.com/17683699/167740419-c185cb7b-a9ce-46f2-9fb8-fe2d670cd920.png">


D/InputMethodManager(25363): showSoftInput() view=com.stripe.android.view.BecsDebitAccountNumberEditText{3a81dd6 VFED..CL. .F.P..ID 0,0-636,149 #7f080030 app:id/account_number_edit_text aid=1073741836} flags=0 reason=SHOW_SOFT_INPUT
2
D/InsetsController(25363): show(ime(), fromIme=true)

**Comment by An9sh** [comment] 2022-05-11 00:35
I did not get any errors but cannot input value inside bsb and account number by using emulator keyboard also

The only time we can input value is when we fill this form at the starting of the app without filling any other forms in other pages.

**Comment by remonh87** [comment] 2022-05-11 05:00
did you experience the same on iOS as well?

**Comment by An9sh** [comment] 2022-05-11 06:04
I have not tried it on IOS just testing it on android.

**Comment by remonh87** [comment] 2022-05-26 08:02
yes I can reproduce it looking into it now

**Comment by remonh87** [comment] 2022-09-12 19:10
Cannot reproduce it anymore this is fixed in the latest Stripe sdk.

**Closed by remonh87** 2022-09-12 19:10 UTC
Labels: bug, Android
