### ISSUE TITLE
Getting the PaymentSheetResult response when calling presentPaymentSheet()

### ISSUE THREAD

**Issue by Pluralist** [flutter-stripe/flutter_stripe#169] opened 2021-06-28 09:39 UTC
To better handling the future after calling "presentPaymentSheet()", that would be great if we can get the PaymentSheetResult response to access "completed", "canceled" or "failed" status according to the stripe docs instead of just getting a "closed" error in the try/catch block in case the user closes the payment sheet.
Thank you all :)

**Comment by MianSaadHafeez646** [comment] 2021-06-30 23:39
yeah please add some results, if payment is success give some transaction details !!

**Comment by emmaxCreative** [comment] 2021-07-06 14:49
I would need this as well. how do we know if the payment was successful without a response?

**Comment by AndreiStefanie** [comment] 2021-07-06 17:38
The current behavior seems to be the same whether the user cancels or completes the payment (i.e. no exception is thrown). I attempted to return the result, but the required changes also include platform-specific code which I struggle to follow and debug for now.

This would be a really nice enhancement indeed.

Thank you and keep up the awesome work!

**Comment by TesfahunK** [comment] 2021-07-07 08:07
I am stuck on this too , there should be some kind of boolean response if the payment actually went through, cancelled or failed.

**Comment by kalptech2021** [comment] 2021-07-08 00:22
Same here, After cancelling the payment it does not complete the transaction but executes the code, I am not sure how to handle the cancel payment, try error block isn't working

**Comment by Bazzz-1** [comment] 2021-07-09 07:57
Yeah it does leave the function somewhat flawed if we can't check if the payment sheet was successful or cancelled.

Really hope we can get a fix for this soon!

**Comment by remonh87** [comment] 2021-07-09 08:08
Duplicate of #184 will be soon fixed.

**Closed by remonh87** 2021-07-09 08:08 UTC
Labels: enhancement
