### ISSUE TITLE
When layout cardformfield render second time on screen

### ISSUE THREAD

**Issue by sachindamco** [flutter-stripe/flutter_stripe#1585] opened 2024-01-03 14:04 UTC
[ERROR:flutter/fml/platform/android/jni_util.cc(206)] java.lang.IllegalStateException: The Android view returned from PlatformView#getView() was already added to a parent view.
E/flutter (14644): 	at io.flutter.plugin.platform.PlatformViewsController.initializePlatformViewIfNeeded(PlatformViewsController.java:1094)
E/flutter (14644): 	at io.flutter.plugin.platform.PlatformViewsController.onDisplayPlatformView(PlatformViewsController.java:1152)
E/flutter (14644): 	at io.flutter.embedding.engine.FlutterJNI.onDisplayPlatformView(FlutterJNI.java:1461)
E/flutter (14644): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (14644): 	at android.os.MessageQueue.next(MessageQueue.java:335)
E/flutter (14644): 	at android.os.Looper.loop(Looper.java:193)
E/flutter (14644): 	at android.app.ActivityThread.main(ActivityThread.java:8057)
E/flutter (14644): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (14644): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
E/flutter (14644): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)
E/flutter (14644): 
F/flutter (14644): [FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(1694)] Check failed: fml::jni::CheckException(env). 
F/libc    (14644): Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 14644

**Comment by jonasbark** [comment] 2024-01-08 12:49
Do you have a reproducible example code for this behavior?

**Comment by sachindamco** [comment] 2024-01-08 13:11
> Do you have a reproducible example code for this behavior?

I just used Cardformfield. first time screen will shown but second time app crashed.

**Comment by remonh87** [comment] 2024-03-02 10:30
closed as cannot reproduce

**Closed by remonh87** 2024-03-02 10:30 UTC
Labels: Android, Awaiting response

**Comment by ebjorklund01** [comment] 2024-05-21 17:39
We are running into this issue as well. This is crashing our Flutter Android apps when run in `--release` mode but not in `--development` mode. Adding 

```gradle
minifyEnabled false
shrinkResources false
```

To our `android/app/build.gradle` fixes the issue so it seems like a resource is being removed during [Android shrinking and obfuscation](https://developer.android.com/build/shrink-code). I would hypothesize that the [proguard-rules.txt](https://github.com/flutter-stripe/flutter_stripe/blob/main/packages/stripe_android/android/proguard-rules.txt) file needs an additional rule.

## Stripe Versions: 
```
flutter_stripe: "10.1.1"
stripe_android: "10.1.1"
```

## Sample code
```dart
          Center(
            child: stripe.CardField(
              controller: _cardEditController,
              onCardChanged: (card) async {
                if (card?.complete ?? false) {
                  widget.onCardDetailsCompleted(true);
                } else {
                  widget.onCardDetailsCompleted(false);
                }
              },
            ),
          ),
```

## Flutter Doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.19.6, on macOS 14.4.1 23E224 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.1)
[✓] VS Code (version 1.89.1)
[✓] Connected device (5 available)
[✓] Network resources

• No issues found!
```

**Comment by ebjorklund01** [comment] 2024-05-21 17:41
It seems like the crash is related to the icon and font used inside of the `CardField`.

**Comment by ebjorklund01** [comment] 2024-05-22 21:48
@remonh87 Do you have any initial thoughts?

**Comment by mohsinnaqvi606** [comment] 2024-09-20 04:25
Issue is still reproducible
