### ISSUE TITLE
return result from Stripe.instance.presentPaymentSheet

### ISSUE THREAD

**Issue by awaik** [flutter-stripe/flutter_stripe#190] opened 2021-07-08 06:25 UTC
Right now `Stripe.instance.presentPaymentSheet` returns void Future. In this case if user closes the payment screen he will get message 'Payment successfully completed'.

https://github.com/flutter-stripe/flutter_stripe/blob/e58bdadfb4e47b74f53d850e4ac98e955aabd770/example/lib/screens/payment_sheet_screen.dart#L87-L105

**Comment by awaik** [comment] 2021-07-08 06:26
Found that this issue is connected with https://github.com/flutter-stripe/flutter_stripe/issues/184

**Comment by remonh87** [comment] 2021-07-08 08:07
Yes it is a duplicate of #184  will close this one. We expect to have a fox next release

**Closed by remonh87** 2021-07-08 08:07 UTC
