### ISSUE TITLE
Weird behaviour of StripeCard Widget on Android

### ISSUE THREAD

**Issue by jstnw10** [flutter-stripe/flutter_stripe#178] opened 2021-07-05 15:17 UTC
After typing a number the keyboard jumps back to normal text input. Could the behaviour be changed to numeric input only? Also, the expiration date does not work the correct way if the card number isn't completed. The separator between the month and the year does not appear. When I remove a character, the focus jumps back to the card number. 

I am currently on version 1.1.0. There is just a CardField on white background.

It's frustrating to switch between text and numbers all the time. Please make the keyboard type configurable or set it to number only. Also, switching between card number and expiration date shouldn't cause any issues.

Realme X2 Pro on Android 10.

**Comment by jonasbark** [comment] 2021-07-05 15:18
Dupe of https://github.com/flutter-stripe/flutter_stripe/issues/14
Also check out https://github.com/flutter-stripe/flutter_stripe#known-issues

**Closed by jonasbark** 2021-07-05 15:18 UTC
